// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/calls": {
    params: {};
  };
  "/calls/:season": {
    params: {
      "season": string;
    };
  };
  "/calls/:season/:episode": {
    params: {
      "season": string;
      "episode": string;
    };
  };
  "/calls/:season/:episode/:slug": {
    params: {
      "season": string;
      "episode": string;
      "slug": string;
    };
  };
  "/chats": {
    params: {};
  };
  "/chats/guest-info": {
    params: {};
  };
  "/chats/:season": {
    params: {
      "season": string;
    };
  };
  "/discord": {
    params: {};
  };
  "/discord/callback": {
    params: {};
  };
  "/me": {
    params: {};
  };
  "/me/download.json": {
    params: {};
  };
  "/talks": {
    params: {};
  };
  "/talks/:slug": {
    params: {
      "slug": string;
    };
  };
  "/404": {
    params: {};
  };
  "/500": {
    params: {};
  };
  "/about": {
    params: {};
  };
  "/blog": {
    params: {};
  };
  "/blog.json": {
    params: {};
  };
  "/contact": {
    params: {};
  };
  "/courses": {
    params: {};
  };
  "/credits": {
    params: {};
  };
  "/forgot-password": {
    params: {};
  };
  "/healthcheck": {
    params: {};
  };
  "/index1": {
    params: {};
  };
  "/kody": {
    params: {};
  };
  "/login": {
    params: {};
  };
  "/magic": {
    params: {};
  };
  "/refresh-commit-sha.json": {
    params: {};
  };
  "/reset-password": {
    params: {};
  };
  "/resume": {
    params: {};
  };
  "/search": {
    params: {};
  };
  "/signup": {
    params: {};
  };
  "/subscribe": {
    params: {};
  };
  "/testimonials": {
    params: {};
  };
  "/youtube": {
    params: {};
  };
  "/:slug": {
    params: {
      "slug": string;
    };
  };
  "/*": {
    params: {
      "*": string;
    };
  };
  "/mcp": {
    params: {};
  };
  "/calls/admin": {
    params: {};
  };
  "/calls/admin/:callId": {
    params: {
      "callId": string;
    };
  };
  "/calls/record": {
    params: {};
  };
  "/calls/record/new": {
    params: {};
  };
  "/calls/record/:callId": {
    params: {
      "callId": string;
    };
  };
  "/.well-known/oauth-authorization-server": {
    params: {};
  };
  "/.well-known/oauth-protected-resource": {
    params: {};
  };
  "/action/kit": {
    params: {};
  };
  "/action/mark-as-read": {
    params: {};
  };
  "/action/refresh-cache": {
    params: {};
  };
  "/action/set-theme": {
    params: {};
  };
  "/blog/list": {
    params: {};
  };
  "/blog/rss.xml": {
    params: {};
  };
  "/cache/admin": {
    params: {};
  };
  "/me/admin": {
    params: {};
  };
  "/me/passkeys": {
    params: {};
  };
  "/me/password": {
    params: {};
  };
  "/oauth/authorize": {
    params: {};
  };
  "/resources/favorite": {
    params: {};
  };
  "/resources/heapsnapshot": {
    params: {};
  };
  "/resources/lookout": {
    params: {};
  };
  "/resources/promotification": {
    params: {};
  };
  "/resources/search": {
    params: {};
  };
  "/search/admin": {
    params: {};
  };
  "/blog/:slug": {
    params: {
      "slug": string;
    };
  };
  "/s/:query": {
    params: {
      "query": string;
    };
  };
  "/resources/cache/sqlite": {
    params: {};
  };
  "/resources/calls/call-audio": {
    params: {};
  };
  "/resources/calls/draft-episode-audio": {
    params: {};
  };
  "/resources/calls/draft-response-audio": {
    params: {};
  };
  "/resources/calls/draft-status": {
    params: {};
  };
  "/resources/calls/episode-audio-callback": {
    params: {};
  };
  "/resources/calls/save": {
    params: {};
  };
  "/resources/calls/text-to-speech": {
    params: {};
  };
  "/resources/webauthn/generate-authentication-options": {
    params: {};
  };
  "/resources/webauthn/generate-registration-options": {
    params: {};
  };
  "/resources/webauthn/verify-authentication": {
    params: {};
  };
  "/resources/webauthn/verify-registration": {
    params: {};
  };
  "/chats/:season/:episode": {
    params: {
      "season": string;
      "episode": string;
    };
  };
  "/resources/cache/lru/:cacheKey": {
    params: {
      "cacheKey": string;
    };
  };
  "/resources/cache/sqlite/:cacheKey": {
    params: {
      "cacheKey": string;
    };
  };
  "/chats/:season/:episode/:slug": {
    params: {
      "season": string;
      "episode": string;
      "slug": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/calls" | "/calls/:season" | "/calls/:season/:episode" | "/calls/:season/:episode/:slug" | "/chats" | "/chats/guest-info" | "/chats/:season" | "/discord" | "/discord/callback" | "/me" | "/me/download.json" | "/talks" | "/talks/:slug" | "/404" | "/500" | "/about" | "/blog" | "/blog.json" | "/contact" | "/courses" | "/credits" | "/forgot-password" | "/healthcheck" | "/index1" | "/kody" | "/login" | "/magic" | "/refresh-commit-sha.json" | "/reset-password" | "/resume" | "/search" | "/signup" | "/subscribe" | "/testimonials" | "/youtube" | "/:slug" | "/*" | "/mcp" | "/calls/admin" | "/calls/admin/:callId" | "/calls/record" | "/calls/record/new" | "/calls/record/:callId" | "/.well-known/oauth-authorization-server" | "/.well-known/oauth-protected-resource" | "/action/kit" | "/action/mark-as-read" | "/action/refresh-cache" | "/action/set-theme" | "/blog/list" | "/blog/rss.xml" | "/cache/admin" | "/me/admin" | "/me/passkeys" | "/me/password" | "/oauth/authorize" | "/resources/favorite" | "/resources/heapsnapshot" | "/resources/lookout" | "/resources/promotification" | "/resources/search" | "/search/admin" | "/blog/:slug" | "/s/:query" | "/resources/cache/sqlite" | "/resources/calls/call-audio" | "/resources/calls/draft-episode-audio" | "/resources/calls/draft-response-audio" | "/resources/calls/draft-status" | "/resources/calls/episode-audio-callback" | "/resources/calls/save" | "/resources/calls/text-to-speech" | "/resources/webauthn/generate-authentication-options" | "/resources/webauthn/generate-registration-options" | "/resources/webauthn/verify-authentication" | "/resources/webauthn/verify-registration" | "/chats/:season/:episode" | "/resources/cache/lru/:cacheKey" | "/resources/cache/sqlite/:cacheKey" | "/chats/:season/:episode/:slug";
  };
  "routes/index.tsx": {
    id: "routes/index";
    page: "/";
  };
  "routes/calls/_layout.tsx": {
    id: "routes/calls/_layout";
    page: "/calls" | "/calls/:season" | "/calls/:season/:episode" | "/calls/:season/:episode/:slug";
  };
  "routes/calls/index.tsx": {
    id: "routes/calls/index";
    page: "/calls";
  };
  "routes/calls/$season/_layout.tsx": {
    id: "routes/calls/$season/_layout";
    page: "/calls/:season" | "/calls/:season/:episode" | "/calls/:season/:episode/:slug";
  };
  "routes/calls/$season/$episode.tsx": {
    id: "routes/calls/$season/$episode";
    page: "/calls/:season/:episode";
  };
  "routes/calls/$season/$episode/$slug.tsx": {
    id: "routes/calls/$season/$episode/$slug";
    page: "/calls/:season/:episode/:slug";
  };
  "routes/chats/_layout.tsx": {
    id: "routes/chats/_layout";
    page: "/chats" | "/chats/guest-info" | "/chats/:season";
  };
  "routes/chats/index.tsx": {
    id: "routes/chats/index";
    page: "/chats";
  };
  "routes/chats/guest-info.tsx": {
    id: "routes/chats/guest-info";
    page: "/chats/guest-info";
  };
  "routes/chats/$season.tsx": {
    id: "routes/chats/$season";
    page: "/chats/:season";
  };
  "routes/discord/_layout.tsx": {
    id: "routes/discord/_layout";
    page: "/discord" | "/discord/callback";
  };
  "routes/discord/index.tsx": {
    id: "routes/discord/index";
    page: "/discord";
  };
  "routes/discord/callback.tsx": {
    id: "routes/discord/callback";
    page: "/discord/callback";
  };
  "routes/me/_layout.tsx": {
    id: "routes/me/_layout";
    page: "/me" | "/me/download.json";
  };
  "routes/me/download[.]json.tsx": {
    id: "routes/me/download[.]json";
    page: "/me/download.json";
  };
  "routes/talks/_layout.tsx": {
    id: "routes/talks/_layout";
    page: "/talks" | "/talks/:slug";
  };
  "routes/talks/$slug.tsx": {
    id: "routes/talks/$slug";
    page: "/talks/:slug";
  };
  "routes/404.tsx": {
    id: "routes/404";
    page: "/404";
  };
  "routes/500.tsx": {
    id: "routes/500";
    page: "/500";
  };
  "routes/about.tsx": {
    id: "routes/about";
    page: "/about";
  };
  "routes/blog.tsx": {
    id: "routes/blog";
    page: "/blog";
  };
  "routes/blog[.]json.tsx": {
    id: "routes/blog[.]json";
    page: "/blog.json";
  };
  "routes/contact.tsx": {
    id: "routes/contact";
    page: "/contact";
  };
  "routes/courses.tsx": {
    id: "routes/courses";
    page: "/courses";
  };
  "routes/credits.tsx": {
    id: "routes/credits";
    page: "/credits";
  };
  "routes/forgot-password.tsx": {
    id: "routes/forgot-password";
    page: "/forgot-password";
  };
  "routes/healthcheck.tsx": {
    id: "routes/healthcheck";
    page: "/healthcheck";
  };
  "routes/index1.tsx": {
    id: "routes/index1";
    page: "/index1";
  };
  "routes/kody.tsx": {
    id: "routes/kody";
    page: "/kody";
  };
  "routes/login.tsx": {
    id: "routes/login";
    page: "/login";
  };
  "routes/magic.tsx": {
    id: "routes/magic";
    page: "/magic";
  };
  "routes/refresh-commit-sha[.]json.tsx": {
    id: "routes/refresh-commit-sha[.]json";
    page: "/refresh-commit-sha.json";
  };
  "routes/reset-password.tsx": {
    id: "routes/reset-password";
    page: "/reset-password";
  };
  "routes/resume.tsx": {
    id: "routes/resume";
    page: "/resume";
  };
  "routes/search.tsx": {
    id: "routes/search";
    page: "/search";
  };
  "routes/signup.tsx": {
    id: "routes/signup";
    page: "/signup";
  };
  "routes/subscribe.tsx": {
    id: "routes/subscribe";
    page: "/subscribe";
  };
  "routes/testimonials.tsx": {
    id: "routes/testimonials";
    page: "/testimonials";
  };
  "routes/youtube.tsx": {
    id: "routes/youtube";
    page: "/youtube";
  };
  "routes/$slug.tsx": {
    id: "routes/$slug";
    page: "/:slug";
  };
  "routes/$.tsx": {
    id: "routes/$";
    page: "/*";
  };
  "routes/mcp/index.ts": {
    id: "routes/mcp/index";
    page: "/mcp";
  };
  "routes/calls_.admin/_layout.tsx": {
    id: "routes/calls_.admin/_layout";
    page: "/calls/admin" | "/calls/admin/:callId";
  };
  "routes/calls_.admin/index.tsx": {
    id: "routes/calls_.admin/index";
    page: "/calls/admin";
  };
  "routes/calls_.admin/$callId.tsx": {
    id: "routes/calls_.admin/$callId";
    page: "/calls/admin/:callId";
  };
  "routes/calls_.record/_layout.tsx": {
    id: "routes/calls_.record/_layout";
    page: "/calls/record" | "/calls/record/new" | "/calls/record/:callId";
  };
  "routes/calls_.record/index.tsx": {
    id: "routes/calls_.record/index";
    page: "/calls/record";
  };
  "routes/calls_.record/new.tsx": {
    id: "routes/calls_.record/new";
    page: "/calls/record/new";
  };
  "routes/calls_.record/$callId.tsx": {
    id: "routes/calls_.record/$callId";
    page: "/calls/record/:callId";
  };
  "routes/[.]well-known/oauth-authorization-server.ts": {
    id: "routes/[.]well-known/oauth-authorization-server";
    page: "/.well-known/oauth-authorization-server";
  };
  "routes/[.]well-known/oauth-protected-resource.ts": {
    id: "routes/[.]well-known/oauth-protected-resource";
    page: "/.well-known/oauth-protected-resource";
  };
  "routes/action/kit.tsx": {
    id: "routes/action/kit";
    page: "/action/kit";
  };
  "routes/action/mark-as-read.tsx": {
    id: "routes/action/mark-as-read";
    page: "/action/mark-as-read";
  };
  "routes/action/refresh-cache.tsx": {
    id: "routes/action/refresh-cache";
    page: "/action/refresh-cache";
  };
  "routes/action/set-theme.tsx": {
    id: "routes/action/set-theme";
    page: "/action/set-theme";
  };
  "routes/blog_/list.tsx": {
    id: "routes/blog_/list";
    page: "/blog/list";
  };
  "routes/blog_/rss[.]xml.tsx": {
    id: "routes/blog_/rss[.]xml";
    page: "/blog/rss.xml";
  };
  "routes/cache.admin.tsx": {
    id: "routes/cache.admin";
    page: "/cache/admin";
  };
  "routes/me_.admin.tsx": {
    id: "routes/me_.admin";
    page: "/me/admin";
  };
  "routes/me_.passkeys.tsx": {
    id: "routes/me_.passkeys";
    page: "/me/passkeys";
  };
  "routes/me_.password.tsx": {
    id: "routes/me_.password";
    page: "/me/password";
  };
  "routes/oauth.authorize.tsx": {
    id: "routes/oauth.authorize";
    page: "/oauth/authorize";
  };
  "routes/resources/favorite.tsx": {
    id: "routes/resources/favorite";
    page: "/resources/favorite";
  };
  "routes/resources/heapsnapshot.ts": {
    id: "routes/resources/heapsnapshot";
    page: "/resources/heapsnapshot";
  };
  "routes/resources/lookout.ts": {
    id: "routes/resources/lookout";
    page: "/resources/lookout";
  };
  "routes/resources/promotification.tsx": {
    id: "routes/resources/promotification";
    page: "/resources/promotification";
  };
  "routes/resources/search.ts": {
    id: "routes/resources/search";
    page: "/resources/search";
  };
  "routes/search.admin.tsx": {
    id: "routes/search.admin";
    page: "/search/admin";
  };
  "routes/blog_/$slug.tsx": {
    id: "routes/blog_/$slug";
    page: "/blog/:slug";
  };
  "routes/s.$query.tsx": {
    id: "routes/s.$query";
    page: "/s/:query";
  };
  "routes/resources/cache.sqlite.ts": {
    id: "routes/resources/cache.sqlite";
    page: "/resources/cache/sqlite";
  };
  "routes/resources/calls/call-audio.ts": {
    id: "routes/resources/calls/call-audio";
    page: "/resources/calls/call-audio";
  };
  "routes/resources/calls/draft-episode-audio.ts": {
    id: "routes/resources/calls/draft-episode-audio";
    page: "/resources/calls/draft-episode-audio";
  };
  "routes/resources/calls/draft-response-audio.ts": {
    id: "routes/resources/calls/draft-response-audio";
    page: "/resources/calls/draft-response-audio";
  };
  "routes/resources/calls/draft-status.ts": {
    id: "routes/resources/calls/draft-status";
    page: "/resources/calls/draft-status";
  };
  "routes/resources/calls/episode-audio-callback.ts": {
    id: "routes/resources/calls/episode-audio-callback";
    page: "/resources/calls/episode-audio-callback";
  };
  "routes/resources/calls/save.tsx": {
    id: "routes/resources/calls/save";
    page: "/resources/calls/save";
  };
  "routes/resources/calls/text-to-speech.tsx": {
    id: "routes/resources/calls/text-to-speech";
    page: "/resources/calls/text-to-speech";
  };
  "routes/resources/webauthn/generate-authentication-options.ts": {
    id: "routes/resources/webauthn/generate-authentication-options";
    page: "/resources/webauthn/generate-authentication-options";
  };
  "routes/resources/webauthn/generate-registration-options.ts": {
    id: "routes/resources/webauthn/generate-registration-options";
    page: "/resources/webauthn/generate-registration-options";
  };
  "routes/resources/webauthn/verify-authentication.ts": {
    id: "routes/resources/webauthn/verify-authentication";
    page: "/resources/webauthn/verify-authentication";
  };
  "routes/resources/webauthn/verify-registration.ts": {
    id: "routes/resources/webauthn/verify-registration";
    page: "/resources/webauthn/verify-registration";
  };
  "routes/chats_/$season_.$episode.tsx": {
    id: "routes/chats_/$season_.$episode";
    page: "/chats/:season/:episode";
  };
  "routes/resources/cache.lru.$cacheKey.ts": {
    id: "routes/resources/cache.lru.$cacheKey";
    page: "/resources/cache/lru/:cacheKey";
  };
  "routes/resources/cache.sqlite_.$cacheKey.ts": {
    id: "routes/resources/cache.sqlite_.$cacheKey";
    page: "/resources/cache/sqlite/:cacheKey";
  };
  "routes/chats_/$season.$episode_.$slug.tsx": {
    id: "routes/chats_/$season.$episode_.$slug";
    page: "/chats/:season/:episode/:slug";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/index": typeof import("./app/routes/index.tsx");
  "routes/calls/_layout": typeof import("./app/routes/calls/_layout.tsx");
  "routes/calls/index": typeof import("./app/routes/calls/index.tsx");
  "routes/calls/$season/_layout": typeof import("./app/routes/calls/$season/_layout.tsx");
  "routes/calls/$season/$episode": typeof import("./app/routes/calls/$season/$episode.tsx");
  "routes/calls/$season/$episode/$slug": typeof import("./app/routes/calls/$season/$episode/$slug.tsx");
  "routes/chats/_layout": typeof import("./app/routes/chats/_layout.tsx");
  "routes/chats/index": typeof import("./app/routes/chats/index.tsx");
  "routes/chats/guest-info": typeof import("./app/routes/chats/guest-info.tsx");
  "routes/chats/$season": typeof import("./app/routes/chats/$season.tsx");
  "routes/discord/_layout": typeof import("./app/routes/discord/_layout.tsx");
  "routes/discord/index": typeof import("./app/routes/discord/index.tsx");
  "routes/discord/callback": typeof import("./app/routes/discord/callback.tsx");
  "routes/me/_layout": typeof import("./app/routes/me/_layout.tsx");
  "routes/me/download[.]json": typeof import("./app/routes/me/download[.]json.tsx");
  "routes/talks/_layout": typeof import("./app/routes/talks/_layout.tsx");
  "routes/talks/$slug": typeof import("./app/routes/talks/$slug.tsx");
  "routes/404": typeof import("./app/routes/404.tsx");
  "routes/500": typeof import("./app/routes/500.tsx");
  "routes/about": typeof import("./app/routes/about.tsx");
  "routes/blog": typeof import("./app/routes/blog.tsx");
  "routes/blog[.]json": typeof import("./app/routes/blog[.]json.tsx");
  "routes/contact": typeof import("./app/routes/contact.tsx");
  "routes/courses": typeof import("./app/routes/courses.tsx");
  "routes/credits": typeof import("./app/routes/credits.tsx");
  "routes/forgot-password": typeof import("./app/routes/forgot-password.tsx");
  "routes/healthcheck": typeof import("./app/routes/healthcheck.tsx");
  "routes/index1": typeof import("./app/routes/index1.tsx");
  "routes/kody": typeof import("./app/routes/kody.tsx");
  "routes/login": typeof import("./app/routes/login.tsx");
  "routes/magic": typeof import("./app/routes/magic.tsx");
  "routes/refresh-commit-sha[.]json": typeof import("./app/routes/refresh-commit-sha[.]json.tsx");
  "routes/reset-password": typeof import("./app/routes/reset-password.tsx");
  "routes/resume": typeof import("./app/routes/resume.tsx");
  "routes/search": typeof import("./app/routes/search.tsx");
  "routes/signup": typeof import("./app/routes/signup.tsx");
  "routes/subscribe": typeof import("./app/routes/subscribe.tsx");
  "routes/testimonials": typeof import("./app/routes/testimonials.tsx");
  "routes/youtube": typeof import("./app/routes/youtube.tsx");
  "routes/$slug": typeof import("./app/routes/$slug.tsx");
  "routes/$": typeof import("./app/routes/$.tsx");
  "routes/mcp/index": typeof import("./app/routes/mcp/index.ts");
  "routes/calls_.admin/_layout": typeof import("./app/routes/calls_.admin/_layout.tsx");
  "routes/calls_.admin/index": typeof import("./app/routes/calls_.admin/index.tsx");
  "routes/calls_.admin/$callId": typeof import("./app/routes/calls_.admin/$callId.tsx");
  "routes/calls_.record/_layout": typeof import("./app/routes/calls_.record/_layout.tsx");
  "routes/calls_.record/index": typeof import("./app/routes/calls_.record/index.tsx");
  "routes/calls_.record/new": typeof import("./app/routes/calls_.record/new.tsx");
  "routes/calls_.record/$callId": typeof import("./app/routes/calls_.record/$callId.tsx");
  "routes/[.]well-known/oauth-authorization-server": typeof import("./app/routes/[.]well-known/oauth-authorization-server.ts");
  "routes/[.]well-known/oauth-protected-resource": typeof import("./app/routes/[.]well-known/oauth-protected-resource.ts");
  "routes/action/kit": typeof import("./app/routes/action/kit.tsx");
  "routes/action/mark-as-read": typeof import("./app/routes/action/mark-as-read.tsx");
  "routes/action/refresh-cache": typeof import("./app/routes/action/refresh-cache.tsx");
  "routes/action/set-theme": typeof import("./app/routes/action/set-theme.tsx");
  "routes/blog_/list": typeof import("./app/routes/blog_/list.tsx");
  "routes/blog_/rss[.]xml": typeof import("./app/routes/blog_/rss[.]xml.tsx");
  "routes/cache.admin": typeof import("./app/routes/cache.admin.tsx");
  "routes/me_.admin": typeof import("./app/routes/me_.admin.tsx");
  "routes/me_.passkeys": typeof import("./app/routes/me_.passkeys.tsx");
  "routes/me_.password": typeof import("./app/routes/me_.password.tsx");
  "routes/oauth.authorize": typeof import("./app/routes/oauth.authorize.tsx");
  "routes/resources/favorite": typeof import("./app/routes/resources/favorite.tsx");
  "routes/resources/heapsnapshot": typeof import("./app/routes/resources/heapsnapshot.ts");
  "routes/resources/lookout": typeof import("./app/routes/resources/lookout.ts");
  "routes/resources/promotification": typeof import("./app/routes/resources/promotification.tsx");
  "routes/resources/search": typeof import("./app/routes/resources/search.ts");
  "routes/search.admin": typeof import("./app/routes/search.admin.tsx");
  "routes/blog_/$slug": typeof import("./app/routes/blog_/$slug.tsx");
  "routes/s.$query": typeof import("./app/routes/s.$query.tsx");
  "routes/resources/cache.sqlite": typeof import("./app/routes/resources/cache.sqlite.ts");
  "routes/resources/calls/call-audio": typeof import("./app/routes/resources/calls/call-audio.ts");
  "routes/resources/calls/draft-episode-audio": typeof import("./app/routes/resources/calls/draft-episode-audio.ts");
  "routes/resources/calls/draft-response-audio": typeof import("./app/routes/resources/calls/draft-response-audio.ts");
  "routes/resources/calls/draft-status": typeof import("./app/routes/resources/calls/draft-status.ts");
  "routes/resources/calls/episode-audio-callback": typeof import("./app/routes/resources/calls/episode-audio-callback.ts");
  "routes/resources/calls/save": typeof import("./app/routes/resources/calls/save.tsx");
  "routes/resources/calls/text-to-speech": typeof import("./app/routes/resources/calls/text-to-speech.tsx");
  "routes/resources/webauthn/generate-authentication-options": typeof import("./app/routes/resources/webauthn/generate-authentication-options.ts");
  "routes/resources/webauthn/generate-registration-options": typeof import("./app/routes/resources/webauthn/generate-registration-options.ts");
  "routes/resources/webauthn/verify-authentication": typeof import("./app/routes/resources/webauthn/verify-authentication.ts");
  "routes/resources/webauthn/verify-registration": typeof import("./app/routes/resources/webauthn/verify-registration.ts");
  "routes/chats_/$season_.$episode": typeof import("./app/routes/chats_/$season_.$episode.tsx");
  "routes/resources/cache.lru.$cacheKey": typeof import("./app/routes/resources/cache.lru.$cacheKey.ts");
  "routes/resources/cache.sqlite_.$cacheKey": typeof import("./app/routes/resources/cache.sqlite_.$cacheKey.ts");
  "routes/chats_/$season.$episode_.$slug": typeof import("./app/routes/chats_/$season.$episode_.$slug.tsx");
};