
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `CallKentCallerEpisode` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.ts"
import type * as Prisma from "../internal/prismaNamespace.ts"

/**
 * Model CallKentCallerEpisode
 * 
 */
export type CallKentCallerEpisodeModel = runtime.Types.Result.DefaultSelection<Prisma.$CallKentCallerEpisodePayload>

export type AggregateCallKentCallerEpisode = {
  _count: CallKentCallerEpisodeCountAggregateOutputType | null
  _min: CallKentCallerEpisodeMinAggregateOutputType | null
  _max: CallKentCallerEpisodeMaxAggregateOutputType | null
}

export type CallKentCallerEpisodeMinAggregateOutputType = {
  id: string | null
  createdAt: Date | null
  updatedAt: Date | null
  userId: string | null
  callTitle: string | null
  callNotes: string | null
  isAnonymous: boolean | null
  transistorEpisodeId: string | null
}

export type CallKentCallerEpisodeMaxAggregateOutputType = {
  id: string | null
  createdAt: Date | null
  updatedAt: Date | null
  userId: string | null
  callTitle: string | null
  callNotes: string | null
  isAnonymous: boolean | null
  transistorEpisodeId: string | null
}

export type CallKentCallerEpisodeCountAggregateOutputType = {
  id: number
  createdAt: number
  updatedAt: number
  userId: number
  callTitle: number
  callNotes: number
  isAnonymous: number
  transistorEpisodeId: number
  _all: number
}


export type CallKentCallerEpisodeMinAggregateInputType = {
  id?: true
  createdAt?: true
  updatedAt?: true
  userId?: true
  callTitle?: true
  callNotes?: true
  isAnonymous?: true
  transistorEpisodeId?: true
}

export type CallKentCallerEpisodeMaxAggregateInputType = {
  id?: true
  createdAt?: true
  updatedAt?: true
  userId?: true
  callTitle?: true
  callNotes?: true
  isAnonymous?: true
  transistorEpisodeId?: true
}

export type CallKentCallerEpisodeCountAggregateInputType = {
  id?: true
  createdAt?: true
  updatedAt?: true
  userId?: true
  callTitle?: true
  callNotes?: true
  isAnonymous?: true
  transistorEpisodeId?: true
  _all?: true
}

export type CallKentCallerEpisodeAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which CallKentCallerEpisode to aggregate.
   */
  where?: Prisma.CallKentCallerEpisodeWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of CallKentCallerEpisodes to fetch.
   */
  orderBy?: Prisma.CallKentCallerEpisodeOrderByWithRelationInput | Prisma.CallKentCallerEpisodeOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.CallKentCallerEpisodeWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` CallKentCallerEpisodes from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` CallKentCallerEpisodes.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned CallKentCallerEpisodes
  **/
  _count?: true | CallKentCallerEpisodeCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: CallKentCallerEpisodeMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: CallKentCallerEpisodeMaxAggregateInputType
}

export type GetCallKentCallerEpisodeAggregateType<T extends CallKentCallerEpisodeAggregateArgs> = {
      [P in keyof T & keyof AggregateCallKentCallerEpisode]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateCallKentCallerEpisode[P]>
    : Prisma.GetScalarType<T[P], AggregateCallKentCallerEpisode[P]>
}




export type CallKentCallerEpisodeGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.CallKentCallerEpisodeWhereInput
  orderBy?: Prisma.CallKentCallerEpisodeOrderByWithAggregationInput | Prisma.CallKentCallerEpisodeOrderByWithAggregationInput[]
  by: Prisma.CallKentCallerEpisodeScalarFieldEnum[] | Prisma.CallKentCallerEpisodeScalarFieldEnum
  having?: Prisma.CallKentCallerEpisodeScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: CallKentCallerEpisodeCountAggregateInputType | true
  _min?: CallKentCallerEpisodeMinAggregateInputType
  _max?: CallKentCallerEpisodeMaxAggregateInputType
}

export type CallKentCallerEpisodeGroupByOutputType = {
  id: string
  createdAt: Date
  updatedAt: Date
  userId: string
  callTitle: string
  callNotes: string | null
  isAnonymous: boolean
  transistorEpisodeId: string
  _count: CallKentCallerEpisodeCountAggregateOutputType | null
  _min: CallKentCallerEpisodeMinAggregateOutputType | null
  _max: CallKentCallerEpisodeMaxAggregateOutputType | null
}

export type GetCallKentCallerEpisodeGroupByPayload<T extends CallKentCallerEpisodeGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<CallKentCallerEpisodeGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof CallKentCallerEpisodeGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], CallKentCallerEpisodeGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], CallKentCallerEpisodeGroupByOutputType[P]>
      }
    >
  >



export type CallKentCallerEpisodeWhereInput = {
  AND?: Prisma.CallKentCallerEpisodeWhereInput | Prisma.CallKentCallerEpisodeWhereInput[]
  OR?: Prisma.CallKentCallerEpisodeWhereInput[]
  NOT?: Prisma.CallKentCallerEpisodeWhereInput | Prisma.CallKentCallerEpisodeWhereInput[]
  id?: Prisma.StringFilter<"CallKentCallerEpisode"> | string
  createdAt?: Prisma.DateTimeFilter<"CallKentCallerEpisode"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"CallKentCallerEpisode"> | Date | string
  userId?: Prisma.StringFilter<"CallKentCallerEpisode"> | string
  callTitle?: Prisma.StringFilter<"CallKentCallerEpisode"> | string
  callNotes?: Prisma.StringNullableFilter<"CallKentCallerEpisode"> | string | null
  isAnonymous?: Prisma.BoolFilter<"CallKentCallerEpisode"> | boolean
  transistorEpisodeId?: Prisma.StringFilter<"CallKentCallerEpisode"> | string
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
}

export type CallKentCallerEpisodeOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  callTitle?: Prisma.SortOrder
  callNotes?: Prisma.SortOrderInput | Prisma.SortOrder
  isAnonymous?: Prisma.SortOrder
  transistorEpisodeId?: Prisma.SortOrder
  user?: Prisma.UserOrderByWithRelationInput
}

export type CallKentCallerEpisodeWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  transistorEpisodeId?: string
  AND?: Prisma.CallKentCallerEpisodeWhereInput | Prisma.CallKentCallerEpisodeWhereInput[]
  OR?: Prisma.CallKentCallerEpisodeWhereInput[]
  NOT?: Prisma.CallKentCallerEpisodeWhereInput | Prisma.CallKentCallerEpisodeWhereInput[]
  createdAt?: Prisma.DateTimeFilter<"CallKentCallerEpisode"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"CallKentCallerEpisode"> | Date | string
  userId?: Prisma.StringFilter<"CallKentCallerEpisode"> | string
  callTitle?: Prisma.StringFilter<"CallKentCallerEpisode"> | string
  callNotes?: Prisma.StringNullableFilter<"CallKentCallerEpisode"> | string | null
  isAnonymous?: Prisma.BoolFilter<"CallKentCallerEpisode"> | boolean
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
}, "id" | "transistorEpisodeId">

export type CallKentCallerEpisodeOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  callTitle?: Prisma.SortOrder
  callNotes?: Prisma.SortOrderInput | Prisma.SortOrder
  isAnonymous?: Prisma.SortOrder
  transistorEpisodeId?: Prisma.SortOrder
  _count?: Prisma.CallKentCallerEpisodeCountOrderByAggregateInput
  _max?: Prisma.CallKentCallerEpisodeMaxOrderByAggregateInput
  _min?: Prisma.CallKentCallerEpisodeMinOrderByAggregateInput
}

export type CallKentCallerEpisodeScalarWhereWithAggregatesInput = {
  AND?: Prisma.CallKentCallerEpisodeScalarWhereWithAggregatesInput | Prisma.CallKentCallerEpisodeScalarWhereWithAggregatesInput[]
  OR?: Prisma.CallKentCallerEpisodeScalarWhereWithAggregatesInput[]
  NOT?: Prisma.CallKentCallerEpisodeScalarWhereWithAggregatesInput | Prisma.CallKentCallerEpisodeScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"CallKentCallerEpisode"> | string
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"CallKentCallerEpisode"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"CallKentCallerEpisode"> | Date | string
  userId?: Prisma.StringWithAggregatesFilter<"CallKentCallerEpisode"> | string
  callTitle?: Prisma.StringWithAggregatesFilter<"CallKentCallerEpisode"> | string
  callNotes?: Prisma.StringNullableWithAggregatesFilter<"CallKentCallerEpisode"> | string | null
  isAnonymous?: Prisma.BoolWithAggregatesFilter<"CallKentCallerEpisode"> | boolean
  transistorEpisodeId?: Prisma.StringWithAggregatesFilter<"CallKentCallerEpisode"> | string
}

export type CallKentCallerEpisodeCreateInput = {
  id?: string
  createdAt?: Date | string
  updatedAt?: Date | string
  callTitle: string
  callNotes?: string | null
  isAnonymous?: boolean
  transistorEpisodeId: string
  user: Prisma.UserCreateNestedOneWithoutCallKentCallerEpisodesInput
}

export type CallKentCallerEpisodeUncheckedCreateInput = {
  id?: string
  createdAt?: Date | string
  updatedAt?: Date | string
  userId: string
  callTitle: string
  callNotes?: string | null
  isAnonymous?: boolean
  transistorEpisodeId: string
}

export type CallKentCallerEpisodeUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  callTitle?: Prisma.StringFieldUpdateOperationsInput | string
  callNotes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isAnonymous?: Prisma.BoolFieldUpdateOperationsInput | boolean
  transistorEpisodeId?: Prisma.StringFieldUpdateOperationsInput | string
  user?: Prisma.UserUpdateOneRequiredWithoutCallKentCallerEpisodesNestedInput
}

export type CallKentCallerEpisodeUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  callTitle?: Prisma.StringFieldUpdateOperationsInput | string
  callNotes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isAnonymous?: Prisma.BoolFieldUpdateOperationsInput | boolean
  transistorEpisodeId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type CallKentCallerEpisodeCreateManyInput = {
  id?: string
  createdAt?: Date | string
  updatedAt?: Date | string
  userId: string
  callTitle: string
  callNotes?: string | null
  isAnonymous?: boolean
  transistorEpisodeId: string
}

export type CallKentCallerEpisodeUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  callTitle?: Prisma.StringFieldUpdateOperationsInput | string
  callNotes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isAnonymous?: Prisma.BoolFieldUpdateOperationsInput | boolean
  transistorEpisodeId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type CallKentCallerEpisodeUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  callTitle?: Prisma.StringFieldUpdateOperationsInput | string
  callNotes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isAnonymous?: Prisma.BoolFieldUpdateOperationsInput | boolean
  transistorEpisodeId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type CallKentCallerEpisodeListRelationFilter = {
  every?: Prisma.CallKentCallerEpisodeWhereInput
  some?: Prisma.CallKentCallerEpisodeWhereInput
  none?: Prisma.CallKentCallerEpisodeWhereInput
}

export type CallKentCallerEpisodeOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type CallKentCallerEpisodeCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  callTitle?: Prisma.SortOrder
  callNotes?: Prisma.SortOrder
  isAnonymous?: Prisma.SortOrder
  transistorEpisodeId?: Prisma.SortOrder
}

export type CallKentCallerEpisodeMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  callTitle?: Prisma.SortOrder
  callNotes?: Prisma.SortOrder
  isAnonymous?: Prisma.SortOrder
  transistorEpisodeId?: Prisma.SortOrder
}

export type CallKentCallerEpisodeMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  callTitle?: Prisma.SortOrder
  callNotes?: Prisma.SortOrder
  isAnonymous?: Prisma.SortOrder
  transistorEpisodeId?: Prisma.SortOrder
}

export type CallKentCallerEpisodeCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.CallKentCallerEpisodeCreateWithoutUserInput, Prisma.CallKentCallerEpisodeUncheckedCreateWithoutUserInput> | Prisma.CallKentCallerEpisodeCreateWithoutUserInput[] | Prisma.CallKentCallerEpisodeUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.CallKentCallerEpisodeCreateOrConnectWithoutUserInput | Prisma.CallKentCallerEpisodeCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.CallKentCallerEpisodeCreateManyUserInputEnvelope
  connect?: Prisma.CallKentCallerEpisodeWhereUniqueInput | Prisma.CallKentCallerEpisodeWhereUniqueInput[]
}

export type CallKentCallerEpisodeUncheckedCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.CallKentCallerEpisodeCreateWithoutUserInput, Prisma.CallKentCallerEpisodeUncheckedCreateWithoutUserInput> | Prisma.CallKentCallerEpisodeCreateWithoutUserInput[] | Prisma.CallKentCallerEpisodeUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.CallKentCallerEpisodeCreateOrConnectWithoutUserInput | Prisma.CallKentCallerEpisodeCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.CallKentCallerEpisodeCreateManyUserInputEnvelope
  connect?: Prisma.CallKentCallerEpisodeWhereUniqueInput | Prisma.CallKentCallerEpisodeWhereUniqueInput[]
}

export type CallKentCallerEpisodeUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.CallKentCallerEpisodeCreateWithoutUserInput, Prisma.CallKentCallerEpisodeUncheckedCreateWithoutUserInput> | Prisma.CallKentCallerEpisodeCreateWithoutUserInput[] | Prisma.CallKentCallerEpisodeUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.CallKentCallerEpisodeCreateOrConnectWithoutUserInput | Prisma.CallKentCallerEpisodeCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.CallKentCallerEpisodeUpsertWithWhereUniqueWithoutUserInput | Prisma.CallKentCallerEpisodeUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.CallKentCallerEpisodeCreateManyUserInputEnvelope
  set?: Prisma.CallKentCallerEpisodeWhereUniqueInput | Prisma.CallKentCallerEpisodeWhereUniqueInput[]
  disconnect?: Prisma.CallKentCallerEpisodeWhereUniqueInput | Prisma.CallKentCallerEpisodeWhereUniqueInput[]
  delete?: Prisma.CallKentCallerEpisodeWhereUniqueInput | Prisma.CallKentCallerEpisodeWhereUniqueInput[]
  connect?: Prisma.CallKentCallerEpisodeWhereUniqueInput | Prisma.CallKentCallerEpisodeWhereUniqueInput[]
  update?: Prisma.CallKentCallerEpisodeUpdateWithWhereUniqueWithoutUserInput | Prisma.CallKentCallerEpisodeUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.CallKentCallerEpisodeUpdateManyWithWhereWithoutUserInput | Prisma.CallKentCallerEpisodeUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.CallKentCallerEpisodeScalarWhereInput | Prisma.CallKentCallerEpisodeScalarWhereInput[]
}

export type CallKentCallerEpisodeUncheckedUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.CallKentCallerEpisodeCreateWithoutUserInput, Prisma.CallKentCallerEpisodeUncheckedCreateWithoutUserInput> | Prisma.CallKentCallerEpisodeCreateWithoutUserInput[] | Prisma.CallKentCallerEpisodeUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.CallKentCallerEpisodeCreateOrConnectWithoutUserInput | Prisma.CallKentCallerEpisodeCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.CallKentCallerEpisodeUpsertWithWhereUniqueWithoutUserInput | Prisma.CallKentCallerEpisodeUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.CallKentCallerEpisodeCreateManyUserInputEnvelope
  set?: Prisma.CallKentCallerEpisodeWhereUniqueInput | Prisma.CallKentCallerEpisodeWhereUniqueInput[]
  disconnect?: Prisma.CallKentCallerEpisodeWhereUniqueInput | Prisma.CallKentCallerEpisodeWhereUniqueInput[]
  delete?: Prisma.CallKentCallerEpisodeWhereUniqueInput | Prisma.CallKentCallerEpisodeWhereUniqueInput[]
  connect?: Prisma.CallKentCallerEpisodeWhereUniqueInput | Prisma.CallKentCallerEpisodeWhereUniqueInput[]
  update?: Prisma.CallKentCallerEpisodeUpdateWithWhereUniqueWithoutUserInput | Prisma.CallKentCallerEpisodeUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.CallKentCallerEpisodeUpdateManyWithWhereWithoutUserInput | Prisma.CallKentCallerEpisodeUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.CallKentCallerEpisodeScalarWhereInput | Prisma.CallKentCallerEpisodeScalarWhereInput[]
}

export type CallKentCallerEpisodeCreateWithoutUserInput = {
  id?: string
  createdAt?: Date | string
  updatedAt?: Date | string
  callTitle: string
  callNotes?: string | null
  isAnonymous?: boolean
  transistorEpisodeId: string
}

export type CallKentCallerEpisodeUncheckedCreateWithoutUserInput = {
  id?: string
  createdAt?: Date | string
  updatedAt?: Date | string
  callTitle: string
  callNotes?: string | null
  isAnonymous?: boolean
  transistorEpisodeId: string
}

export type CallKentCallerEpisodeCreateOrConnectWithoutUserInput = {
  where: Prisma.CallKentCallerEpisodeWhereUniqueInput
  create: Prisma.XOR<Prisma.CallKentCallerEpisodeCreateWithoutUserInput, Prisma.CallKentCallerEpisodeUncheckedCreateWithoutUserInput>
}

export type CallKentCallerEpisodeCreateManyUserInputEnvelope = {
  data: Prisma.CallKentCallerEpisodeCreateManyUserInput | Prisma.CallKentCallerEpisodeCreateManyUserInput[]
}

export type CallKentCallerEpisodeUpsertWithWhereUniqueWithoutUserInput = {
  where: Prisma.CallKentCallerEpisodeWhereUniqueInput
  update: Prisma.XOR<Prisma.CallKentCallerEpisodeUpdateWithoutUserInput, Prisma.CallKentCallerEpisodeUncheckedUpdateWithoutUserInput>
  create: Prisma.XOR<Prisma.CallKentCallerEpisodeCreateWithoutUserInput, Prisma.CallKentCallerEpisodeUncheckedCreateWithoutUserInput>
}

export type CallKentCallerEpisodeUpdateWithWhereUniqueWithoutUserInput = {
  where: Prisma.CallKentCallerEpisodeWhereUniqueInput
  data: Prisma.XOR<Prisma.CallKentCallerEpisodeUpdateWithoutUserInput, Prisma.CallKentCallerEpisodeUncheckedUpdateWithoutUserInput>
}

export type CallKentCallerEpisodeUpdateManyWithWhereWithoutUserInput = {
  where: Prisma.CallKentCallerEpisodeScalarWhereInput
  data: Prisma.XOR<Prisma.CallKentCallerEpisodeUpdateManyMutationInput, Prisma.CallKentCallerEpisodeUncheckedUpdateManyWithoutUserInput>
}

export type CallKentCallerEpisodeScalarWhereInput = {
  AND?: Prisma.CallKentCallerEpisodeScalarWhereInput | Prisma.CallKentCallerEpisodeScalarWhereInput[]
  OR?: Prisma.CallKentCallerEpisodeScalarWhereInput[]
  NOT?: Prisma.CallKentCallerEpisodeScalarWhereInput | Prisma.CallKentCallerEpisodeScalarWhereInput[]
  id?: Prisma.StringFilter<"CallKentCallerEpisode"> | string
  createdAt?: Prisma.DateTimeFilter<"CallKentCallerEpisode"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"CallKentCallerEpisode"> | Date | string
  userId?: Prisma.StringFilter<"CallKentCallerEpisode"> | string
  callTitle?: Prisma.StringFilter<"CallKentCallerEpisode"> | string
  callNotes?: Prisma.StringNullableFilter<"CallKentCallerEpisode"> | string | null
  isAnonymous?: Prisma.BoolFilter<"CallKentCallerEpisode"> | boolean
  transistorEpisodeId?: Prisma.StringFilter<"CallKentCallerEpisode"> | string
}

export type CallKentCallerEpisodeCreateManyUserInput = {
  id?: string
  createdAt?: Date | string
  updatedAt?: Date | string
  callTitle: string
  callNotes?: string | null
  isAnonymous?: boolean
  transistorEpisodeId: string
}

export type CallKentCallerEpisodeUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  callTitle?: Prisma.StringFieldUpdateOperationsInput | string
  callNotes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isAnonymous?: Prisma.BoolFieldUpdateOperationsInput | boolean
  transistorEpisodeId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type CallKentCallerEpisodeUncheckedUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  callTitle?: Prisma.StringFieldUpdateOperationsInput | string
  callNotes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isAnonymous?: Prisma.BoolFieldUpdateOperationsInput | boolean
  transistorEpisodeId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type CallKentCallerEpisodeUncheckedUpdateManyWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  callTitle?: Prisma.StringFieldUpdateOperationsInput | string
  callNotes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isAnonymous?: Prisma.BoolFieldUpdateOperationsInput | boolean
  transistorEpisodeId?: Prisma.StringFieldUpdateOperationsInput | string
}



export type CallKentCallerEpisodeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  userId?: boolean
  callTitle?: boolean
  callNotes?: boolean
  isAnonymous?: boolean
  transistorEpisodeId?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["callKentCallerEpisode"]>

export type CallKentCallerEpisodeSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  userId?: boolean
  callTitle?: boolean
  callNotes?: boolean
  isAnonymous?: boolean
  transistorEpisodeId?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["callKentCallerEpisode"]>

export type CallKentCallerEpisodeSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  userId?: boolean
  callTitle?: boolean
  callNotes?: boolean
  isAnonymous?: boolean
  transistorEpisodeId?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["callKentCallerEpisode"]>

export type CallKentCallerEpisodeSelectScalar = {
  id?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  userId?: boolean
  callTitle?: boolean
  callNotes?: boolean
  isAnonymous?: boolean
  transistorEpisodeId?: boolean
}

export type CallKentCallerEpisodeOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "createdAt" | "updatedAt" | "userId" | "callTitle" | "callNotes" | "isAnonymous" | "transistorEpisodeId", ExtArgs["result"]["callKentCallerEpisode"]>
export type CallKentCallerEpisodeInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}
export type CallKentCallerEpisodeIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}
export type CallKentCallerEpisodeIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}

export type $CallKentCallerEpisodePayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "CallKentCallerEpisode"
  objects: {
    user: Prisma.$UserPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    createdAt: Date
    updatedAt: Date
    userId: string
    callTitle: string
    callNotes: string | null
    isAnonymous: boolean
    transistorEpisodeId: string
  }, ExtArgs["result"]["callKentCallerEpisode"]>
  composites: {}
}

export type CallKentCallerEpisodeGetPayload<S extends boolean | null | undefined | CallKentCallerEpisodeDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$CallKentCallerEpisodePayload, S>

export type CallKentCallerEpisodeCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<CallKentCallerEpisodeFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: CallKentCallerEpisodeCountAggregateInputType | true
  }

export interface CallKentCallerEpisodeDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['CallKentCallerEpisode'], meta: { name: 'CallKentCallerEpisode' } }
  /**
   * Find zero or one CallKentCallerEpisode that matches the filter.
   * @param {CallKentCallerEpisodeFindUniqueArgs} args - Arguments to find a CallKentCallerEpisode
   * @example
   * // Get one CallKentCallerEpisode
   * const callKentCallerEpisode = await prisma.callKentCallerEpisode.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends CallKentCallerEpisodeFindUniqueArgs>(args: Prisma.SelectSubset<T, CallKentCallerEpisodeFindUniqueArgs<ExtArgs>>): Prisma.Prisma__CallKentCallerEpisodeClient<runtime.Types.Result.GetResult<Prisma.$CallKentCallerEpisodePayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one CallKentCallerEpisode that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {CallKentCallerEpisodeFindUniqueOrThrowArgs} args - Arguments to find a CallKentCallerEpisode
   * @example
   * // Get one CallKentCallerEpisode
   * const callKentCallerEpisode = await prisma.callKentCallerEpisode.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends CallKentCallerEpisodeFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, CallKentCallerEpisodeFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__CallKentCallerEpisodeClient<runtime.Types.Result.GetResult<Prisma.$CallKentCallerEpisodePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first CallKentCallerEpisode that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CallKentCallerEpisodeFindFirstArgs} args - Arguments to find a CallKentCallerEpisode
   * @example
   * // Get one CallKentCallerEpisode
   * const callKentCallerEpisode = await prisma.callKentCallerEpisode.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends CallKentCallerEpisodeFindFirstArgs>(args?: Prisma.SelectSubset<T, CallKentCallerEpisodeFindFirstArgs<ExtArgs>>): Prisma.Prisma__CallKentCallerEpisodeClient<runtime.Types.Result.GetResult<Prisma.$CallKentCallerEpisodePayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first CallKentCallerEpisode that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CallKentCallerEpisodeFindFirstOrThrowArgs} args - Arguments to find a CallKentCallerEpisode
   * @example
   * // Get one CallKentCallerEpisode
   * const callKentCallerEpisode = await prisma.callKentCallerEpisode.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends CallKentCallerEpisodeFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, CallKentCallerEpisodeFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__CallKentCallerEpisodeClient<runtime.Types.Result.GetResult<Prisma.$CallKentCallerEpisodePayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more CallKentCallerEpisodes that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CallKentCallerEpisodeFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all CallKentCallerEpisodes
   * const callKentCallerEpisodes = await prisma.callKentCallerEpisode.findMany()
   * 
   * // Get first 10 CallKentCallerEpisodes
   * const callKentCallerEpisodes = await prisma.callKentCallerEpisode.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const callKentCallerEpisodeWithIdOnly = await prisma.callKentCallerEpisode.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends CallKentCallerEpisodeFindManyArgs>(args?: Prisma.SelectSubset<T, CallKentCallerEpisodeFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$CallKentCallerEpisodePayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a CallKentCallerEpisode.
   * @param {CallKentCallerEpisodeCreateArgs} args - Arguments to create a CallKentCallerEpisode.
   * @example
   * // Create one CallKentCallerEpisode
   * const CallKentCallerEpisode = await prisma.callKentCallerEpisode.create({
   *   data: {
   *     // ... data to create a CallKentCallerEpisode
   *   }
   * })
   * 
   */
  create<T extends CallKentCallerEpisodeCreateArgs>(args: Prisma.SelectSubset<T, CallKentCallerEpisodeCreateArgs<ExtArgs>>): Prisma.Prisma__CallKentCallerEpisodeClient<runtime.Types.Result.GetResult<Prisma.$CallKentCallerEpisodePayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many CallKentCallerEpisodes.
   * @param {CallKentCallerEpisodeCreateManyArgs} args - Arguments to create many CallKentCallerEpisodes.
   * @example
   * // Create many CallKentCallerEpisodes
   * const callKentCallerEpisode = await prisma.callKentCallerEpisode.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends CallKentCallerEpisodeCreateManyArgs>(args?: Prisma.SelectSubset<T, CallKentCallerEpisodeCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many CallKentCallerEpisodes and returns the data saved in the database.
   * @param {CallKentCallerEpisodeCreateManyAndReturnArgs} args - Arguments to create many CallKentCallerEpisodes.
   * @example
   * // Create many CallKentCallerEpisodes
   * const callKentCallerEpisode = await prisma.callKentCallerEpisode.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many CallKentCallerEpisodes and only return the `id`
   * const callKentCallerEpisodeWithIdOnly = await prisma.callKentCallerEpisode.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends CallKentCallerEpisodeCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, CallKentCallerEpisodeCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$CallKentCallerEpisodePayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a CallKentCallerEpisode.
   * @param {CallKentCallerEpisodeDeleteArgs} args - Arguments to delete one CallKentCallerEpisode.
   * @example
   * // Delete one CallKentCallerEpisode
   * const CallKentCallerEpisode = await prisma.callKentCallerEpisode.delete({
   *   where: {
   *     // ... filter to delete one CallKentCallerEpisode
   *   }
   * })
   * 
   */
  delete<T extends CallKentCallerEpisodeDeleteArgs>(args: Prisma.SelectSubset<T, CallKentCallerEpisodeDeleteArgs<ExtArgs>>): Prisma.Prisma__CallKentCallerEpisodeClient<runtime.Types.Result.GetResult<Prisma.$CallKentCallerEpisodePayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one CallKentCallerEpisode.
   * @param {CallKentCallerEpisodeUpdateArgs} args - Arguments to update one CallKentCallerEpisode.
   * @example
   * // Update one CallKentCallerEpisode
   * const callKentCallerEpisode = await prisma.callKentCallerEpisode.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends CallKentCallerEpisodeUpdateArgs>(args: Prisma.SelectSubset<T, CallKentCallerEpisodeUpdateArgs<ExtArgs>>): Prisma.Prisma__CallKentCallerEpisodeClient<runtime.Types.Result.GetResult<Prisma.$CallKentCallerEpisodePayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more CallKentCallerEpisodes.
   * @param {CallKentCallerEpisodeDeleteManyArgs} args - Arguments to filter CallKentCallerEpisodes to delete.
   * @example
   * // Delete a few CallKentCallerEpisodes
   * const { count } = await prisma.callKentCallerEpisode.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends CallKentCallerEpisodeDeleteManyArgs>(args?: Prisma.SelectSubset<T, CallKentCallerEpisodeDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more CallKentCallerEpisodes.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CallKentCallerEpisodeUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many CallKentCallerEpisodes
   * const callKentCallerEpisode = await prisma.callKentCallerEpisode.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends CallKentCallerEpisodeUpdateManyArgs>(args: Prisma.SelectSubset<T, CallKentCallerEpisodeUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more CallKentCallerEpisodes and returns the data updated in the database.
   * @param {CallKentCallerEpisodeUpdateManyAndReturnArgs} args - Arguments to update many CallKentCallerEpisodes.
   * @example
   * // Update many CallKentCallerEpisodes
   * const callKentCallerEpisode = await prisma.callKentCallerEpisode.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more CallKentCallerEpisodes and only return the `id`
   * const callKentCallerEpisodeWithIdOnly = await prisma.callKentCallerEpisode.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends CallKentCallerEpisodeUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, CallKentCallerEpisodeUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$CallKentCallerEpisodePayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one CallKentCallerEpisode.
   * @param {CallKentCallerEpisodeUpsertArgs} args - Arguments to update or create a CallKentCallerEpisode.
   * @example
   * // Update or create a CallKentCallerEpisode
   * const callKentCallerEpisode = await prisma.callKentCallerEpisode.upsert({
   *   create: {
   *     // ... data to create a CallKentCallerEpisode
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the CallKentCallerEpisode we want to update
   *   }
   * })
   */
  upsert<T extends CallKentCallerEpisodeUpsertArgs>(args: Prisma.SelectSubset<T, CallKentCallerEpisodeUpsertArgs<ExtArgs>>): Prisma.Prisma__CallKentCallerEpisodeClient<runtime.Types.Result.GetResult<Prisma.$CallKentCallerEpisodePayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of CallKentCallerEpisodes.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CallKentCallerEpisodeCountArgs} args - Arguments to filter CallKentCallerEpisodes to count.
   * @example
   * // Count the number of CallKentCallerEpisodes
   * const count = await prisma.callKentCallerEpisode.count({
   *   where: {
   *     // ... the filter for the CallKentCallerEpisodes we want to count
   *   }
   * })
  **/
  count<T extends CallKentCallerEpisodeCountArgs>(
    args?: Prisma.Subset<T, CallKentCallerEpisodeCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], CallKentCallerEpisodeCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a CallKentCallerEpisode.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CallKentCallerEpisodeAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends CallKentCallerEpisodeAggregateArgs>(args: Prisma.Subset<T, CallKentCallerEpisodeAggregateArgs>): Prisma.PrismaPromise<GetCallKentCallerEpisodeAggregateType<T>>

  /**
   * Group by CallKentCallerEpisode.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CallKentCallerEpisodeGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends CallKentCallerEpisodeGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: CallKentCallerEpisodeGroupByArgs['orderBy'] }
      : { orderBy?: CallKentCallerEpisodeGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, CallKentCallerEpisodeGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetCallKentCallerEpisodeGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the CallKentCallerEpisode model
 */
readonly fields: CallKentCallerEpisodeFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for CallKentCallerEpisode.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__CallKentCallerEpisodeClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  user<T extends Prisma.UserDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.UserDefaultArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the CallKentCallerEpisode model
 */
export interface CallKentCallerEpisodeFieldRefs {
  readonly id: Prisma.FieldRef<"CallKentCallerEpisode", 'String'>
  readonly createdAt: Prisma.FieldRef<"CallKentCallerEpisode", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"CallKentCallerEpisode", 'DateTime'>
  readonly userId: Prisma.FieldRef<"CallKentCallerEpisode", 'String'>
  readonly callTitle: Prisma.FieldRef<"CallKentCallerEpisode", 'String'>
  readonly callNotes: Prisma.FieldRef<"CallKentCallerEpisode", 'String'>
  readonly isAnonymous: Prisma.FieldRef<"CallKentCallerEpisode", 'Boolean'>
  readonly transistorEpisodeId: Prisma.FieldRef<"CallKentCallerEpisode", 'String'>
}
    

// Custom InputTypes
/**
 * CallKentCallerEpisode findUnique
 */
export type CallKentCallerEpisodeFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CallKentCallerEpisode
   */
  select?: Prisma.CallKentCallerEpisodeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CallKentCallerEpisode
   */
  omit?: Prisma.CallKentCallerEpisodeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CallKentCallerEpisodeInclude<ExtArgs> | null
  /**
   * Filter, which CallKentCallerEpisode to fetch.
   */
  where: Prisma.CallKentCallerEpisodeWhereUniqueInput
}

/**
 * CallKentCallerEpisode findUniqueOrThrow
 */
export type CallKentCallerEpisodeFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CallKentCallerEpisode
   */
  select?: Prisma.CallKentCallerEpisodeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CallKentCallerEpisode
   */
  omit?: Prisma.CallKentCallerEpisodeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CallKentCallerEpisodeInclude<ExtArgs> | null
  /**
   * Filter, which CallKentCallerEpisode to fetch.
   */
  where: Prisma.CallKentCallerEpisodeWhereUniqueInput
}

/**
 * CallKentCallerEpisode findFirst
 */
export type CallKentCallerEpisodeFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CallKentCallerEpisode
   */
  select?: Prisma.CallKentCallerEpisodeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CallKentCallerEpisode
   */
  omit?: Prisma.CallKentCallerEpisodeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CallKentCallerEpisodeInclude<ExtArgs> | null
  /**
   * Filter, which CallKentCallerEpisode to fetch.
   */
  where?: Prisma.CallKentCallerEpisodeWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of CallKentCallerEpisodes to fetch.
   */
  orderBy?: Prisma.CallKentCallerEpisodeOrderByWithRelationInput | Prisma.CallKentCallerEpisodeOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for CallKentCallerEpisodes.
   */
  cursor?: Prisma.CallKentCallerEpisodeWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` CallKentCallerEpisodes from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` CallKentCallerEpisodes.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of CallKentCallerEpisodes.
   */
  distinct?: Prisma.CallKentCallerEpisodeScalarFieldEnum | Prisma.CallKentCallerEpisodeScalarFieldEnum[]
}

/**
 * CallKentCallerEpisode findFirstOrThrow
 */
export type CallKentCallerEpisodeFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CallKentCallerEpisode
   */
  select?: Prisma.CallKentCallerEpisodeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CallKentCallerEpisode
   */
  omit?: Prisma.CallKentCallerEpisodeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CallKentCallerEpisodeInclude<ExtArgs> | null
  /**
   * Filter, which CallKentCallerEpisode to fetch.
   */
  where?: Prisma.CallKentCallerEpisodeWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of CallKentCallerEpisodes to fetch.
   */
  orderBy?: Prisma.CallKentCallerEpisodeOrderByWithRelationInput | Prisma.CallKentCallerEpisodeOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for CallKentCallerEpisodes.
   */
  cursor?: Prisma.CallKentCallerEpisodeWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` CallKentCallerEpisodes from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` CallKentCallerEpisodes.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of CallKentCallerEpisodes.
   */
  distinct?: Prisma.CallKentCallerEpisodeScalarFieldEnum | Prisma.CallKentCallerEpisodeScalarFieldEnum[]
}

/**
 * CallKentCallerEpisode findMany
 */
export type CallKentCallerEpisodeFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CallKentCallerEpisode
   */
  select?: Prisma.CallKentCallerEpisodeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CallKentCallerEpisode
   */
  omit?: Prisma.CallKentCallerEpisodeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CallKentCallerEpisodeInclude<ExtArgs> | null
  /**
   * Filter, which CallKentCallerEpisodes to fetch.
   */
  where?: Prisma.CallKentCallerEpisodeWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of CallKentCallerEpisodes to fetch.
   */
  orderBy?: Prisma.CallKentCallerEpisodeOrderByWithRelationInput | Prisma.CallKentCallerEpisodeOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing CallKentCallerEpisodes.
   */
  cursor?: Prisma.CallKentCallerEpisodeWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` CallKentCallerEpisodes from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` CallKentCallerEpisodes.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of CallKentCallerEpisodes.
   */
  distinct?: Prisma.CallKentCallerEpisodeScalarFieldEnum | Prisma.CallKentCallerEpisodeScalarFieldEnum[]
}

/**
 * CallKentCallerEpisode create
 */
export type CallKentCallerEpisodeCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CallKentCallerEpisode
   */
  select?: Prisma.CallKentCallerEpisodeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CallKentCallerEpisode
   */
  omit?: Prisma.CallKentCallerEpisodeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CallKentCallerEpisodeInclude<ExtArgs> | null
  /**
   * The data needed to create a CallKentCallerEpisode.
   */
  data: Prisma.XOR<Prisma.CallKentCallerEpisodeCreateInput, Prisma.CallKentCallerEpisodeUncheckedCreateInput>
}

/**
 * CallKentCallerEpisode createMany
 */
export type CallKentCallerEpisodeCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many CallKentCallerEpisodes.
   */
  data: Prisma.CallKentCallerEpisodeCreateManyInput | Prisma.CallKentCallerEpisodeCreateManyInput[]
}

/**
 * CallKentCallerEpisode createManyAndReturn
 */
export type CallKentCallerEpisodeCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CallKentCallerEpisode
   */
  select?: Prisma.CallKentCallerEpisodeSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the CallKentCallerEpisode
   */
  omit?: Prisma.CallKentCallerEpisodeOmit<ExtArgs> | null
  /**
   * The data used to create many CallKentCallerEpisodes.
   */
  data: Prisma.CallKentCallerEpisodeCreateManyInput | Prisma.CallKentCallerEpisodeCreateManyInput[]
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CallKentCallerEpisodeIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * CallKentCallerEpisode update
 */
export type CallKentCallerEpisodeUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CallKentCallerEpisode
   */
  select?: Prisma.CallKentCallerEpisodeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CallKentCallerEpisode
   */
  omit?: Prisma.CallKentCallerEpisodeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CallKentCallerEpisodeInclude<ExtArgs> | null
  /**
   * The data needed to update a CallKentCallerEpisode.
   */
  data: Prisma.XOR<Prisma.CallKentCallerEpisodeUpdateInput, Prisma.CallKentCallerEpisodeUncheckedUpdateInput>
  /**
   * Choose, which CallKentCallerEpisode to update.
   */
  where: Prisma.CallKentCallerEpisodeWhereUniqueInput
}

/**
 * CallKentCallerEpisode updateMany
 */
export type CallKentCallerEpisodeUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update CallKentCallerEpisodes.
   */
  data: Prisma.XOR<Prisma.CallKentCallerEpisodeUpdateManyMutationInput, Prisma.CallKentCallerEpisodeUncheckedUpdateManyInput>
  /**
   * Filter which CallKentCallerEpisodes to update
   */
  where?: Prisma.CallKentCallerEpisodeWhereInput
  /**
   * Limit how many CallKentCallerEpisodes to update.
   */
  limit?: number
}

/**
 * CallKentCallerEpisode updateManyAndReturn
 */
export type CallKentCallerEpisodeUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CallKentCallerEpisode
   */
  select?: Prisma.CallKentCallerEpisodeSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the CallKentCallerEpisode
   */
  omit?: Prisma.CallKentCallerEpisodeOmit<ExtArgs> | null
  /**
   * The data used to update CallKentCallerEpisodes.
   */
  data: Prisma.XOR<Prisma.CallKentCallerEpisodeUpdateManyMutationInput, Prisma.CallKentCallerEpisodeUncheckedUpdateManyInput>
  /**
   * Filter which CallKentCallerEpisodes to update
   */
  where?: Prisma.CallKentCallerEpisodeWhereInput
  /**
   * Limit how many CallKentCallerEpisodes to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CallKentCallerEpisodeIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * CallKentCallerEpisode upsert
 */
export type CallKentCallerEpisodeUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CallKentCallerEpisode
   */
  select?: Prisma.CallKentCallerEpisodeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CallKentCallerEpisode
   */
  omit?: Prisma.CallKentCallerEpisodeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CallKentCallerEpisodeInclude<ExtArgs> | null
  /**
   * The filter to search for the CallKentCallerEpisode to update in case it exists.
   */
  where: Prisma.CallKentCallerEpisodeWhereUniqueInput
  /**
   * In case the CallKentCallerEpisode found by the `where` argument doesn't exist, create a new CallKentCallerEpisode with this data.
   */
  create: Prisma.XOR<Prisma.CallKentCallerEpisodeCreateInput, Prisma.CallKentCallerEpisodeUncheckedCreateInput>
  /**
   * In case the CallKentCallerEpisode was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.CallKentCallerEpisodeUpdateInput, Prisma.CallKentCallerEpisodeUncheckedUpdateInput>
}

/**
 * CallKentCallerEpisode delete
 */
export type CallKentCallerEpisodeDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CallKentCallerEpisode
   */
  select?: Prisma.CallKentCallerEpisodeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CallKentCallerEpisode
   */
  omit?: Prisma.CallKentCallerEpisodeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CallKentCallerEpisodeInclude<ExtArgs> | null
  /**
   * Filter which CallKentCallerEpisode to delete.
   */
  where: Prisma.CallKentCallerEpisodeWhereUniqueInput
}

/**
 * CallKentCallerEpisode deleteMany
 */
export type CallKentCallerEpisodeDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which CallKentCallerEpisodes to delete
   */
  where?: Prisma.CallKentCallerEpisodeWhereInput
  /**
   * Limit how many CallKentCallerEpisodes to delete.
   */
  limit?: number
}

/**
 * CallKentCallerEpisode without action
 */
export type CallKentCallerEpisodeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CallKentCallerEpisode
   */
  select?: Prisma.CallKentCallerEpisodeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CallKentCallerEpisode
   */
  omit?: Prisma.CallKentCallerEpisodeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CallKentCallerEpisodeInclude<ExtArgs> | null
}
