
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Call` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.ts"
import type * as Prisma from "../internal/prismaNamespace.ts"

/**
 * Model Call
 * 
 */
export type CallModel = runtime.Types.Result.DefaultSelection<Prisma.$CallPayload>

export type AggregateCall = {
  _count: CallCountAggregateOutputType | null
  _avg: CallAvgAggregateOutputType | null
  _sum: CallSumAggregateOutputType | null
  _min: CallMinAggregateOutputType | null
  _max: CallMaxAggregateOutputType | null
}

export type CallAvgAggregateOutputType = {
  audioSize: number | null
}

export type CallSumAggregateOutputType = {
  audioSize: number | null
}

export type CallMinAggregateOutputType = {
  id: string | null
  createdAt: Date | null
  updatedAt: Date | null
  title: string | null
  notes: string | null
  isAnonymous: boolean | null
  callerTranscript: string | null
  callerTranscriptStatus: $Enums.CallTranscriptStatus | null
  callerTranscriptErrorMessage: string | null
  userId: string | null
  audioKey: string | null
  audioContentType: string | null
  audioSize: number | null
}

export type CallMaxAggregateOutputType = {
  id: string | null
  createdAt: Date | null
  updatedAt: Date | null
  title: string | null
  notes: string | null
  isAnonymous: boolean | null
  callerTranscript: string | null
  callerTranscriptStatus: $Enums.CallTranscriptStatus | null
  callerTranscriptErrorMessage: string | null
  userId: string | null
  audioKey: string | null
  audioContentType: string | null
  audioSize: number | null
}

export type CallCountAggregateOutputType = {
  id: number
  createdAt: number
  updatedAt: number
  title: number
  notes: number
  isAnonymous: number
  callerTranscript: number
  callerTranscriptStatus: number
  callerTranscriptErrorMessage: number
  userId: number
  audioKey: number
  audioContentType: number
  audioSize: number
  _all: number
}


export type CallAvgAggregateInputType = {
  audioSize?: true
}

export type CallSumAggregateInputType = {
  audioSize?: true
}

export type CallMinAggregateInputType = {
  id?: true
  createdAt?: true
  updatedAt?: true
  title?: true
  notes?: true
  isAnonymous?: true
  callerTranscript?: true
  callerTranscriptStatus?: true
  callerTranscriptErrorMessage?: true
  userId?: true
  audioKey?: true
  audioContentType?: true
  audioSize?: true
}

export type CallMaxAggregateInputType = {
  id?: true
  createdAt?: true
  updatedAt?: true
  title?: true
  notes?: true
  isAnonymous?: true
  callerTranscript?: true
  callerTranscriptStatus?: true
  callerTranscriptErrorMessage?: true
  userId?: true
  audioKey?: true
  audioContentType?: true
  audioSize?: true
}

export type CallCountAggregateInputType = {
  id?: true
  createdAt?: true
  updatedAt?: true
  title?: true
  notes?: true
  isAnonymous?: true
  callerTranscript?: true
  callerTranscriptStatus?: true
  callerTranscriptErrorMessage?: true
  userId?: true
  audioKey?: true
  audioContentType?: true
  audioSize?: true
  _all?: true
}

export type CallAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Call to aggregate.
   */
  where?: Prisma.CallWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Calls to fetch.
   */
  orderBy?: Prisma.CallOrderByWithRelationInput | Prisma.CallOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.CallWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Calls from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Calls.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Calls
  **/
  _count?: true | CallCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: CallAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: CallSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: CallMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: CallMaxAggregateInputType
}

export type GetCallAggregateType<T extends CallAggregateArgs> = {
      [P in keyof T & keyof AggregateCall]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateCall[P]>
    : Prisma.GetScalarType<T[P], AggregateCall[P]>
}




export type CallGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.CallWhereInput
  orderBy?: Prisma.CallOrderByWithAggregationInput | Prisma.CallOrderByWithAggregationInput[]
  by: Prisma.CallScalarFieldEnum[] | Prisma.CallScalarFieldEnum
  having?: Prisma.CallScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: CallCountAggregateInputType | true
  _avg?: CallAvgAggregateInputType
  _sum?: CallSumAggregateInputType
  _min?: CallMinAggregateInputType
  _max?: CallMaxAggregateInputType
}

export type CallGroupByOutputType = {
  id: string
  createdAt: Date
  updatedAt: Date
  title: string
  notes: string | null
  isAnonymous: boolean
  callerTranscript: string | null
  callerTranscriptStatus: $Enums.CallTranscriptStatus
  callerTranscriptErrorMessage: string | null
  userId: string
  audioKey: string | null
  audioContentType: string | null
  audioSize: number | null
  _count: CallCountAggregateOutputType | null
  _avg: CallAvgAggregateOutputType | null
  _sum: CallSumAggregateOutputType | null
  _min: CallMinAggregateOutputType | null
  _max: CallMaxAggregateOutputType | null
}

export type GetCallGroupByPayload<T extends CallGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<CallGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof CallGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], CallGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], CallGroupByOutputType[P]>
      }
    >
  >



export type CallWhereInput = {
  AND?: Prisma.CallWhereInput | Prisma.CallWhereInput[]
  OR?: Prisma.CallWhereInput[]
  NOT?: Prisma.CallWhereInput | Prisma.CallWhereInput[]
  id?: Prisma.StringFilter<"Call"> | string
  createdAt?: Prisma.DateTimeFilter<"Call"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Call"> | Date | string
  title?: Prisma.StringFilter<"Call"> | string
  notes?: Prisma.StringNullableFilter<"Call"> | string | null
  isAnonymous?: Prisma.BoolFilter<"Call"> | boolean
  callerTranscript?: Prisma.StringNullableFilter<"Call"> | string | null
  callerTranscriptStatus?: Prisma.EnumCallTranscriptStatusFilter<"Call"> | $Enums.CallTranscriptStatus
  callerTranscriptErrorMessage?: Prisma.StringNullableFilter<"Call"> | string | null
  userId?: Prisma.StringFilter<"Call"> | string
  audioKey?: Prisma.StringNullableFilter<"Call"> | string | null
  audioContentType?: Prisma.StringNullableFilter<"Call"> | string | null
  audioSize?: Prisma.IntNullableFilter<"Call"> | number | null
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
  episodeDraft?: Prisma.XOR<Prisma.CallKentEpisodeDraftNullableScalarRelationFilter, Prisma.CallKentEpisodeDraftWhereInput> | null
}

export type CallOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  title?: Prisma.SortOrder
  notes?: Prisma.SortOrderInput | Prisma.SortOrder
  isAnonymous?: Prisma.SortOrder
  callerTranscript?: Prisma.SortOrderInput | Prisma.SortOrder
  callerTranscriptStatus?: Prisma.SortOrder
  callerTranscriptErrorMessage?: Prisma.SortOrderInput | Prisma.SortOrder
  userId?: Prisma.SortOrder
  audioKey?: Prisma.SortOrderInput | Prisma.SortOrder
  audioContentType?: Prisma.SortOrderInput | Prisma.SortOrder
  audioSize?: Prisma.SortOrderInput | Prisma.SortOrder
  user?: Prisma.UserOrderByWithRelationInput
  episodeDraft?: Prisma.CallKentEpisodeDraftOrderByWithRelationInput
}

export type CallWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.CallWhereInput | Prisma.CallWhereInput[]
  OR?: Prisma.CallWhereInput[]
  NOT?: Prisma.CallWhereInput | Prisma.CallWhereInput[]
  createdAt?: Prisma.DateTimeFilter<"Call"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Call"> | Date | string
  title?: Prisma.StringFilter<"Call"> | string
  notes?: Prisma.StringNullableFilter<"Call"> | string | null
  isAnonymous?: Prisma.BoolFilter<"Call"> | boolean
  callerTranscript?: Prisma.StringNullableFilter<"Call"> | string | null
  callerTranscriptStatus?: Prisma.EnumCallTranscriptStatusFilter<"Call"> | $Enums.CallTranscriptStatus
  callerTranscriptErrorMessage?: Prisma.StringNullableFilter<"Call"> | string | null
  userId?: Prisma.StringFilter<"Call"> | string
  audioKey?: Prisma.StringNullableFilter<"Call"> | string | null
  audioContentType?: Prisma.StringNullableFilter<"Call"> | string | null
  audioSize?: Prisma.IntNullableFilter<"Call"> | number | null
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
  episodeDraft?: Prisma.XOR<Prisma.CallKentEpisodeDraftNullableScalarRelationFilter, Prisma.CallKentEpisodeDraftWhereInput> | null
}, "id">

export type CallOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  title?: Prisma.SortOrder
  notes?: Prisma.SortOrderInput | Prisma.SortOrder
  isAnonymous?: Prisma.SortOrder
  callerTranscript?: Prisma.SortOrderInput | Prisma.SortOrder
  callerTranscriptStatus?: Prisma.SortOrder
  callerTranscriptErrorMessage?: Prisma.SortOrderInput | Prisma.SortOrder
  userId?: Prisma.SortOrder
  audioKey?: Prisma.SortOrderInput | Prisma.SortOrder
  audioContentType?: Prisma.SortOrderInput | Prisma.SortOrder
  audioSize?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.CallCountOrderByAggregateInput
  _avg?: Prisma.CallAvgOrderByAggregateInput
  _max?: Prisma.CallMaxOrderByAggregateInput
  _min?: Prisma.CallMinOrderByAggregateInput
  _sum?: Prisma.CallSumOrderByAggregateInput
}

export type CallScalarWhereWithAggregatesInput = {
  AND?: Prisma.CallScalarWhereWithAggregatesInput | Prisma.CallScalarWhereWithAggregatesInput[]
  OR?: Prisma.CallScalarWhereWithAggregatesInput[]
  NOT?: Prisma.CallScalarWhereWithAggregatesInput | Prisma.CallScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"Call"> | string
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"Call"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"Call"> | Date | string
  title?: Prisma.StringWithAggregatesFilter<"Call"> | string
  notes?: Prisma.StringNullableWithAggregatesFilter<"Call"> | string | null
  isAnonymous?: Prisma.BoolWithAggregatesFilter<"Call"> | boolean
  callerTranscript?: Prisma.StringNullableWithAggregatesFilter<"Call"> | string | null
  callerTranscriptStatus?: Prisma.EnumCallTranscriptStatusWithAggregatesFilter<"Call"> | $Enums.CallTranscriptStatus
  callerTranscriptErrorMessage?: Prisma.StringNullableWithAggregatesFilter<"Call"> | string | null
  userId?: Prisma.StringWithAggregatesFilter<"Call"> | string
  audioKey?: Prisma.StringNullableWithAggregatesFilter<"Call"> | string | null
  audioContentType?: Prisma.StringNullableWithAggregatesFilter<"Call"> | string | null
  audioSize?: Prisma.IntNullableWithAggregatesFilter<"Call"> | number | null
}

export type CallCreateInput = {
  id?: string
  createdAt?: Date | string
  updatedAt?: Date | string
  title: string
  notes?: string | null
  isAnonymous?: boolean
  callerTranscript?: string | null
  callerTranscriptStatus?: $Enums.CallTranscriptStatus
  callerTranscriptErrorMessage?: string | null
  audioKey?: string | null
  audioContentType?: string | null
  audioSize?: number | null
  user: Prisma.UserCreateNestedOneWithoutCallsInput
  episodeDraft?: Prisma.CallKentEpisodeDraftCreateNestedOneWithoutCallInput
}

export type CallUncheckedCreateInput = {
  id?: string
  createdAt?: Date | string
  updatedAt?: Date | string
  title: string
  notes?: string | null
  isAnonymous?: boolean
  callerTranscript?: string | null
  callerTranscriptStatus?: $Enums.CallTranscriptStatus
  callerTranscriptErrorMessage?: string | null
  userId: string
  audioKey?: string | null
  audioContentType?: string | null
  audioSize?: number | null
  episodeDraft?: Prisma.CallKentEpisodeDraftUncheckedCreateNestedOneWithoutCallInput
}

export type CallUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isAnonymous?: Prisma.BoolFieldUpdateOperationsInput | boolean
  callerTranscript?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  callerTranscriptStatus?: Prisma.EnumCallTranscriptStatusFieldUpdateOperationsInput | $Enums.CallTranscriptStatus
  callerTranscriptErrorMessage?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  audioKey?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  audioContentType?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  audioSize?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  user?: Prisma.UserUpdateOneRequiredWithoutCallsNestedInput
  episodeDraft?: Prisma.CallKentEpisodeDraftUpdateOneWithoutCallNestedInput
}

export type CallUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isAnonymous?: Prisma.BoolFieldUpdateOperationsInput | boolean
  callerTranscript?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  callerTranscriptStatus?: Prisma.EnumCallTranscriptStatusFieldUpdateOperationsInput | $Enums.CallTranscriptStatus
  callerTranscriptErrorMessage?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  audioKey?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  audioContentType?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  audioSize?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  episodeDraft?: Prisma.CallKentEpisodeDraftUncheckedUpdateOneWithoutCallNestedInput
}

export type CallCreateManyInput = {
  id?: string
  createdAt?: Date | string
  updatedAt?: Date | string
  title: string
  notes?: string | null
  isAnonymous?: boolean
  callerTranscript?: string | null
  callerTranscriptStatus?: $Enums.CallTranscriptStatus
  callerTranscriptErrorMessage?: string | null
  userId: string
  audioKey?: string | null
  audioContentType?: string | null
  audioSize?: number | null
}

export type CallUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isAnonymous?: Prisma.BoolFieldUpdateOperationsInput | boolean
  callerTranscript?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  callerTranscriptStatus?: Prisma.EnumCallTranscriptStatusFieldUpdateOperationsInput | $Enums.CallTranscriptStatus
  callerTranscriptErrorMessage?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  audioKey?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  audioContentType?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  audioSize?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
}

export type CallUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isAnonymous?: Prisma.BoolFieldUpdateOperationsInput | boolean
  callerTranscript?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  callerTranscriptStatus?: Prisma.EnumCallTranscriptStatusFieldUpdateOperationsInput | $Enums.CallTranscriptStatus
  callerTranscriptErrorMessage?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  audioKey?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  audioContentType?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  audioSize?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
}

export type CallListRelationFilter = {
  every?: Prisma.CallWhereInput
  some?: Prisma.CallWhereInput
  none?: Prisma.CallWhereInput
}

export type CallOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type CallCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  title?: Prisma.SortOrder
  notes?: Prisma.SortOrder
  isAnonymous?: Prisma.SortOrder
  callerTranscript?: Prisma.SortOrder
  callerTranscriptStatus?: Prisma.SortOrder
  callerTranscriptErrorMessage?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  audioKey?: Prisma.SortOrder
  audioContentType?: Prisma.SortOrder
  audioSize?: Prisma.SortOrder
}

export type CallAvgOrderByAggregateInput = {
  audioSize?: Prisma.SortOrder
}

export type CallMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  title?: Prisma.SortOrder
  notes?: Prisma.SortOrder
  isAnonymous?: Prisma.SortOrder
  callerTranscript?: Prisma.SortOrder
  callerTranscriptStatus?: Prisma.SortOrder
  callerTranscriptErrorMessage?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  audioKey?: Prisma.SortOrder
  audioContentType?: Prisma.SortOrder
  audioSize?: Prisma.SortOrder
}

export type CallMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  title?: Prisma.SortOrder
  notes?: Prisma.SortOrder
  isAnonymous?: Prisma.SortOrder
  callerTranscript?: Prisma.SortOrder
  callerTranscriptStatus?: Prisma.SortOrder
  callerTranscriptErrorMessage?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  audioKey?: Prisma.SortOrder
  audioContentType?: Prisma.SortOrder
  audioSize?: Prisma.SortOrder
}

export type CallSumOrderByAggregateInput = {
  audioSize?: Prisma.SortOrder
}

export type CallScalarRelationFilter = {
  is?: Prisma.CallWhereInput
  isNot?: Prisma.CallWhereInput
}

export type CallCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.CallCreateWithoutUserInput, Prisma.CallUncheckedCreateWithoutUserInput> | Prisma.CallCreateWithoutUserInput[] | Prisma.CallUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.CallCreateOrConnectWithoutUserInput | Prisma.CallCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.CallCreateManyUserInputEnvelope
  connect?: Prisma.CallWhereUniqueInput | Prisma.CallWhereUniqueInput[]
}

export type CallUncheckedCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.CallCreateWithoutUserInput, Prisma.CallUncheckedCreateWithoutUserInput> | Prisma.CallCreateWithoutUserInput[] | Prisma.CallUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.CallCreateOrConnectWithoutUserInput | Prisma.CallCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.CallCreateManyUserInputEnvelope
  connect?: Prisma.CallWhereUniqueInput | Prisma.CallWhereUniqueInput[]
}

export type CallUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.CallCreateWithoutUserInput, Prisma.CallUncheckedCreateWithoutUserInput> | Prisma.CallCreateWithoutUserInput[] | Prisma.CallUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.CallCreateOrConnectWithoutUserInput | Prisma.CallCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.CallUpsertWithWhereUniqueWithoutUserInput | Prisma.CallUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.CallCreateManyUserInputEnvelope
  set?: Prisma.CallWhereUniqueInput | Prisma.CallWhereUniqueInput[]
  disconnect?: Prisma.CallWhereUniqueInput | Prisma.CallWhereUniqueInput[]
  delete?: Prisma.CallWhereUniqueInput | Prisma.CallWhereUniqueInput[]
  connect?: Prisma.CallWhereUniqueInput | Prisma.CallWhereUniqueInput[]
  update?: Prisma.CallUpdateWithWhereUniqueWithoutUserInput | Prisma.CallUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.CallUpdateManyWithWhereWithoutUserInput | Prisma.CallUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.CallScalarWhereInput | Prisma.CallScalarWhereInput[]
}

export type CallUncheckedUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.CallCreateWithoutUserInput, Prisma.CallUncheckedCreateWithoutUserInput> | Prisma.CallCreateWithoutUserInput[] | Prisma.CallUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.CallCreateOrConnectWithoutUserInput | Prisma.CallCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.CallUpsertWithWhereUniqueWithoutUserInput | Prisma.CallUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.CallCreateManyUserInputEnvelope
  set?: Prisma.CallWhereUniqueInput | Prisma.CallWhereUniqueInput[]
  disconnect?: Prisma.CallWhereUniqueInput | Prisma.CallWhereUniqueInput[]
  delete?: Prisma.CallWhereUniqueInput | Prisma.CallWhereUniqueInput[]
  connect?: Prisma.CallWhereUniqueInput | Prisma.CallWhereUniqueInput[]
  update?: Prisma.CallUpdateWithWhereUniqueWithoutUserInput | Prisma.CallUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.CallUpdateManyWithWhereWithoutUserInput | Prisma.CallUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.CallScalarWhereInput | Prisma.CallScalarWhereInput[]
}

export type BoolFieldUpdateOperationsInput = {
  set?: boolean
}

export type EnumCallTranscriptStatusFieldUpdateOperationsInput = {
  set?: $Enums.CallTranscriptStatus
}

export type NullableIntFieldUpdateOperationsInput = {
  set?: number | null
  increment?: number
  decrement?: number
  multiply?: number
  divide?: number
}

export type CallCreateNestedOneWithoutEpisodeDraftInput = {
  create?: Prisma.XOR<Prisma.CallCreateWithoutEpisodeDraftInput, Prisma.CallUncheckedCreateWithoutEpisodeDraftInput>
  connectOrCreate?: Prisma.CallCreateOrConnectWithoutEpisodeDraftInput
  connect?: Prisma.CallWhereUniqueInput
}

export type CallUpdateOneRequiredWithoutEpisodeDraftNestedInput = {
  create?: Prisma.XOR<Prisma.CallCreateWithoutEpisodeDraftInput, Prisma.CallUncheckedCreateWithoutEpisodeDraftInput>
  connectOrCreate?: Prisma.CallCreateOrConnectWithoutEpisodeDraftInput
  upsert?: Prisma.CallUpsertWithoutEpisodeDraftInput
  connect?: Prisma.CallWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.CallUpdateToOneWithWhereWithoutEpisodeDraftInput, Prisma.CallUpdateWithoutEpisodeDraftInput>, Prisma.CallUncheckedUpdateWithoutEpisodeDraftInput>
}

export type CallCreateWithoutUserInput = {
  id?: string
  createdAt?: Date | string
  updatedAt?: Date | string
  title: string
  notes?: string | null
  isAnonymous?: boolean
  callerTranscript?: string | null
  callerTranscriptStatus?: $Enums.CallTranscriptStatus
  callerTranscriptErrorMessage?: string | null
  audioKey?: string | null
  audioContentType?: string | null
  audioSize?: number | null
  episodeDraft?: Prisma.CallKentEpisodeDraftCreateNestedOneWithoutCallInput
}

export type CallUncheckedCreateWithoutUserInput = {
  id?: string
  createdAt?: Date | string
  updatedAt?: Date | string
  title: string
  notes?: string | null
  isAnonymous?: boolean
  callerTranscript?: string | null
  callerTranscriptStatus?: $Enums.CallTranscriptStatus
  callerTranscriptErrorMessage?: string | null
  audioKey?: string | null
  audioContentType?: string | null
  audioSize?: number | null
  episodeDraft?: Prisma.CallKentEpisodeDraftUncheckedCreateNestedOneWithoutCallInput
}

export type CallCreateOrConnectWithoutUserInput = {
  where: Prisma.CallWhereUniqueInput
  create: Prisma.XOR<Prisma.CallCreateWithoutUserInput, Prisma.CallUncheckedCreateWithoutUserInput>
}

export type CallCreateManyUserInputEnvelope = {
  data: Prisma.CallCreateManyUserInput | Prisma.CallCreateManyUserInput[]
}

export type CallUpsertWithWhereUniqueWithoutUserInput = {
  where: Prisma.CallWhereUniqueInput
  update: Prisma.XOR<Prisma.CallUpdateWithoutUserInput, Prisma.CallUncheckedUpdateWithoutUserInput>
  create: Prisma.XOR<Prisma.CallCreateWithoutUserInput, Prisma.CallUncheckedCreateWithoutUserInput>
}

export type CallUpdateWithWhereUniqueWithoutUserInput = {
  where: Prisma.CallWhereUniqueInput
  data: Prisma.XOR<Prisma.CallUpdateWithoutUserInput, Prisma.CallUncheckedUpdateWithoutUserInput>
}

export type CallUpdateManyWithWhereWithoutUserInput = {
  where: Prisma.CallScalarWhereInput
  data: Prisma.XOR<Prisma.CallUpdateManyMutationInput, Prisma.CallUncheckedUpdateManyWithoutUserInput>
}

export type CallScalarWhereInput = {
  AND?: Prisma.CallScalarWhereInput | Prisma.CallScalarWhereInput[]
  OR?: Prisma.CallScalarWhereInput[]
  NOT?: Prisma.CallScalarWhereInput | Prisma.CallScalarWhereInput[]
  id?: Prisma.StringFilter<"Call"> | string
  createdAt?: Prisma.DateTimeFilter<"Call"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Call"> | Date | string
  title?: Prisma.StringFilter<"Call"> | string
  notes?: Prisma.StringNullableFilter<"Call"> | string | null
  isAnonymous?: Prisma.BoolFilter<"Call"> | boolean
  callerTranscript?: Prisma.StringNullableFilter<"Call"> | string | null
  callerTranscriptStatus?: Prisma.EnumCallTranscriptStatusFilter<"Call"> | $Enums.CallTranscriptStatus
  callerTranscriptErrorMessage?: Prisma.StringNullableFilter<"Call"> | string | null
  userId?: Prisma.StringFilter<"Call"> | string
  audioKey?: Prisma.StringNullableFilter<"Call"> | string | null
  audioContentType?: Prisma.StringNullableFilter<"Call"> | string | null
  audioSize?: Prisma.IntNullableFilter<"Call"> | number | null
}

export type CallCreateWithoutEpisodeDraftInput = {
  id?: string
  createdAt?: Date | string
  updatedAt?: Date | string
  title: string
  notes?: string | null
  isAnonymous?: boolean
  callerTranscript?: string | null
  callerTranscriptStatus?: $Enums.CallTranscriptStatus
  callerTranscriptErrorMessage?: string | null
  audioKey?: string | null
  audioContentType?: string | null
  audioSize?: number | null
  user: Prisma.UserCreateNestedOneWithoutCallsInput
}

export type CallUncheckedCreateWithoutEpisodeDraftInput = {
  id?: string
  createdAt?: Date | string
  updatedAt?: Date | string
  title: string
  notes?: string | null
  isAnonymous?: boolean
  callerTranscript?: string | null
  callerTranscriptStatus?: $Enums.CallTranscriptStatus
  callerTranscriptErrorMessage?: string | null
  userId: string
  audioKey?: string | null
  audioContentType?: string | null
  audioSize?: number | null
}

export type CallCreateOrConnectWithoutEpisodeDraftInput = {
  where: Prisma.CallWhereUniqueInput
  create: Prisma.XOR<Prisma.CallCreateWithoutEpisodeDraftInput, Prisma.CallUncheckedCreateWithoutEpisodeDraftInput>
}

export type CallUpsertWithoutEpisodeDraftInput = {
  update: Prisma.XOR<Prisma.CallUpdateWithoutEpisodeDraftInput, Prisma.CallUncheckedUpdateWithoutEpisodeDraftInput>
  create: Prisma.XOR<Prisma.CallCreateWithoutEpisodeDraftInput, Prisma.CallUncheckedCreateWithoutEpisodeDraftInput>
  where?: Prisma.CallWhereInput
}

export type CallUpdateToOneWithWhereWithoutEpisodeDraftInput = {
  where?: Prisma.CallWhereInput
  data: Prisma.XOR<Prisma.CallUpdateWithoutEpisodeDraftInput, Prisma.CallUncheckedUpdateWithoutEpisodeDraftInput>
}

export type CallUpdateWithoutEpisodeDraftInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isAnonymous?: Prisma.BoolFieldUpdateOperationsInput | boolean
  callerTranscript?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  callerTranscriptStatus?: Prisma.EnumCallTranscriptStatusFieldUpdateOperationsInput | $Enums.CallTranscriptStatus
  callerTranscriptErrorMessage?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  audioKey?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  audioContentType?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  audioSize?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  user?: Prisma.UserUpdateOneRequiredWithoutCallsNestedInput
}

export type CallUncheckedUpdateWithoutEpisodeDraftInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isAnonymous?: Prisma.BoolFieldUpdateOperationsInput | boolean
  callerTranscript?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  callerTranscriptStatus?: Prisma.EnumCallTranscriptStatusFieldUpdateOperationsInput | $Enums.CallTranscriptStatus
  callerTranscriptErrorMessage?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  audioKey?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  audioContentType?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  audioSize?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
}

export type CallCreateManyUserInput = {
  id?: string
  createdAt?: Date | string
  updatedAt?: Date | string
  title: string
  notes?: string | null
  isAnonymous?: boolean
  callerTranscript?: string | null
  callerTranscriptStatus?: $Enums.CallTranscriptStatus
  callerTranscriptErrorMessage?: string | null
  audioKey?: string | null
  audioContentType?: string | null
  audioSize?: number | null
}

export type CallUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isAnonymous?: Prisma.BoolFieldUpdateOperationsInput | boolean
  callerTranscript?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  callerTranscriptStatus?: Prisma.EnumCallTranscriptStatusFieldUpdateOperationsInput | $Enums.CallTranscriptStatus
  callerTranscriptErrorMessage?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  audioKey?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  audioContentType?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  audioSize?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  episodeDraft?: Prisma.CallKentEpisodeDraftUpdateOneWithoutCallNestedInput
}

export type CallUncheckedUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isAnonymous?: Prisma.BoolFieldUpdateOperationsInput | boolean
  callerTranscript?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  callerTranscriptStatus?: Prisma.EnumCallTranscriptStatusFieldUpdateOperationsInput | $Enums.CallTranscriptStatus
  callerTranscriptErrorMessage?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  audioKey?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  audioContentType?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  audioSize?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  episodeDraft?: Prisma.CallKentEpisodeDraftUncheckedUpdateOneWithoutCallNestedInput
}

export type CallUncheckedUpdateManyWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isAnonymous?: Prisma.BoolFieldUpdateOperationsInput | boolean
  callerTranscript?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  callerTranscriptStatus?: Prisma.EnumCallTranscriptStatusFieldUpdateOperationsInput | $Enums.CallTranscriptStatus
  callerTranscriptErrorMessage?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  audioKey?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  audioContentType?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  audioSize?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
}



export type CallSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  title?: boolean
  notes?: boolean
  isAnonymous?: boolean
  callerTranscript?: boolean
  callerTranscriptStatus?: boolean
  callerTranscriptErrorMessage?: boolean
  userId?: boolean
  audioKey?: boolean
  audioContentType?: boolean
  audioSize?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  episodeDraft?: boolean | Prisma.Call$episodeDraftArgs<ExtArgs>
}, ExtArgs["result"]["call"]>

export type CallSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  title?: boolean
  notes?: boolean
  isAnonymous?: boolean
  callerTranscript?: boolean
  callerTranscriptStatus?: boolean
  callerTranscriptErrorMessage?: boolean
  userId?: boolean
  audioKey?: boolean
  audioContentType?: boolean
  audioSize?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["call"]>

export type CallSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  title?: boolean
  notes?: boolean
  isAnonymous?: boolean
  callerTranscript?: boolean
  callerTranscriptStatus?: boolean
  callerTranscriptErrorMessage?: boolean
  userId?: boolean
  audioKey?: boolean
  audioContentType?: boolean
  audioSize?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["call"]>

export type CallSelectScalar = {
  id?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  title?: boolean
  notes?: boolean
  isAnonymous?: boolean
  callerTranscript?: boolean
  callerTranscriptStatus?: boolean
  callerTranscriptErrorMessage?: boolean
  userId?: boolean
  audioKey?: boolean
  audioContentType?: boolean
  audioSize?: boolean
}

export type CallOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "createdAt" | "updatedAt" | "title" | "notes" | "isAnonymous" | "callerTranscript" | "callerTranscriptStatus" | "callerTranscriptErrorMessage" | "userId" | "audioKey" | "audioContentType" | "audioSize", ExtArgs["result"]["call"]>
export type CallInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  episodeDraft?: boolean | Prisma.Call$episodeDraftArgs<ExtArgs>
}
export type CallIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}
export type CallIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}

export type $CallPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Call"
  objects: {
    user: Prisma.$UserPayload<ExtArgs>
    episodeDraft: Prisma.$CallKentEpisodeDraftPayload<ExtArgs> | null
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    createdAt: Date
    updatedAt: Date
    title: string
    notes: string | null
    isAnonymous: boolean
    callerTranscript: string | null
    callerTranscriptStatus: $Enums.CallTranscriptStatus
    callerTranscriptErrorMessage: string | null
    userId: string
    audioKey: string | null
    audioContentType: string | null
    audioSize: number | null
  }, ExtArgs["result"]["call"]>
  composites: {}
}

export type CallGetPayload<S extends boolean | null | undefined | CallDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$CallPayload, S>

export type CallCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<CallFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: CallCountAggregateInputType | true
  }

export interface CallDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Call'], meta: { name: 'Call' } }
  /**
   * Find zero or one Call that matches the filter.
   * @param {CallFindUniqueArgs} args - Arguments to find a Call
   * @example
   * // Get one Call
   * const call = await prisma.call.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends CallFindUniqueArgs>(args: Prisma.SelectSubset<T, CallFindUniqueArgs<ExtArgs>>): Prisma.Prisma__CallClient<runtime.Types.Result.GetResult<Prisma.$CallPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Call that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {CallFindUniqueOrThrowArgs} args - Arguments to find a Call
   * @example
   * // Get one Call
   * const call = await prisma.call.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends CallFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, CallFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__CallClient<runtime.Types.Result.GetResult<Prisma.$CallPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Call that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CallFindFirstArgs} args - Arguments to find a Call
   * @example
   * // Get one Call
   * const call = await prisma.call.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends CallFindFirstArgs>(args?: Prisma.SelectSubset<T, CallFindFirstArgs<ExtArgs>>): Prisma.Prisma__CallClient<runtime.Types.Result.GetResult<Prisma.$CallPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Call that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CallFindFirstOrThrowArgs} args - Arguments to find a Call
   * @example
   * // Get one Call
   * const call = await prisma.call.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends CallFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, CallFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__CallClient<runtime.Types.Result.GetResult<Prisma.$CallPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Calls that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CallFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Calls
   * const calls = await prisma.call.findMany()
   * 
   * // Get first 10 Calls
   * const calls = await prisma.call.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const callWithIdOnly = await prisma.call.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends CallFindManyArgs>(args?: Prisma.SelectSubset<T, CallFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$CallPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Call.
   * @param {CallCreateArgs} args - Arguments to create a Call.
   * @example
   * // Create one Call
   * const Call = await prisma.call.create({
   *   data: {
   *     // ... data to create a Call
   *   }
   * })
   * 
   */
  create<T extends CallCreateArgs>(args: Prisma.SelectSubset<T, CallCreateArgs<ExtArgs>>): Prisma.Prisma__CallClient<runtime.Types.Result.GetResult<Prisma.$CallPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Calls.
   * @param {CallCreateManyArgs} args - Arguments to create many Calls.
   * @example
   * // Create many Calls
   * const call = await prisma.call.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends CallCreateManyArgs>(args?: Prisma.SelectSubset<T, CallCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Calls and returns the data saved in the database.
   * @param {CallCreateManyAndReturnArgs} args - Arguments to create many Calls.
   * @example
   * // Create many Calls
   * const call = await prisma.call.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Calls and only return the `id`
   * const callWithIdOnly = await prisma.call.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends CallCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, CallCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$CallPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Call.
   * @param {CallDeleteArgs} args - Arguments to delete one Call.
   * @example
   * // Delete one Call
   * const Call = await prisma.call.delete({
   *   where: {
   *     // ... filter to delete one Call
   *   }
   * })
   * 
   */
  delete<T extends CallDeleteArgs>(args: Prisma.SelectSubset<T, CallDeleteArgs<ExtArgs>>): Prisma.Prisma__CallClient<runtime.Types.Result.GetResult<Prisma.$CallPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Call.
   * @param {CallUpdateArgs} args - Arguments to update one Call.
   * @example
   * // Update one Call
   * const call = await prisma.call.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends CallUpdateArgs>(args: Prisma.SelectSubset<T, CallUpdateArgs<ExtArgs>>): Prisma.Prisma__CallClient<runtime.Types.Result.GetResult<Prisma.$CallPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Calls.
   * @param {CallDeleteManyArgs} args - Arguments to filter Calls to delete.
   * @example
   * // Delete a few Calls
   * const { count } = await prisma.call.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends CallDeleteManyArgs>(args?: Prisma.SelectSubset<T, CallDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Calls.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CallUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Calls
   * const call = await prisma.call.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends CallUpdateManyArgs>(args: Prisma.SelectSubset<T, CallUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Calls and returns the data updated in the database.
   * @param {CallUpdateManyAndReturnArgs} args - Arguments to update many Calls.
   * @example
   * // Update many Calls
   * const call = await prisma.call.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Calls and only return the `id`
   * const callWithIdOnly = await prisma.call.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends CallUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, CallUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$CallPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Call.
   * @param {CallUpsertArgs} args - Arguments to update or create a Call.
   * @example
   * // Update or create a Call
   * const call = await prisma.call.upsert({
   *   create: {
   *     // ... data to create a Call
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Call we want to update
   *   }
   * })
   */
  upsert<T extends CallUpsertArgs>(args: Prisma.SelectSubset<T, CallUpsertArgs<ExtArgs>>): Prisma.Prisma__CallClient<runtime.Types.Result.GetResult<Prisma.$CallPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Calls.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CallCountArgs} args - Arguments to filter Calls to count.
   * @example
   * // Count the number of Calls
   * const count = await prisma.call.count({
   *   where: {
   *     // ... the filter for the Calls we want to count
   *   }
   * })
  **/
  count<T extends CallCountArgs>(
    args?: Prisma.Subset<T, CallCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], CallCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Call.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CallAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends CallAggregateArgs>(args: Prisma.Subset<T, CallAggregateArgs>): Prisma.PrismaPromise<GetCallAggregateType<T>>

  /**
   * Group by Call.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CallGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends CallGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: CallGroupByArgs['orderBy'] }
      : { orderBy?: CallGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, CallGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetCallGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Call model
 */
readonly fields: CallFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Call.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__CallClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  user<T extends Prisma.UserDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.UserDefaultArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  episodeDraft<T extends Prisma.Call$episodeDraftArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Call$episodeDraftArgs<ExtArgs>>): Prisma.Prisma__CallKentEpisodeDraftClient<runtime.Types.Result.GetResult<Prisma.$CallKentEpisodeDraftPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Call model
 */
export interface CallFieldRefs {
  readonly id: Prisma.FieldRef<"Call", 'String'>
  readonly createdAt: Prisma.FieldRef<"Call", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"Call", 'DateTime'>
  readonly title: Prisma.FieldRef<"Call", 'String'>
  readonly notes: Prisma.FieldRef<"Call", 'String'>
  readonly isAnonymous: Prisma.FieldRef<"Call", 'Boolean'>
  readonly callerTranscript: Prisma.FieldRef<"Call", 'String'>
  readonly callerTranscriptStatus: Prisma.FieldRef<"Call", 'CallTranscriptStatus'>
  readonly callerTranscriptErrorMessage: Prisma.FieldRef<"Call", 'String'>
  readonly userId: Prisma.FieldRef<"Call", 'String'>
  readonly audioKey: Prisma.FieldRef<"Call", 'String'>
  readonly audioContentType: Prisma.FieldRef<"Call", 'String'>
  readonly audioSize: Prisma.FieldRef<"Call", 'Int'>
}
    

// Custom InputTypes
/**
 * Call findUnique
 */
export type CallFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Call
   */
  select?: Prisma.CallSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Call
   */
  omit?: Prisma.CallOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CallInclude<ExtArgs> | null
  /**
   * Filter, which Call to fetch.
   */
  where: Prisma.CallWhereUniqueInput
}

/**
 * Call findUniqueOrThrow
 */
export type CallFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Call
   */
  select?: Prisma.CallSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Call
   */
  omit?: Prisma.CallOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CallInclude<ExtArgs> | null
  /**
   * Filter, which Call to fetch.
   */
  where: Prisma.CallWhereUniqueInput
}

/**
 * Call findFirst
 */
export type CallFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Call
   */
  select?: Prisma.CallSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Call
   */
  omit?: Prisma.CallOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CallInclude<ExtArgs> | null
  /**
   * Filter, which Call to fetch.
   */
  where?: Prisma.CallWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Calls to fetch.
   */
  orderBy?: Prisma.CallOrderByWithRelationInput | Prisma.CallOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Calls.
   */
  cursor?: Prisma.CallWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Calls from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Calls.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Calls.
   */
  distinct?: Prisma.CallScalarFieldEnum | Prisma.CallScalarFieldEnum[]
}

/**
 * Call findFirstOrThrow
 */
export type CallFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Call
   */
  select?: Prisma.CallSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Call
   */
  omit?: Prisma.CallOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CallInclude<ExtArgs> | null
  /**
   * Filter, which Call to fetch.
   */
  where?: Prisma.CallWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Calls to fetch.
   */
  orderBy?: Prisma.CallOrderByWithRelationInput | Prisma.CallOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Calls.
   */
  cursor?: Prisma.CallWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Calls from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Calls.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Calls.
   */
  distinct?: Prisma.CallScalarFieldEnum | Prisma.CallScalarFieldEnum[]
}

/**
 * Call findMany
 */
export type CallFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Call
   */
  select?: Prisma.CallSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Call
   */
  omit?: Prisma.CallOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CallInclude<ExtArgs> | null
  /**
   * Filter, which Calls to fetch.
   */
  where?: Prisma.CallWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Calls to fetch.
   */
  orderBy?: Prisma.CallOrderByWithRelationInput | Prisma.CallOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Calls.
   */
  cursor?: Prisma.CallWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Calls from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Calls.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Calls.
   */
  distinct?: Prisma.CallScalarFieldEnum | Prisma.CallScalarFieldEnum[]
}

/**
 * Call create
 */
export type CallCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Call
   */
  select?: Prisma.CallSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Call
   */
  omit?: Prisma.CallOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CallInclude<ExtArgs> | null
  /**
   * The data needed to create a Call.
   */
  data: Prisma.XOR<Prisma.CallCreateInput, Prisma.CallUncheckedCreateInput>
}

/**
 * Call createMany
 */
export type CallCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Calls.
   */
  data: Prisma.CallCreateManyInput | Prisma.CallCreateManyInput[]
}

/**
 * Call createManyAndReturn
 */
export type CallCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Call
   */
  select?: Prisma.CallSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Call
   */
  omit?: Prisma.CallOmit<ExtArgs> | null
  /**
   * The data used to create many Calls.
   */
  data: Prisma.CallCreateManyInput | Prisma.CallCreateManyInput[]
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CallIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * Call update
 */
export type CallUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Call
   */
  select?: Prisma.CallSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Call
   */
  omit?: Prisma.CallOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CallInclude<ExtArgs> | null
  /**
   * The data needed to update a Call.
   */
  data: Prisma.XOR<Prisma.CallUpdateInput, Prisma.CallUncheckedUpdateInput>
  /**
   * Choose, which Call to update.
   */
  where: Prisma.CallWhereUniqueInput
}

/**
 * Call updateMany
 */
export type CallUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Calls.
   */
  data: Prisma.XOR<Prisma.CallUpdateManyMutationInput, Prisma.CallUncheckedUpdateManyInput>
  /**
   * Filter which Calls to update
   */
  where?: Prisma.CallWhereInput
  /**
   * Limit how many Calls to update.
   */
  limit?: number
}

/**
 * Call updateManyAndReturn
 */
export type CallUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Call
   */
  select?: Prisma.CallSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Call
   */
  omit?: Prisma.CallOmit<ExtArgs> | null
  /**
   * The data used to update Calls.
   */
  data: Prisma.XOR<Prisma.CallUpdateManyMutationInput, Prisma.CallUncheckedUpdateManyInput>
  /**
   * Filter which Calls to update
   */
  where?: Prisma.CallWhereInput
  /**
   * Limit how many Calls to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CallIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * Call upsert
 */
export type CallUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Call
   */
  select?: Prisma.CallSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Call
   */
  omit?: Prisma.CallOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CallInclude<ExtArgs> | null
  /**
   * The filter to search for the Call to update in case it exists.
   */
  where: Prisma.CallWhereUniqueInput
  /**
   * In case the Call found by the `where` argument doesn't exist, create a new Call with this data.
   */
  create: Prisma.XOR<Prisma.CallCreateInput, Prisma.CallUncheckedCreateInput>
  /**
   * In case the Call was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.CallUpdateInput, Prisma.CallUncheckedUpdateInput>
}

/**
 * Call delete
 */
export type CallDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Call
   */
  select?: Prisma.CallSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Call
   */
  omit?: Prisma.CallOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CallInclude<ExtArgs> | null
  /**
   * Filter which Call to delete.
   */
  where: Prisma.CallWhereUniqueInput
}

/**
 * Call deleteMany
 */
export type CallDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Calls to delete
   */
  where?: Prisma.CallWhereInput
  /**
   * Limit how many Calls to delete.
   */
  limit?: number
}

/**
 * Call.episodeDraft
 */
export type Call$episodeDraftArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CallKentEpisodeDraft
   */
  select?: Prisma.CallKentEpisodeDraftSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CallKentEpisodeDraft
   */
  omit?: Prisma.CallKentEpisodeDraftOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CallKentEpisodeDraftInclude<ExtArgs> | null
  where?: Prisma.CallKentEpisodeDraftWhereInput
}

/**
 * Call without action
 */
export type CallDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Call
   */
  select?: Prisma.CallSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Call
   */
  omit?: Prisma.CallOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CallInclude<ExtArgs> | null
}
