
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `PostRead` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.ts"
import type * as Prisma from "../internal/prismaNamespace.ts"

/**
 * Model PostRead
 * 
 */
export type PostReadModel = runtime.Types.Result.DefaultSelection<Prisma.$PostReadPayload>

export type AggregatePostRead = {
  _count: PostReadCountAggregateOutputType | null
  _min: PostReadMinAggregateOutputType | null
  _max: PostReadMaxAggregateOutputType | null
}

export type PostReadMinAggregateOutputType = {
  id: string | null
  createdAt: Date | null
  userId: string | null
  clientId: string | null
  postSlug: string | null
}

export type PostReadMaxAggregateOutputType = {
  id: string | null
  createdAt: Date | null
  userId: string | null
  clientId: string | null
  postSlug: string | null
}

export type PostReadCountAggregateOutputType = {
  id: number
  createdAt: number
  userId: number
  clientId: number
  postSlug: number
  _all: number
}


export type PostReadMinAggregateInputType = {
  id?: true
  createdAt?: true
  userId?: true
  clientId?: true
  postSlug?: true
}

export type PostReadMaxAggregateInputType = {
  id?: true
  createdAt?: true
  userId?: true
  clientId?: true
  postSlug?: true
}

export type PostReadCountAggregateInputType = {
  id?: true
  createdAt?: true
  userId?: true
  clientId?: true
  postSlug?: true
  _all?: true
}

export type PostReadAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which PostRead to aggregate.
   */
  where?: Prisma.PostReadWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of PostReads to fetch.
   */
  orderBy?: Prisma.PostReadOrderByWithRelationInput | Prisma.PostReadOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.PostReadWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` PostReads from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` PostReads.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned PostReads
  **/
  _count?: true | PostReadCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: PostReadMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: PostReadMaxAggregateInputType
}

export type GetPostReadAggregateType<T extends PostReadAggregateArgs> = {
      [P in keyof T & keyof AggregatePostRead]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregatePostRead[P]>
    : Prisma.GetScalarType<T[P], AggregatePostRead[P]>
}




export type PostReadGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.PostReadWhereInput
  orderBy?: Prisma.PostReadOrderByWithAggregationInput | Prisma.PostReadOrderByWithAggregationInput[]
  by: Prisma.PostReadScalarFieldEnum[] | Prisma.PostReadScalarFieldEnum
  having?: Prisma.PostReadScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: PostReadCountAggregateInputType | true
  _min?: PostReadMinAggregateInputType
  _max?: PostReadMaxAggregateInputType
}

export type PostReadGroupByOutputType = {
  id: string
  createdAt: Date
  userId: string | null
  clientId: string | null
  postSlug: string
  _count: PostReadCountAggregateOutputType | null
  _min: PostReadMinAggregateOutputType | null
  _max: PostReadMaxAggregateOutputType | null
}

export type GetPostReadGroupByPayload<T extends PostReadGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<PostReadGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof PostReadGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], PostReadGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], PostReadGroupByOutputType[P]>
      }
    >
  >



export type PostReadWhereInput = {
  AND?: Prisma.PostReadWhereInput | Prisma.PostReadWhereInput[]
  OR?: Prisma.PostReadWhereInput[]
  NOT?: Prisma.PostReadWhereInput | Prisma.PostReadWhereInput[]
  id?: Prisma.StringFilter<"PostRead"> | string
  createdAt?: Prisma.DateTimeFilter<"PostRead"> | Date | string
  userId?: Prisma.StringNullableFilter<"PostRead"> | string | null
  clientId?: Prisma.StringNullableFilter<"PostRead"> | string | null
  postSlug?: Prisma.StringFilter<"PostRead"> | string
  user?: Prisma.XOR<Prisma.UserNullableScalarRelationFilter, Prisma.UserWhereInput> | null
}

export type PostReadOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  userId?: Prisma.SortOrderInput | Prisma.SortOrder
  clientId?: Prisma.SortOrderInput | Prisma.SortOrder
  postSlug?: Prisma.SortOrder
  user?: Prisma.UserOrderByWithRelationInput
}

export type PostReadWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.PostReadWhereInput | Prisma.PostReadWhereInput[]
  OR?: Prisma.PostReadWhereInput[]
  NOT?: Prisma.PostReadWhereInput | Prisma.PostReadWhereInput[]
  createdAt?: Prisma.DateTimeFilter<"PostRead"> | Date | string
  userId?: Prisma.StringNullableFilter<"PostRead"> | string | null
  clientId?: Prisma.StringNullableFilter<"PostRead"> | string | null
  postSlug?: Prisma.StringFilter<"PostRead"> | string
  user?: Prisma.XOR<Prisma.UserNullableScalarRelationFilter, Prisma.UserWhereInput> | null
}, "id">

export type PostReadOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  userId?: Prisma.SortOrderInput | Prisma.SortOrder
  clientId?: Prisma.SortOrderInput | Prisma.SortOrder
  postSlug?: Prisma.SortOrder
  _count?: Prisma.PostReadCountOrderByAggregateInput
  _max?: Prisma.PostReadMaxOrderByAggregateInput
  _min?: Prisma.PostReadMinOrderByAggregateInput
}

export type PostReadScalarWhereWithAggregatesInput = {
  AND?: Prisma.PostReadScalarWhereWithAggregatesInput | Prisma.PostReadScalarWhereWithAggregatesInput[]
  OR?: Prisma.PostReadScalarWhereWithAggregatesInput[]
  NOT?: Prisma.PostReadScalarWhereWithAggregatesInput | Prisma.PostReadScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"PostRead"> | string
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"PostRead"> | Date | string
  userId?: Prisma.StringNullableWithAggregatesFilter<"PostRead"> | string | null
  clientId?: Prisma.StringNullableWithAggregatesFilter<"PostRead"> | string | null
  postSlug?: Prisma.StringWithAggregatesFilter<"PostRead"> | string
}

export type PostReadCreateInput = {
  id?: string
  createdAt?: Date | string
  clientId?: string | null
  postSlug: string
  user?: Prisma.UserCreateNestedOneWithoutPostReadsInput
}

export type PostReadUncheckedCreateInput = {
  id?: string
  createdAt?: Date | string
  userId?: string | null
  clientId?: string | null
  postSlug: string
}

export type PostReadUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  clientId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  postSlug?: Prisma.StringFieldUpdateOperationsInput | string
  user?: Prisma.UserUpdateOneWithoutPostReadsNestedInput
}

export type PostReadUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  userId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  clientId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  postSlug?: Prisma.StringFieldUpdateOperationsInput | string
}

export type PostReadCreateManyInput = {
  id?: string
  createdAt?: Date | string
  userId?: string | null
  clientId?: string | null
  postSlug: string
}

export type PostReadUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  clientId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  postSlug?: Prisma.StringFieldUpdateOperationsInput | string
}

export type PostReadUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  userId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  clientId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  postSlug?: Prisma.StringFieldUpdateOperationsInput | string
}

export type PostReadListRelationFilter = {
  every?: Prisma.PostReadWhereInput
  some?: Prisma.PostReadWhereInput
  none?: Prisma.PostReadWhereInput
}

export type PostReadOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type PostReadCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  clientId?: Prisma.SortOrder
  postSlug?: Prisma.SortOrder
}

export type PostReadMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  clientId?: Prisma.SortOrder
  postSlug?: Prisma.SortOrder
}

export type PostReadMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  clientId?: Prisma.SortOrder
  postSlug?: Prisma.SortOrder
}

export type PostReadCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.PostReadCreateWithoutUserInput, Prisma.PostReadUncheckedCreateWithoutUserInput> | Prisma.PostReadCreateWithoutUserInput[] | Prisma.PostReadUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.PostReadCreateOrConnectWithoutUserInput | Prisma.PostReadCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.PostReadCreateManyUserInputEnvelope
  connect?: Prisma.PostReadWhereUniqueInput | Prisma.PostReadWhereUniqueInput[]
}

export type PostReadUncheckedCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.PostReadCreateWithoutUserInput, Prisma.PostReadUncheckedCreateWithoutUserInput> | Prisma.PostReadCreateWithoutUserInput[] | Prisma.PostReadUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.PostReadCreateOrConnectWithoutUserInput | Prisma.PostReadCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.PostReadCreateManyUserInputEnvelope
  connect?: Prisma.PostReadWhereUniqueInput | Prisma.PostReadWhereUniqueInput[]
}

export type PostReadUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.PostReadCreateWithoutUserInput, Prisma.PostReadUncheckedCreateWithoutUserInput> | Prisma.PostReadCreateWithoutUserInput[] | Prisma.PostReadUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.PostReadCreateOrConnectWithoutUserInput | Prisma.PostReadCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.PostReadUpsertWithWhereUniqueWithoutUserInput | Prisma.PostReadUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.PostReadCreateManyUserInputEnvelope
  set?: Prisma.PostReadWhereUniqueInput | Prisma.PostReadWhereUniqueInput[]
  disconnect?: Prisma.PostReadWhereUniqueInput | Prisma.PostReadWhereUniqueInput[]
  delete?: Prisma.PostReadWhereUniqueInput | Prisma.PostReadWhereUniqueInput[]
  connect?: Prisma.PostReadWhereUniqueInput | Prisma.PostReadWhereUniqueInput[]
  update?: Prisma.PostReadUpdateWithWhereUniqueWithoutUserInput | Prisma.PostReadUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.PostReadUpdateManyWithWhereWithoutUserInput | Prisma.PostReadUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.PostReadScalarWhereInput | Prisma.PostReadScalarWhereInput[]
}

export type PostReadUncheckedUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.PostReadCreateWithoutUserInput, Prisma.PostReadUncheckedCreateWithoutUserInput> | Prisma.PostReadCreateWithoutUserInput[] | Prisma.PostReadUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.PostReadCreateOrConnectWithoutUserInput | Prisma.PostReadCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.PostReadUpsertWithWhereUniqueWithoutUserInput | Prisma.PostReadUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.PostReadCreateManyUserInputEnvelope
  set?: Prisma.PostReadWhereUniqueInput | Prisma.PostReadWhereUniqueInput[]
  disconnect?: Prisma.PostReadWhereUniqueInput | Prisma.PostReadWhereUniqueInput[]
  delete?: Prisma.PostReadWhereUniqueInput | Prisma.PostReadWhereUniqueInput[]
  connect?: Prisma.PostReadWhereUniqueInput | Prisma.PostReadWhereUniqueInput[]
  update?: Prisma.PostReadUpdateWithWhereUniqueWithoutUserInput | Prisma.PostReadUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.PostReadUpdateManyWithWhereWithoutUserInput | Prisma.PostReadUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.PostReadScalarWhereInput | Prisma.PostReadScalarWhereInput[]
}

export type PostReadCreateWithoutUserInput = {
  id?: string
  createdAt?: Date | string
  clientId?: string | null
  postSlug: string
}

export type PostReadUncheckedCreateWithoutUserInput = {
  id?: string
  createdAt?: Date | string
  clientId?: string | null
  postSlug: string
}

export type PostReadCreateOrConnectWithoutUserInput = {
  where: Prisma.PostReadWhereUniqueInput
  create: Prisma.XOR<Prisma.PostReadCreateWithoutUserInput, Prisma.PostReadUncheckedCreateWithoutUserInput>
}

export type PostReadCreateManyUserInputEnvelope = {
  data: Prisma.PostReadCreateManyUserInput | Prisma.PostReadCreateManyUserInput[]
}

export type PostReadUpsertWithWhereUniqueWithoutUserInput = {
  where: Prisma.PostReadWhereUniqueInput
  update: Prisma.XOR<Prisma.PostReadUpdateWithoutUserInput, Prisma.PostReadUncheckedUpdateWithoutUserInput>
  create: Prisma.XOR<Prisma.PostReadCreateWithoutUserInput, Prisma.PostReadUncheckedCreateWithoutUserInput>
}

export type PostReadUpdateWithWhereUniqueWithoutUserInput = {
  where: Prisma.PostReadWhereUniqueInput
  data: Prisma.XOR<Prisma.PostReadUpdateWithoutUserInput, Prisma.PostReadUncheckedUpdateWithoutUserInput>
}

export type PostReadUpdateManyWithWhereWithoutUserInput = {
  where: Prisma.PostReadScalarWhereInput
  data: Prisma.XOR<Prisma.PostReadUpdateManyMutationInput, Prisma.PostReadUncheckedUpdateManyWithoutUserInput>
}

export type PostReadScalarWhereInput = {
  AND?: Prisma.PostReadScalarWhereInput | Prisma.PostReadScalarWhereInput[]
  OR?: Prisma.PostReadScalarWhereInput[]
  NOT?: Prisma.PostReadScalarWhereInput | Prisma.PostReadScalarWhereInput[]
  id?: Prisma.StringFilter<"PostRead"> | string
  createdAt?: Prisma.DateTimeFilter<"PostRead"> | Date | string
  userId?: Prisma.StringNullableFilter<"PostRead"> | string | null
  clientId?: Prisma.StringNullableFilter<"PostRead"> | string | null
  postSlug?: Prisma.StringFilter<"PostRead"> | string
}

export type PostReadCreateManyUserInput = {
  id?: string
  createdAt?: Date | string
  clientId?: string | null
  postSlug: string
}

export type PostReadUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  clientId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  postSlug?: Prisma.StringFieldUpdateOperationsInput | string
}

export type PostReadUncheckedUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  clientId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  postSlug?: Prisma.StringFieldUpdateOperationsInput | string
}

export type PostReadUncheckedUpdateManyWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  clientId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  postSlug?: Prisma.StringFieldUpdateOperationsInput | string
}



export type PostReadSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  createdAt?: boolean
  userId?: boolean
  clientId?: boolean
  postSlug?: boolean
  user?: boolean | Prisma.PostRead$userArgs<ExtArgs>
}, ExtArgs["result"]["postRead"]>

export type PostReadSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  createdAt?: boolean
  userId?: boolean
  clientId?: boolean
  postSlug?: boolean
  user?: boolean | Prisma.PostRead$userArgs<ExtArgs>
}, ExtArgs["result"]["postRead"]>

export type PostReadSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  createdAt?: boolean
  userId?: boolean
  clientId?: boolean
  postSlug?: boolean
  user?: boolean | Prisma.PostRead$userArgs<ExtArgs>
}, ExtArgs["result"]["postRead"]>

export type PostReadSelectScalar = {
  id?: boolean
  createdAt?: boolean
  userId?: boolean
  clientId?: boolean
  postSlug?: boolean
}

export type PostReadOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "createdAt" | "userId" | "clientId" | "postSlug", ExtArgs["result"]["postRead"]>
export type PostReadInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.PostRead$userArgs<ExtArgs>
}
export type PostReadIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.PostRead$userArgs<ExtArgs>
}
export type PostReadIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.PostRead$userArgs<ExtArgs>
}

export type $PostReadPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "PostRead"
  objects: {
    user: Prisma.$UserPayload<ExtArgs> | null
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    createdAt: Date
    userId: string | null
    clientId: string | null
    postSlug: string
  }, ExtArgs["result"]["postRead"]>
  composites: {}
}

export type PostReadGetPayload<S extends boolean | null | undefined | PostReadDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$PostReadPayload, S>

export type PostReadCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<PostReadFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: PostReadCountAggregateInputType | true
  }

export interface PostReadDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['PostRead'], meta: { name: 'PostRead' } }
  /**
   * Find zero or one PostRead that matches the filter.
   * @param {PostReadFindUniqueArgs} args - Arguments to find a PostRead
   * @example
   * // Get one PostRead
   * const postRead = await prisma.postRead.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends PostReadFindUniqueArgs>(args: Prisma.SelectSubset<T, PostReadFindUniqueArgs<ExtArgs>>): Prisma.Prisma__PostReadClient<runtime.Types.Result.GetResult<Prisma.$PostReadPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one PostRead that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {PostReadFindUniqueOrThrowArgs} args - Arguments to find a PostRead
   * @example
   * // Get one PostRead
   * const postRead = await prisma.postRead.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends PostReadFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, PostReadFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__PostReadClient<runtime.Types.Result.GetResult<Prisma.$PostReadPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first PostRead that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PostReadFindFirstArgs} args - Arguments to find a PostRead
   * @example
   * // Get one PostRead
   * const postRead = await prisma.postRead.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends PostReadFindFirstArgs>(args?: Prisma.SelectSubset<T, PostReadFindFirstArgs<ExtArgs>>): Prisma.Prisma__PostReadClient<runtime.Types.Result.GetResult<Prisma.$PostReadPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first PostRead that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PostReadFindFirstOrThrowArgs} args - Arguments to find a PostRead
   * @example
   * // Get one PostRead
   * const postRead = await prisma.postRead.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends PostReadFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, PostReadFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__PostReadClient<runtime.Types.Result.GetResult<Prisma.$PostReadPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more PostReads that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PostReadFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all PostReads
   * const postReads = await prisma.postRead.findMany()
   * 
   * // Get first 10 PostReads
   * const postReads = await prisma.postRead.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const postReadWithIdOnly = await prisma.postRead.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends PostReadFindManyArgs>(args?: Prisma.SelectSubset<T, PostReadFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PostReadPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a PostRead.
   * @param {PostReadCreateArgs} args - Arguments to create a PostRead.
   * @example
   * // Create one PostRead
   * const PostRead = await prisma.postRead.create({
   *   data: {
   *     // ... data to create a PostRead
   *   }
   * })
   * 
   */
  create<T extends PostReadCreateArgs>(args: Prisma.SelectSubset<T, PostReadCreateArgs<ExtArgs>>): Prisma.Prisma__PostReadClient<runtime.Types.Result.GetResult<Prisma.$PostReadPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many PostReads.
   * @param {PostReadCreateManyArgs} args - Arguments to create many PostReads.
   * @example
   * // Create many PostReads
   * const postRead = await prisma.postRead.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends PostReadCreateManyArgs>(args?: Prisma.SelectSubset<T, PostReadCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many PostReads and returns the data saved in the database.
   * @param {PostReadCreateManyAndReturnArgs} args - Arguments to create many PostReads.
   * @example
   * // Create many PostReads
   * const postRead = await prisma.postRead.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many PostReads and only return the `id`
   * const postReadWithIdOnly = await prisma.postRead.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends PostReadCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, PostReadCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PostReadPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a PostRead.
   * @param {PostReadDeleteArgs} args - Arguments to delete one PostRead.
   * @example
   * // Delete one PostRead
   * const PostRead = await prisma.postRead.delete({
   *   where: {
   *     // ... filter to delete one PostRead
   *   }
   * })
   * 
   */
  delete<T extends PostReadDeleteArgs>(args: Prisma.SelectSubset<T, PostReadDeleteArgs<ExtArgs>>): Prisma.Prisma__PostReadClient<runtime.Types.Result.GetResult<Prisma.$PostReadPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one PostRead.
   * @param {PostReadUpdateArgs} args - Arguments to update one PostRead.
   * @example
   * // Update one PostRead
   * const postRead = await prisma.postRead.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends PostReadUpdateArgs>(args: Prisma.SelectSubset<T, PostReadUpdateArgs<ExtArgs>>): Prisma.Prisma__PostReadClient<runtime.Types.Result.GetResult<Prisma.$PostReadPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more PostReads.
   * @param {PostReadDeleteManyArgs} args - Arguments to filter PostReads to delete.
   * @example
   * // Delete a few PostReads
   * const { count } = await prisma.postRead.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends PostReadDeleteManyArgs>(args?: Prisma.SelectSubset<T, PostReadDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more PostReads.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PostReadUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many PostReads
   * const postRead = await prisma.postRead.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends PostReadUpdateManyArgs>(args: Prisma.SelectSubset<T, PostReadUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more PostReads and returns the data updated in the database.
   * @param {PostReadUpdateManyAndReturnArgs} args - Arguments to update many PostReads.
   * @example
   * // Update many PostReads
   * const postRead = await prisma.postRead.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more PostReads and only return the `id`
   * const postReadWithIdOnly = await prisma.postRead.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends PostReadUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, PostReadUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PostReadPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one PostRead.
   * @param {PostReadUpsertArgs} args - Arguments to update or create a PostRead.
   * @example
   * // Update or create a PostRead
   * const postRead = await prisma.postRead.upsert({
   *   create: {
   *     // ... data to create a PostRead
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the PostRead we want to update
   *   }
   * })
   */
  upsert<T extends PostReadUpsertArgs>(args: Prisma.SelectSubset<T, PostReadUpsertArgs<ExtArgs>>): Prisma.Prisma__PostReadClient<runtime.Types.Result.GetResult<Prisma.$PostReadPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of PostReads.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PostReadCountArgs} args - Arguments to filter PostReads to count.
   * @example
   * // Count the number of PostReads
   * const count = await prisma.postRead.count({
   *   where: {
   *     // ... the filter for the PostReads we want to count
   *   }
   * })
  **/
  count<T extends PostReadCountArgs>(
    args?: Prisma.Subset<T, PostReadCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], PostReadCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a PostRead.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PostReadAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends PostReadAggregateArgs>(args: Prisma.Subset<T, PostReadAggregateArgs>): Prisma.PrismaPromise<GetPostReadAggregateType<T>>

  /**
   * Group by PostRead.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PostReadGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends PostReadGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: PostReadGroupByArgs['orderBy'] }
      : { orderBy?: PostReadGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, PostReadGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetPostReadGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the PostRead model
 */
readonly fields: PostReadFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for PostRead.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__PostReadClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  user<T extends Prisma.PostRead$userArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.PostRead$userArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the PostRead model
 */
export interface PostReadFieldRefs {
  readonly id: Prisma.FieldRef<"PostRead", 'String'>
  readonly createdAt: Prisma.FieldRef<"PostRead", 'DateTime'>
  readonly userId: Prisma.FieldRef<"PostRead", 'String'>
  readonly clientId: Prisma.FieldRef<"PostRead", 'String'>
  readonly postSlug: Prisma.FieldRef<"PostRead", 'String'>
}
    

// Custom InputTypes
/**
 * PostRead findUnique
 */
export type PostReadFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PostRead
   */
  select?: Prisma.PostReadSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PostRead
   */
  omit?: Prisma.PostReadOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PostReadInclude<ExtArgs> | null
  /**
   * Filter, which PostRead to fetch.
   */
  where: Prisma.PostReadWhereUniqueInput
}

/**
 * PostRead findUniqueOrThrow
 */
export type PostReadFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PostRead
   */
  select?: Prisma.PostReadSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PostRead
   */
  omit?: Prisma.PostReadOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PostReadInclude<ExtArgs> | null
  /**
   * Filter, which PostRead to fetch.
   */
  where: Prisma.PostReadWhereUniqueInput
}

/**
 * PostRead findFirst
 */
export type PostReadFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PostRead
   */
  select?: Prisma.PostReadSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PostRead
   */
  omit?: Prisma.PostReadOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PostReadInclude<ExtArgs> | null
  /**
   * Filter, which PostRead to fetch.
   */
  where?: Prisma.PostReadWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of PostReads to fetch.
   */
  orderBy?: Prisma.PostReadOrderByWithRelationInput | Prisma.PostReadOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for PostReads.
   */
  cursor?: Prisma.PostReadWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` PostReads from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` PostReads.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of PostReads.
   */
  distinct?: Prisma.PostReadScalarFieldEnum | Prisma.PostReadScalarFieldEnum[]
}

/**
 * PostRead findFirstOrThrow
 */
export type PostReadFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PostRead
   */
  select?: Prisma.PostReadSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PostRead
   */
  omit?: Prisma.PostReadOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PostReadInclude<ExtArgs> | null
  /**
   * Filter, which PostRead to fetch.
   */
  where?: Prisma.PostReadWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of PostReads to fetch.
   */
  orderBy?: Prisma.PostReadOrderByWithRelationInput | Prisma.PostReadOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for PostReads.
   */
  cursor?: Prisma.PostReadWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` PostReads from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` PostReads.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of PostReads.
   */
  distinct?: Prisma.PostReadScalarFieldEnum | Prisma.PostReadScalarFieldEnum[]
}

/**
 * PostRead findMany
 */
export type PostReadFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PostRead
   */
  select?: Prisma.PostReadSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PostRead
   */
  omit?: Prisma.PostReadOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PostReadInclude<ExtArgs> | null
  /**
   * Filter, which PostReads to fetch.
   */
  where?: Prisma.PostReadWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of PostReads to fetch.
   */
  orderBy?: Prisma.PostReadOrderByWithRelationInput | Prisma.PostReadOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing PostReads.
   */
  cursor?: Prisma.PostReadWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` PostReads from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` PostReads.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of PostReads.
   */
  distinct?: Prisma.PostReadScalarFieldEnum | Prisma.PostReadScalarFieldEnum[]
}

/**
 * PostRead create
 */
export type PostReadCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PostRead
   */
  select?: Prisma.PostReadSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PostRead
   */
  omit?: Prisma.PostReadOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PostReadInclude<ExtArgs> | null
  /**
   * The data needed to create a PostRead.
   */
  data: Prisma.XOR<Prisma.PostReadCreateInput, Prisma.PostReadUncheckedCreateInput>
}

/**
 * PostRead createMany
 */
export type PostReadCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many PostReads.
   */
  data: Prisma.PostReadCreateManyInput | Prisma.PostReadCreateManyInput[]
}

/**
 * PostRead createManyAndReturn
 */
export type PostReadCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PostRead
   */
  select?: Prisma.PostReadSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the PostRead
   */
  omit?: Prisma.PostReadOmit<ExtArgs> | null
  /**
   * The data used to create many PostReads.
   */
  data: Prisma.PostReadCreateManyInput | Prisma.PostReadCreateManyInput[]
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PostReadIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * PostRead update
 */
export type PostReadUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PostRead
   */
  select?: Prisma.PostReadSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PostRead
   */
  omit?: Prisma.PostReadOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PostReadInclude<ExtArgs> | null
  /**
   * The data needed to update a PostRead.
   */
  data: Prisma.XOR<Prisma.PostReadUpdateInput, Prisma.PostReadUncheckedUpdateInput>
  /**
   * Choose, which PostRead to update.
   */
  where: Prisma.PostReadWhereUniqueInput
}

/**
 * PostRead updateMany
 */
export type PostReadUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update PostReads.
   */
  data: Prisma.XOR<Prisma.PostReadUpdateManyMutationInput, Prisma.PostReadUncheckedUpdateManyInput>
  /**
   * Filter which PostReads to update
   */
  where?: Prisma.PostReadWhereInput
  /**
   * Limit how many PostReads to update.
   */
  limit?: number
}

/**
 * PostRead updateManyAndReturn
 */
export type PostReadUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PostRead
   */
  select?: Prisma.PostReadSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the PostRead
   */
  omit?: Prisma.PostReadOmit<ExtArgs> | null
  /**
   * The data used to update PostReads.
   */
  data: Prisma.XOR<Prisma.PostReadUpdateManyMutationInput, Prisma.PostReadUncheckedUpdateManyInput>
  /**
   * Filter which PostReads to update
   */
  where?: Prisma.PostReadWhereInput
  /**
   * Limit how many PostReads to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PostReadIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * PostRead upsert
 */
export type PostReadUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PostRead
   */
  select?: Prisma.PostReadSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PostRead
   */
  omit?: Prisma.PostReadOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PostReadInclude<ExtArgs> | null
  /**
   * The filter to search for the PostRead to update in case it exists.
   */
  where: Prisma.PostReadWhereUniqueInput
  /**
   * In case the PostRead found by the `where` argument doesn't exist, create a new PostRead with this data.
   */
  create: Prisma.XOR<Prisma.PostReadCreateInput, Prisma.PostReadUncheckedCreateInput>
  /**
   * In case the PostRead was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.PostReadUpdateInput, Prisma.PostReadUncheckedUpdateInput>
}

/**
 * PostRead delete
 */
export type PostReadDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PostRead
   */
  select?: Prisma.PostReadSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PostRead
   */
  omit?: Prisma.PostReadOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PostReadInclude<ExtArgs> | null
  /**
   * Filter which PostRead to delete.
   */
  where: Prisma.PostReadWhereUniqueInput
}

/**
 * PostRead deleteMany
 */
export type PostReadDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which PostReads to delete
   */
  where?: Prisma.PostReadWhereInput
  /**
   * Limit how many PostReads to delete.
   */
  limit?: number
}

/**
 * PostRead.user
 */
export type PostRead$userArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the User
   */
  select?: Prisma.UserSelect<ExtArgs> | null
  /**
   * Omit specific fields from the User
   */
  omit?: Prisma.UserOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserInclude<ExtArgs> | null
  where?: Prisma.UserWhereInput
}

/**
 * PostRead without action
 */
export type PostReadDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PostRead
   */
  select?: Prisma.PostReadSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PostRead
   */
  omit?: Prisma.PostReadOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PostReadInclude<ExtArgs> | null
}
