
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `User` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.ts"
import type * as Prisma from "../internal/prismaNamespace.ts"

/**
 * Model User
 * 
 */
export type UserModel = runtime.Types.Result.DefaultSelection<Prisma.$UserPayload>

export type AggregateUser = {
  _count: UserCountAggregateOutputType | null
  _min: UserMinAggregateOutputType | null
  _max: UserMaxAggregateOutputType | null
}

export type UserMinAggregateOutputType = {
  id: string | null
  createdAt: Date | null
  updatedAt: Date | null
  email: string | null
  firstName: string | null
  discordId: string | null
  kitId: string | null
  role: string | null
  team: string | null
}

export type UserMaxAggregateOutputType = {
  id: string | null
  createdAt: Date | null
  updatedAt: Date | null
  email: string | null
  firstName: string | null
  discordId: string | null
  kitId: string | null
  role: string | null
  team: string | null
}

export type UserCountAggregateOutputType = {
  id: number
  createdAt: number
  updatedAt: number
  email: number
  firstName: number
  discordId: number
  kitId: number
  role: number
  team: number
  _all: number
}


export type UserMinAggregateInputType = {
  id?: true
  createdAt?: true
  updatedAt?: true
  email?: true
  firstName?: true
  discordId?: true
  kitId?: true
  role?: true
  team?: true
}

export type UserMaxAggregateInputType = {
  id?: true
  createdAt?: true
  updatedAt?: true
  email?: true
  firstName?: true
  discordId?: true
  kitId?: true
  role?: true
  team?: true
}

export type UserCountAggregateInputType = {
  id?: true
  createdAt?: true
  updatedAt?: true
  email?: true
  firstName?: true
  discordId?: true
  kitId?: true
  role?: true
  team?: true
  _all?: true
}

export type UserAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which User to aggregate.
   */
  where?: Prisma.UserWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Users to fetch.
   */
  orderBy?: Prisma.UserOrderByWithRelationInput | Prisma.UserOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.UserWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Users from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Users.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Users
  **/
  _count?: true | UserCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: UserMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: UserMaxAggregateInputType
}

export type GetUserAggregateType<T extends UserAggregateArgs> = {
      [P in keyof T & keyof AggregateUser]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateUser[P]>
    : Prisma.GetScalarType<T[P], AggregateUser[P]>
}




export type UserGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.UserWhereInput
  orderBy?: Prisma.UserOrderByWithAggregationInput | Prisma.UserOrderByWithAggregationInput[]
  by: Prisma.UserScalarFieldEnum[] | Prisma.UserScalarFieldEnum
  having?: Prisma.UserScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: UserCountAggregateInputType | true
  _min?: UserMinAggregateInputType
  _max?: UserMaxAggregateInputType
}

export type UserGroupByOutputType = {
  id: string
  createdAt: Date
  updatedAt: Date
  email: string
  firstName: string
  discordId: string | null
  kitId: string | null
  role: string
  team: string
  _count: UserCountAggregateOutputType | null
  _min: UserMinAggregateOutputType | null
  _max: UserMaxAggregateOutputType | null
}

export type GetUserGroupByPayload<T extends UserGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<UserGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof UserGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], UserGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], UserGroupByOutputType[P]>
      }
    >
  >



export type UserWhereInput = {
  AND?: Prisma.UserWhereInput | Prisma.UserWhereInput[]
  OR?: Prisma.UserWhereInput[]
  NOT?: Prisma.UserWhereInput | Prisma.UserWhereInput[]
  id?: Prisma.StringFilter<"User"> | string
  createdAt?: Prisma.DateTimeFilter<"User"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"User"> | Date | string
  email?: Prisma.StringFilter<"User"> | string
  firstName?: Prisma.StringFilter<"User"> | string
  discordId?: Prisma.StringNullableFilter<"User"> | string | null
  kitId?: Prisma.StringNullableFilter<"User"> | string | null
  role?: Prisma.StringFilter<"User"> | string
  team?: Prisma.StringFilter<"User"> | string
  password?: Prisma.XOR<Prisma.PasswordNullableScalarRelationFilter, Prisma.PasswordWhereInput> | null
  passkeys?: Prisma.PasskeyListRelationFilter
  calls?: Prisma.CallListRelationFilter
  callKentCallerEpisodes?: Prisma.CallKentCallerEpisodeListRelationFilter
  sessions?: Prisma.SessionListRelationFilter
  postReads?: Prisma.PostReadListRelationFilter
  favorites?: Prisma.FavoriteListRelationFilter
}

export type UserOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  email?: Prisma.SortOrder
  firstName?: Prisma.SortOrder
  discordId?: Prisma.SortOrderInput | Prisma.SortOrder
  kitId?: Prisma.SortOrderInput | Prisma.SortOrder
  role?: Prisma.SortOrder
  team?: Prisma.SortOrder
  password?: Prisma.PasswordOrderByWithRelationInput
  passkeys?: Prisma.PasskeyOrderByRelationAggregateInput
  calls?: Prisma.CallOrderByRelationAggregateInput
  callKentCallerEpisodes?: Prisma.CallKentCallerEpisodeOrderByRelationAggregateInput
  sessions?: Prisma.SessionOrderByRelationAggregateInput
  postReads?: Prisma.PostReadOrderByRelationAggregateInput
  favorites?: Prisma.FavoriteOrderByRelationAggregateInput
}

export type UserWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  email?: string
  AND?: Prisma.UserWhereInput | Prisma.UserWhereInput[]
  OR?: Prisma.UserWhereInput[]
  NOT?: Prisma.UserWhereInput | Prisma.UserWhereInput[]
  createdAt?: Prisma.DateTimeFilter<"User"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"User"> | Date | string
  firstName?: Prisma.StringFilter<"User"> | string
  discordId?: Prisma.StringNullableFilter<"User"> | string | null
  kitId?: Prisma.StringNullableFilter<"User"> | string | null
  role?: Prisma.StringFilter<"User"> | string
  team?: Prisma.StringFilter<"User"> | string
  password?: Prisma.XOR<Prisma.PasswordNullableScalarRelationFilter, Prisma.PasswordWhereInput> | null
  passkeys?: Prisma.PasskeyListRelationFilter
  calls?: Prisma.CallListRelationFilter
  callKentCallerEpisodes?: Prisma.CallKentCallerEpisodeListRelationFilter
  sessions?: Prisma.SessionListRelationFilter
  postReads?: Prisma.PostReadListRelationFilter
  favorites?: Prisma.FavoriteListRelationFilter
}, "id" | "email">

export type UserOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  email?: Prisma.SortOrder
  firstName?: Prisma.SortOrder
  discordId?: Prisma.SortOrderInput | Prisma.SortOrder
  kitId?: Prisma.SortOrderInput | Prisma.SortOrder
  role?: Prisma.SortOrder
  team?: Prisma.SortOrder
  _count?: Prisma.UserCountOrderByAggregateInput
  _max?: Prisma.UserMaxOrderByAggregateInput
  _min?: Prisma.UserMinOrderByAggregateInput
}

export type UserScalarWhereWithAggregatesInput = {
  AND?: Prisma.UserScalarWhereWithAggregatesInput | Prisma.UserScalarWhereWithAggregatesInput[]
  OR?: Prisma.UserScalarWhereWithAggregatesInput[]
  NOT?: Prisma.UserScalarWhereWithAggregatesInput | Prisma.UserScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"User"> | string
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"User"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"User"> | Date | string
  email?: Prisma.StringWithAggregatesFilter<"User"> | string
  firstName?: Prisma.StringWithAggregatesFilter<"User"> | string
  discordId?: Prisma.StringNullableWithAggregatesFilter<"User"> | string | null
  kitId?: Prisma.StringNullableWithAggregatesFilter<"User"> | string | null
  role?: Prisma.StringWithAggregatesFilter<"User"> | string
  team?: Prisma.StringWithAggregatesFilter<"User"> | string
}

export type UserCreateInput = {
  id?: string
  createdAt?: Date | string
  updatedAt?: Date | string
  email: string
  firstName: string
  discordId?: string | null
  kitId?: string | null
  role?: string
  team: string
  password?: Prisma.PasswordCreateNestedOneWithoutUserInput
  passkeys?: Prisma.PasskeyCreateNestedManyWithoutUserInput
  calls?: Prisma.CallCreateNestedManyWithoutUserInput
  callKentCallerEpisodes?: Prisma.CallKentCallerEpisodeCreateNestedManyWithoutUserInput
  sessions?: Prisma.SessionCreateNestedManyWithoutUserInput
  postReads?: Prisma.PostReadCreateNestedManyWithoutUserInput
  favorites?: Prisma.FavoriteCreateNestedManyWithoutUserInput
}

export type UserUncheckedCreateInput = {
  id?: string
  createdAt?: Date | string
  updatedAt?: Date | string
  email: string
  firstName: string
  discordId?: string | null
  kitId?: string | null
  role?: string
  team: string
  password?: Prisma.PasswordUncheckedCreateNestedOneWithoutUserInput
  passkeys?: Prisma.PasskeyUncheckedCreateNestedManyWithoutUserInput
  calls?: Prisma.CallUncheckedCreateNestedManyWithoutUserInput
  callKentCallerEpisodes?: Prisma.CallKentCallerEpisodeUncheckedCreateNestedManyWithoutUserInput
  sessions?: Prisma.SessionUncheckedCreateNestedManyWithoutUserInput
  postReads?: Prisma.PostReadUncheckedCreateNestedManyWithoutUserInput
  favorites?: Prisma.FavoriteUncheckedCreateNestedManyWithoutUserInput
}

export type UserUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  firstName?: Prisma.StringFieldUpdateOperationsInput | string
  discordId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  kitId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  role?: Prisma.StringFieldUpdateOperationsInput | string
  team?: Prisma.StringFieldUpdateOperationsInput | string
  password?: Prisma.PasswordUpdateOneWithoutUserNestedInput
  passkeys?: Prisma.PasskeyUpdateManyWithoutUserNestedInput
  calls?: Prisma.CallUpdateManyWithoutUserNestedInput
  callKentCallerEpisodes?: Prisma.CallKentCallerEpisodeUpdateManyWithoutUserNestedInput
  sessions?: Prisma.SessionUpdateManyWithoutUserNestedInput
  postReads?: Prisma.PostReadUpdateManyWithoutUserNestedInput
  favorites?: Prisma.FavoriteUpdateManyWithoutUserNestedInput
}

export type UserUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  firstName?: Prisma.StringFieldUpdateOperationsInput | string
  discordId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  kitId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  role?: Prisma.StringFieldUpdateOperationsInput | string
  team?: Prisma.StringFieldUpdateOperationsInput | string
  password?: Prisma.PasswordUncheckedUpdateOneWithoutUserNestedInput
  passkeys?: Prisma.PasskeyUncheckedUpdateManyWithoutUserNestedInput
  calls?: Prisma.CallUncheckedUpdateManyWithoutUserNestedInput
  callKentCallerEpisodes?: Prisma.CallKentCallerEpisodeUncheckedUpdateManyWithoutUserNestedInput
  sessions?: Prisma.SessionUncheckedUpdateManyWithoutUserNestedInput
  postReads?: Prisma.PostReadUncheckedUpdateManyWithoutUserNestedInput
  favorites?: Prisma.FavoriteUncheckedUpdateManyWithoutUserNestedInput
}

export type UserCreateManyInput = {
  id?: string
  createdAt?: Date | string
  updatedAt?: Date | string
  email: string
  firstName: string
  discordId?: string | null
  kitId?: string | null
  role?: string
  team: string
}

export type UserUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  firstName?: Prisma.StringFieldUpdateOperationsInput | string
  discordId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  kitId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  role?: Prisma.StringFieldUpdateOperationsInput | string
  team?: Prisma.StringFieldUpdateOperationsInput | string
}

export type UserUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  firstName?: Prisma.StringFieldUpdateOperationsInput | string
  discordId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  kitId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  role?: Prisma.StringFieldUpdateOperationsInput | string
  team?: Prisma.StringFieldUpdateOperationsInput | string
}

export type UserCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  email?: Prisma.SortOrder
  firstName?: Prisma.SortOrder
  discordId?: Prisma.SortOrder
  kitId?: Prisma.SortOrder
  role?: Prisma.SortOrder
  team?: Prisma.SortOrder
}

export type UserMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  email?: Prisma.SortOrder
  firstName?: Prisma.SortOrder
  discordId?: Prisma.SortOrder
  kitId?: Prisma.SortOrder
  role?: Prisma.SortOrder
  team?: Prisma.SortOrder
}

export type UserMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  email?: Prisma.SortOrder
  firstName?: Prisma.SortOrder
  discordId?: Prisma.SortOrder
  kitId?: Prisma.SortOrder
  role?: Prisma.SortOrder
  team?: Prisma.SortOrder
}

export type UserScalarRelationFilter = {
  is?: Prisma.UserWhereInput
  isNot?: Prisma.UserWhereInput
}

export type UserNullableScalarRelationFilter = {
  is?: Prisma.UserWhereInput | null
  isNot?: Prisma.UserWhereInput | null
}

export type StringFieldUpdateOperationsInput = {
  set?: string
}

export type DateTimeFieldUpdateOperationsInput = {
  set?: Date | string
}

export type NullableStringFieldUpdateOperationsInput = {
  set?: string | null
}

export type UserCreateNestedOneWithoutPasswordInput = {
  create?: Prisma.XOR<Prisma.UserCreateWithoutPasswordInput, Prisma.UserUncheckedCreateWithoutPasswordInput>
  connectOrCreate?: Prisma.UserCreateOrConnectWithoutPasswordInput
  connect?: Prisma.UserWhereUniqueInput
}

export type UserUpdateOneRequiredWithoutPasswordNestedInput = {
  create?: Prisma.XOR<Prisma.UserCreateWithoutPasswordInput, Prisma.UserUncheckedCreateWithoutPasswordInput>
  connectOrCreate?: Prisma.UserCreateOrConnectWithoutPasswordInput
  upsert?: Prisma.UserUpsertWithoutPasswordInput
  connect?: Prisma.UserWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.UserUpdateToOneWithWhereWithoutPasswordInput, Prisma.UserUpdateWithoutPasswordInput>, Prisma.UserUncheckedUpdateWithoutPasswordInput>
}

export type UserCreateNestedOneWithoutSessionsInput = {
  create?: Prisma.XOR<Prisma.UserCreateWithoutSessionsInput, Prisma.UserUncheckedCreateWithoutSessionsInput>
  connectOrCreate?: Prisma.UserCreateOrConnectWithoutSessionsInput
  connect?: Prisma.UserWhereUniqueInput
}

export type UserUpdateOneRequiredWithoutSessionsNestedInput = {
  create?: Prisma.XOR<Prisma.UserCreateWithoutSessionsInput, Prisma.UserUncheckedCreateWithoutSessionsInput>
  connectOrCreate?: Prisma.UserCreateOrConnectWithoutSessionsInput
  upsert?: Prisma.UserUpsertWithoutSessionsInput
  connect?: Prisma.UserWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.UserUpdateToOneWithWhereWithoutSessionsInput, Prisma.UserUpdateWithoutSessionsInput>, Prisma.UserUncheckedUpdateWithoutSessionsInput>
}

export type UserCreateNestedOneWithoutCallsInput = {
  create?: Prisma.XOR<Prisma.UserCreateWithoutCallsInput, Prisma.UserUncheckedCreateWithoutCallsInput>
  connectOrCreate?: Prisma.UserCreateOrConnectWithoutCallsInput
  connect?: Prisma.UserWhereUniqueInput
}

export type UserUpdateOneRequiredWithoutCallsNestedInput = {
  create?: Prisma.XOR<Prisma.UserCreateWithoutCallsInput, Prisma.UserUncheckedCreateWithoutCallsInput>
  connectOrCreate?: Prisma.UserCreateOrConnectWithoutCallsInput
  upsert?: Prisma.UserUpsertWithoutCallsInput
  connect?: Prisma.UserWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.UserUpdateToOneWithWhereWithoutCallsInput, Prisma.UserUpdateWithoutCallsInput>, Prisma.UserUncheckedUpdateWithoutCallsInput>
}

export type UserCreateNestedOneWithoutCallKentCallerEpisodesInput = {
  create?: Prisma.XOR<Prisma.UserCreateWithoutCallKentCallerEpisodesInput, Prisma.UserUncheckedCreateWithoutCallKentCallerEpisodesInput>
  connectOrCreate?: Prisma.UserCreateOrConnectWithoutCallKentCallerEpisodesInput
  connect?: Prisma.UserWhereUniqueInput
}

export type UserUpdateOneRequiredWithoutCallKentCallerEpisodesNestedInput = {
  create?: Prisma.XOR<Prisma.UserCreateWithoutCallKentCallerEpisodesInput, Prisma.UserUncheckedCreateWithoutCallKentCallerEpisodesInput>
  connectOrCreate?: Prisma.UserCreateOrConnectWithoutCallKentCallerEpisodesInput
  upsert?: Prisma.UserUpsertWithoutCallKentCallerEpisodesInput
  connect?: Prisma.UserWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.UserUpdateToOneWithWhereWithoutCallKentCallerEpisodesInput, Prisma.UserUpdateWithoutCallKentCallerEpisodesInput>, Prisma.UserUncheckedUpdateWithoutCallKentCallerEpisodesInput>
}

export type UserCreateNestedOneWithoutPostReadsInput = {
  create?: Prisma.XOR<Prisma.UserCreateWithoutPostReadsInput, Prisma.UserUncheckedCreateWithoutPostReadsInput>
  connectOrCreate?: Prisma.UserCreateOrConnectWithoutPostReadsInput
  connect?: Prisma.UserWhereUniqueInput
}

export type UserUpdateOneWithoutPostReadsNestedInput = {
  create?: Prisma.XOR<Prisma.UserCreateWithoutPostReadsInput, Prisma.UserUncheckedCreateWithoutPostReadsInput>
  connectOrCreate?: Prisma.UserCreateOrConnectWithoutPostReadsInput
  upsert?: Prisma.UserUpsertWithoutPostReadsInput
  disconnect?: Prisma.UserWhereInput | boolean
  delete?: Prisma.UserWhereInput | boolean
  connect?: Prisma.UserWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.UserUpdateToOneWithWhereWithoutPostReadsInput, Prisma.UserUpdateWithoutPostReadsInput>, Prisma.UserUncheckedUpdateWithoutPostReadsInput>
}

export type UserCreateNestedOneWithoutPasskeysInput = {
  create?: Prisma.XOR<Prisma.UserCreateWithoutPasskeysInput, Prisma.UserUncheckedCreateWithoutPasskeysInput>
  connectOrCreate?: Prisma.UserCreateOrConnectWithoutPasskeysInput
  connect?: Prisma.UserWhereUniqueInput
}

export type UserUpdateOneRequiredWithoutPasskeysNestedInput = {
  create?: Prisma.XOR<Prisma.UserCreateWithoutPasskeysInput, Prisma.UserUncheckedCreateWithoutPasskeysInput>
  connectOrCreate?: Prisma.UserCreateOrConnectWithoutPasskeysInput
  upsert?: Prisma.UserUpsertWithoutPasskeysInput
  connect?: Prisma.UserWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.UserUpdateToOneWithWhereWithoutPasskeysInput, Prisma.UserUpdateWithoutPasskeysInput>, Prisma.UserUncheckedUpdateWithoutPasskeysInput>
}

export type UserCreateNestedOneWithoutFavoritesInput = {
  create?: Prisma.XOR<Prisma.UserCreateWithoutFavoritesInput, Prisma.UserUncheckedCreateWithoutFavoritesInput>
  connectOrCreate?: Prisma.UserCreateOrConnectWithoutFavoritesInput
  connect?: Prisma.UserWhereUniqueInput
}

export type UserUpdateOneRequiredWithoutFavoritesNestedInput = {
  create?: Prisma.XOR<Prisma.UserCreateWithoutFavoritesInput, Prisma.UserUncheckedCreateWithoutFavoritesInput>
  connectOrCreate?: Prisma.UserCreateOrConnectWithoutFavoritesInput
  upsert?: Prisma.UserUpsertWithoutFavoritesInput
  connect?: Prisma.UserWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.UserUpdateToOneWithWhereWithoutFavoritesInput, Prisma.UserUpdateWithoutFavoritesInput>, Prisma.UserUncheckedUpdateWithoutFavoritesInput>
}

export type UserCreateWithoutPasswordInput = {
  id?: string
  createdAt?: Date | string
  updatedAt?: Date | string
  email: string
  firstName: string
  discordId?: string | null
  kitId?: string | null
  role?: string
  team: string
  passkeys?: Prisma.PasskeyCreateNestedManyWithoutUserInput
  calls?: Prisma.CallCreateNestedManyWithoutUserInput
  callKentCallerEpisodes?: Prisma.CallKentCallerEpisodeCreateNestedManyWithoutUserInput
  sessions?: Prisma.SessionCreateNestedManyWithoutUserInput
  postReads?: Prisma.PostReadCreateNestedManyWithoutUserInput
  favorites?: Prisma.FavoriteCreateNestedManyWithoutUserInput
}

export type UserUncheckedCreateWithoutPasswordInput = {
  id?: string
  createdAt?: Date | string
  updatedAt?: Date | string
  email: string
  firstName: string
  discordId?: string | null
  kitId?: string | null
  role?: string
  team: string
  passkeys?: Prisma.PasskeyUncheckedCreateNestedManyWithoutUserInput
  calls?: Prisma.CallUncheckedCreateNestedManyWithoutUserInput
  callKentCallerEpisodes?: Prisma.CallKentCallerEpisodeUncheckedCreateNestedManyWithoutUserInput
  sessions?: Prisma.SessionUncheckedCreateNestedManyWithoutUserInput
  postReads?: Prisma.PostReadUncheckedCreateNestedManyWithoutUserInput
  favorites?: Prisma.FavoriteUncheckedCreateNestedManyWithoutUserInput
}

export type UserCreateOrConnectWithoutPasswordInput = {
  where: Prisma.UserWhereUniqueInput
  create: Prisma.XOR<Prisma.UserCreateWithoutPasswordInput, Prisma.UserUncheckedCreateWithoutPasswordInput>
}

export type UserUpsertWithoutPasswordInput = {
  update: Prisma.XOR<Prisma.UserUpdateWithoutPasswordInput, Prisma.UserUncheckedUpdateWithoutPasswordInput>
  create: Prisma.XOR<Prisma.UserCreateWithoutPasswordInput, Prisma.UserUncheckedCreateWithoutPasswordInput>
  where?: Prisma.UserWhereInput
}

export type UserUpdateToOneWithWhereWithoutPasswordInput = {
  where?: Prisma.UserWhereInput
  data: Prisma.XOR<Prisma.UserUpdateWithoutPasswordInput, Prisma.UserUncheckedUpdateWithoutPasswordInput>
}

export type UserUpdateWithoutPasswordInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  firstName?: Prisma.StringFieldUpdateOperationsInput | string
  discordId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  kitId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  role?: Prisma.StringFieldUpdateOperationsInput | string
  team?: Prisma.StringFieldUpdateOperationsInput | string
  passkeys?: Prisma.PasskeyUpdateManyWithoutUserNestedInput
  calls?: Prisma.CallUpdateManyWithoutUserNestedInput
  callKentCallerEpisodes?: Prisma.CallKentCallerEpisodeUpdateManyWithoutUserNestedInput
  sessions?: Prisma.SessionUpdateManyWithoutUserNestedInput
  postReads?: Prisma.PostReadUpdateManyWithoutUserNestedInput
  favorites?: Prisma.FavoriteUpdateManyWithoutUserNestedInput
}

export type UserUncheckedUpdateWithoutPasswordInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  firstName?: Prisma.StringFieldUpdateOperationsInput | string
  discordId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  kitId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  role?: Prisma.StringFieldUpdateOperationsInput | string
  team?: Prisma.StringFieldUpdateOperationsInput | string
  passkeys?: Prisma.PasskeyUncheckedUpdateManyWithoutUserNestedInput
  calls?: Prisma.CallUncheckedUpdateManyWithoutUserNestedInput
  callKentCallerEpisodes?: Prisma.CallKentCallerEpisodeUncheckedUpdateManyWithoutUserNestedInput
  sessions?: Prisma.SessionUncheckedUpdateManyWithoutUserNestedInput
  postReads?: Prisma.PostReadUncheckedUpdateManyWithoutUserNestedInput
  favorites?: Prisma.FavoriteUncheckedUpdateManyWithoutUserNestedInput
}

export type UserCreateWithoutSessionsInput = {
  id?: string
  createdAt?: Date | string
  updatedAt?: Date | string
  email: string
  firstName: string
  discordId?: string | null
  kitId?: string | null
  role?: string
  team: string
  password?: Prisma.PasswordCreateNestedOneWithoutUserInput
  passkeys?: Prisma.PasskeyCreateNestedManyWithoutUserInput
  calls?: Prisma.CallCreateNestedManyWithoutUserInput
  callKentCallerEpisodes?: Prisma.CallKentCallerEpisodeCreateNestedManyWithoutUserInput
  postReads?: Prisma.PostReadCreateNestedManyWithoutUserInput
  favorites?: Prisma.FavoriteCreateNestedManyWithoutUserInput
}

export type UserUncheckedCreateWithoutSessionsInput = {
  id?: string
  createdAt?: Date | string
  updatedAt?: Date | string
  email: string
  firstName: string
  discordId?: string | null
  kitId?: string | null
  role?: string
  team: string
  password?: Prisma.PasswordUncheckedCreateNestedOneWithoutUserInput
  passkeys?: Prisma.PasskeyUncheckedCreateNestedManyWithoutUserInput
  calls?: Prisma.CallUncheckedCreateNestedManyWithoutUserInput
  callKentCallerEpisodes?: Prisma.CallKentCallerEpisodeUncheckedCreateNestedManyWithoutUserInput
  postReads?: Prisma.PostReadUncheckedCreateNestedManyWithoutUserInput
  favorites?: Prisma.FavoriteUncheckedCreateNestedManyWithoutUserInput
}

export type UserCreateOrConnectWithoutSessionsInput = {
  where: Prisma.UserWhereUniqueInput
  create: Prisma.XOR<Prisma.UserCreateWithoutSessionsInput, Prisma.UserUncheckedCreateWithoutSessionsInput>
}

export type UserUpsertWithoutSessionsInput = {
  update: Prisma.XOR<Prisma.UserUpdateWithoutSessionsInput, Prisma.UserUncheckedUpdateWithoutSessionsInput>
  create: Prisma.XOR<Prisma.UserCreateWithoutSessionsInput, Prisma.UserUncheckedCreateWithoutSessionsInput>
  where?: Prisma.UserWhereInput
}

export type UserUpdateToOneWithWhereWithoutSessionsInput = {
  where?: Prisma.UserWhereInput
  data: Prisma.XOR<Prisma.UserUpdateWithoutSessionsInput, Prisma.UserUncheckedUpdateWithoutSessionsInput>
}

export type UserUpdateWithoutSessionsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  firstName?: Prisma.StringFieldUpdateOperationsInput | string
  discordId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  kitId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  role?: Prisma.StringFieldUpdateOperationsInput | string
  team?: Prisma.StringFieldUpdateOperationsInput | string
  password?: Prisma.PasswordUpdateOneWithoutUserNestedInput
  passkeys?: Prisma.PasskeyUpdateManyWithoutUserNestedInput
  calls?: Prisma.CallUpdateManyWithoutUserNestedInput
  callKentCallerEpisodes?: Prisma.CallKentCallerEpisodeUpdateManyWithoutUserNestedInput
  postReads?: Prisma.PostReadUpdateManyWithoutUserNestedInput
  favorites?: Prisma.FavoriteUpdateManyWithoutUserNestedInput
}

export type UserUncheckedUpdateWithoutSessionsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  firstName?: Prisma.StringFieldUpdateOperationsInput | string
  discordId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  kitId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  role?: Prisma.StringFieldUpdateOperationsInput | string
  team?: Prisma.StringFieldUpdateOperationsInput | string
  password?: Prisma.PasswordUncheckedUpdateOneWithoutUserNestedInput
  passkeys?: Prisma.PasskeyUncheckedUpdateManyWithoutUserNestedInput
  calls?: Prisma.CallUncheckedUpdateManyWithoutUserNestedInput
  callKentCallerEpisodes?: Prisma.CallKentCallerEpisodeUncheckedUpdateManyWithoutUserNestedInput
  postReads?: Prisma.PostReadUncheckedUpdateManyWithoutUserNestedInput
  favorites?: Prisma.FavoriteUncheckedUpdateManyWithoutUserNestedInput
}

export type UserCreateWithoutCallsInput = {
  id?: string
  createdAt?: Date | string
  updatedAt?: Date | string
  email: string
  firstName: string
  discordId?: string | null
  kitId?: string | null
  role?: string
  team: string
  password?: Prisma.PasswordCreateNestedOneWithoutUserInput
  passkeys?: Prisma.PasskeyCreateNestedManyWithoutUserInput
  callKentCallerEpisodes?: Prisma.CallKentCallerEpisodeCreateNestedManyWithoutUserInput
  sessions?: Prisma.SessionCreateNestedManyWithoutUserInput
  postReads?: Prisma.PostReadCreateNestedManyWithoutUserInput
  favorites?: Prisma.FavoriteCreateNestedManyWithoutUserInput
}

export type UserUncheckedCreateWithoutCallsInput = {
  id?: string
  createdAt?: Date | string
  updatedAt?: Date | string
  email: string
  firstName: string
  discordId?: string | null
  kitId?: string | null
  role?: string
  team: string
  password?: Prisma.PasswordUncheckedCreateNestedOneWithoutUserInput
  passkeys?: Prisma.PasskeyUncheckedCreateNestedManyWithoutUserInput
  callKentCallerEpisodes?: Prisma.CallKentCallerEpisodeUncheckedCreateNestedManyWithoutUserInput
  sessions?: Prisma.SessionUncheckedCreateNestedManyWithoutUserInput
  postReads?: Prisma.PostReadUncheckedCreateNestedManyWithoutUserInput
  favorites?: Prisma.FavoriteUncheckedCreateNestedManyWithoutUserInput
}

export type UserCreateOrConnectWithoutCallsInput = {
  where: Prisma.UserWhereUniqueInput
  create: Prisma.XOR<Prisma.UserCreateWithoutCallsInput, Prisma.UserUncheckedCreateWithoutCallsInput>
}

export type UserUpsertWithoutCallsInput = {
  update: Prisma.XOR<Prisma.UserUpdateWithoutCallsInput, Prisma.UserUncheckedUpdateWithoutCallsInput>
  create: Prisma.XOR<Prisma.UserCreateWithoutCallsInput, Prisma.UserUncheckedCreateWithoutCallsInput>
  where?: Prisma.UserWhereInput
}

export type UserUpdateToOneWithWhereWithoutCallsInput = {
  where?: Prisma.UserWhereInput
  data: Prisma.XOR<Prisma.UserUpdateWithoutCallsInput, Prisma.UserUncheckedUpdateWithoutCallsInput>
}

export type UserUpdateWithoutCallsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  firstName?: Prisma.StringFieldUpdateOperationsInput | string
  discordId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  kitId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  role?: Prisma.StringFieldUpdateOperationsInput | string
  team?: Prisma.StringFieldUpdateOperationsInput | string
  password?: Prisma.PasswordUpdateOneWithoutUserNestedInput
  passkeys?: Prisma.PasskeyUpdateManyWithoutUserNestedInput
  callKentCallerEpisodes?: Prisma.CallKentCallerEpisodeUpdateManyWithoutUserNestedInput
  sessions?: Prisma.SessionUpdateManyWithoutUserNestedInput
  postReads?: Prisma.PostReadUpdateManyWithoutUserNestedInput
  favorites?: Prisma.FavoriteUpdateManyWithoutUserNestedInput
}

export type UserUncheckedUpdateWithoutCallsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  firstName?: Prisma.StringFieldUpdateOperationsInput | string
  discordId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  kitId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  role?: Prisma.StringFieldUpdateOperationsInput | string
  team?: Prisma.StringFieldUpdateOperationsInput | string
  password?: Prisma.PasswordUncheckedUpdateOneWithoutUserNestedInput
  passkeys?: Prisma.PasskeyUncheckedUpdateManyWithoutUserNestedInput
  callKentCallerEpisodes?: Prisma.CallKentCallerEpisodeUncheckedUpdateManyWithoutUserNestedInput
  sessions?: Prisma.SessionUncheckedUpdateManyWithoutUserNestedInput
  postReads?: Prisma.PostReadUncheckedUpdateManyWithoutUserNestedInput
  favorites?: Prisma.FavoriteUncheckedUpdateManyWithoutUserNestedInput
}

export type UserCreateWithoutCallKentCallerEpisodesInput = {
  id?: string
  createdAt?: Date | string
  updatedAt?: Date | string
  email: string
  firstName: string
  discordId?: string | null
  kitId?: string | null
  role?: string
  team: string
  password?: Prisma.PasswordCreateNestedOneWithoutUserInput
  passkeys?: Prisma.PasskeyCreateNestedManyWithoutUserInput
  calls?: Prisma.CallCreateNestedManyWithoutUserInput
  sessions?: Prisma.SessionCreateNestedManyWithoutUserInput
  postReads?: Prisma.PostReadCreateNestedManyWithoutUserInput
  favorites?: Prisma.FavoriteCreateNestedManyWithoutUserInput
}

export type UserUncheckedCreateWithoutCallKentCallerEpisodesInput = {
  id?: string
  createdAt?: Date | string
  updatedAt?: Date | string
  email: string
  firstName: string
  discordId?: string | null
  kitId?: string | null
  role?: string
  team: string
  password?: Prisma.PasswordUncheckedCreateNestedOneWithoutUserInput
  passkeys?: Prisma.PasskeyUncheckedCreateNestedManyWithoutUserInput
  calls?: Prisma.CallUncheckedCreateNestedManyWithoutUserInput
  sessions?: Prisma.SessionUncheckedCreateNestedManyWithoutUserInput
  postReads?: Prisma.PostReadUncheckedCreateNestedManyWithoutUserInput
  favorites?: Prisma.FavoriteUncheckedCreateNestedManyWithoutUserInput
}

export type UserCreateOrConnectWithoutCallKentCallerEpisodesInput = {
  where: Prisma.UserWhereUniqueInput
  create: Prisma.XOR<Prisma.UserCreateWithoutCallKentCallerEpisodesInput, Prisma.UserUncheckedCreateWithoutCallKentCallerEpisodesInput>
}

export type UserUpsertWithoutCallKentCallerEpisodesInput = {
  update: Prisma.XOR<Prisma.UserUpdateWithoutCallKentCallerEpisodesInput, Prisma.UserUncheckedUpdateWithoutCallKentCallerEpisodesInput>
  create: Prisma.XOR<Prisma.UserCreateWithoutCallKentCallerEpisodesInput, Prisma.UserUncheckedCreateWithoutCallKentCallerEpisodesInput>
  where?: Prisma.UserWhereInput
}

export type UserUpdateToOneWithWhereWithoutCallKentCallerEpisodesInput = {
  where?: Prisma.UserWhereInput
  data: Prisma.XOR<Prisma.UserUpdateWithoutCallKentCallerEpisodesInput, Prisma.UserUncheckedUpdateWithoutCallKentCallerEpisodesInput>
}

export type UserUpdateWithoutCallKentCallerEpisodesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  firstName?: Prisma.StringFieldUpdateOperationsInput | string
  discordId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  kitId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  role?: Prisma.StringFieldUpdateOperationsInput | string
  team?: Prisma.StringFieldUpdateOperationsInput | string
  password?: Prisma.PasswordUpdateOneWithoutUserNestedInput
  passkeys?: Prisma.PasskeyUpdateManyWithoutUserNestedInput
  calls?: Prisma.CallUpdateManyWithoutUserNestedInput
  sessions?: Prisma.SessionUpdateManyWithoutUserNestedInput
  postReads?: Prisma.PostReadUpdateManyWithoutUserNestedInput
  favorites?: Prisma.FavoriteUpdateManyWithoutUserNestedInput
}

export type UserUncheckedUpdateWithoutCallKentCallerEpisodesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  firstName?: Prisma.StringFieldUpdateOperationsInput | string
  discordId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  kitId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  role?: Prisma.StringFieldUpdateOperationsInput | string
  team?: Prisma.StringFieldUpdateOperationsInput | string
  password?: Prisma.PasswordUncheckedUpdateOneWithoutUserNestedInput
  passkeys?: Prisma.PasskeyUncheckedUpdateManyWithoutUserNestedInput
  calls?: Prisma.CallUncheckedUpdateManyWithoutUserNestedInput
  sessions?: Prisma.SessionUncheckedUpdateManyWithoutUserNestedInput
  postReads?: Prisma.PostReadUncheckedUpdateManyWithoutUserNestedInput
  favorites?: Prisma.FavoriteUncheckedUpdateManyWithoutUserNestedInput
}

export type UserCreateWithoutPostReadsInput = {
  id?: string
  createdAt?: Date | string
  updatedAt?: Date | string
  email: string
  firstName: string
  discordId?: string | null
  kitId?: string | null
  role?: string
  team: string
  password?: Prisma.PasswordCreateNestedOneWithoutUserInput
  passkeys?: Prisma.PasskeyCreateNestedManyWithoutUserInput
  calls?: Prisma.CallCreateNestedManyWithoutUserInput
  callKentCallerEpisodes?: Prisma.CallKentCallerEpisodeCreateNestedManyWithoutUserInput
  sessions?: Prisma.SessionCreateNestedManyWithoutUserInput
  favorites?: Prisma.FavoriteCreateNestedManyWithoutUserInput
}

export type UserUncheckedCreateWithoutPostReadsInput = {
  id?: string
  createdAt?: Date | string
  updatedAt?: Date | string
  email: string
  firstName: string
  discordId?: string | null
  kitId?: string | null
  role?: string
  team: string
  password?: Prisma.PasswordUncheckedCreateNestedOneWithoutUserInput
  passkeys?: Prisma.PasskeyUncheckedCreateNestedManyWithoutUserInput
  calls?: Prisma.CallUncheckedCreateNestedManyWithoutUserInput
  callKentCallerEpisodes?: Prisma.CallKentCallerEpisodeUncheckedCreateNestedManyWithoutUserInput
  sessions?: Prisma.SessionUncheckedCreateNestedManyWithoutUserInput
  favorites?: Prisma.FavoriteUncheckedCreateNestedManyWithoutUserInput
}

export type UserCreateOrConnectWithoutPostReadsInput = {
  where: Prisma.UserWhereUniqueInput
  create: Prisma.XOR<Prisma.UserCreateWithoutPostReadsInput, Prisma.UserUncheckedCreateWithoutPostReadsInput>
}

export type UserUpsertWithoutPostReadsInput = {
  update: Prisma.XOR<Prisma.UserUpdateWithoutPostReadsInput, Prisma.UserUncheckedUpdateWithoutPostReadsInput>
  create: Prisma.XOR<Prisma.UserCreateWithoutPostReadsInput, Prisma.UserUncheckedCreateWithoutPostReadsInput>
  where?: Prisma.UserWhereInput
}

export type UserUpdateToOneWithWhereWithoutPostReadsInput = {
  where?: Prisma.UserWhereInput
  data: Prisma.XOR<Prisma.UserUpdateWithoutPostReadsInput, Prisma.UserUncheckedUpdateWithoutPostReadsInput>
}

export type UserUpdateWithoutPostReadsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  firstName?: Prisma.StringFieldUpdateOperationsInput | string
  discordId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  kitId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  role?: Prisma.StringFieldUpdateOperationsInput | string
  team?: Prisma.StringFieldUpdateOperationsInput | string
  password?: Prisma.PasswordUpdateOneWithoutUserNestedInput
  passkeys?: Prisma.PasskeyUpdateManyWithoutUserNestedInput
  calls?: Prisma.CallUpdateManyWithoutUserNestedInput
  callKentCallerEpisodes?: Prisma.CallKentCallerEpisodeUpdateManyWithoutUserNestedInput
  sessions?: Prisma.SessionUpdateManyWithoutUserNestedInput
  favorites?: Prisma.FavoriteUpdateManyWithoutUserNestedInput
}

export type UserUncheckedUpdateWithoutPostReadsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  firstName?: Prisma.StringFieldUpdateOperationsInput | string
  discordId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  kitId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  role?: Prisma.StringFieldUpdateOperationsInput | string
  team?: Prisma.StringFieldUpdateOperationsInput | string
  password?: Prisma.PasswordUncheckedUpdateOneWithoutUserNestedInput
  passkeys?: Prisma.PasskeyUncheckedUpdateManyWithoutUserNestedInput
  calls?: Prisma.CallUncheckedUpdateManyWithoutUserNestedInput
  callKentCallerEpisodes?: Prisma.CallKentCallerEpisodeUncheckedUpdateManyWithoutUserNestedInput
  sessions?: Prisma.SessionUncheckedUpdateManyWithoutUserNestedInput
  favorites?: Prisma.FavoriteUncheckedUpdateManyWithoutUserNestedInput
}

export type UserCreateWithoutPasskeysInput = {
  id?: string
  createdAt?: Date | string
  updatedAt?: Date | string
  email: string
  firstName: string
  discordId?: string | null
  kitId?: string | null
  role?: string
  team: string
  password?: Prisma.PasswordCreateNestedOneWithoutUserInput
  calls?: Prisma.CallCreateNestedManyWithoutUserInput
  callKentCallerEpisodes?: Prisma.CallKentCallerEpisodeCreateNestedManyWithoutUserInput
  sessions?: Prisma.SessionCreateNestedManyWithoutUserInput
  postReads?: Prisma.PostReadCreateNestedManyWithoutUserInput
  favorites?: Prisma.FavoriteCreateNestedManyWithoutUserInput
}

export type UserUncheckedCreateWithoutPasskeysInput = {
  id?: string
  createdAt?: Date | string
  updatedAt?: Date | string
  email: string
  firstName: string
  discordId?: string | null
  kitId?: string | null
  role?: string
  team: string
  password?: Prisma.PasswordUncheckedCreateNestedOneWithoutUserInput
  calls?: Prisma.CallUncheckedCreateNestedManyWithoutUserInput
  callKentCallerEpisodes?: Prisma.CallKentCallerEpisodeUncheckedCreateNestedManyWithoutUserInput
  sessions?: Prisma.SessionUncheckedCreateNestedManyWithoutUserInput
  postReads?: Prisma.PostReadUncheckedCreateNestedManyWithoutUserInput
  favorites?: Prisma.FavoriteUncheckedCreateNestedManyWithoutUserInput
}

export type UserCreateOrConnectWithoutPasskeysInput = {
  where: Prisma.UserWhereUniqueInput
  create: Prisma.XOR<Prisma.UserCreateWithoutPasskeysInput, Prisma.UserUncheckedCreateWithoutPasskeysInput>
}

export type UserUpsertWithoutPasskeysInput = {
  update: Prisma.XOR<Prisma.UserUpdateWithoutPasskeysInput, Prisma.UserUncheckedUpdateWithoutPasskeysInput>
  create: Prisma.XOR<Prisma.UserCreateWithoutPasskeysInput, Prisma.UserUncheckedCreateWithoutPasskeysInput>
  where?: Prisma.UserWhereInput
}

export type UserUpdateToOneWithWhereWithoutPasskeysInput = {
  where?: Prisma.UserWhereInput
  data: Prisma.XOR<Prisma.UserUpdateWithoutPasskeysInput, Prisma.UserUncheckedUpdateWithoutPasskeysInput>
}

export type UserUpdateWithoutPasskeysInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  firstName?: Prisma.StringFieldUpdateOperationsInput | string
  discordId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  kitId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  role?: Prisma.StringFieldUpdateOperationsInput | string
  team?: Prisma.StringFieldUpdateOperationsInput | string
  password?: Prisma.PasswordUpdateOneWithoutUserNestedInput
  calls?: Prisma.CallUpdateManyWithoutUserNestedInput
  callKentCallerEpisodes?: Prisma.CallKentCallerEpisodeUpdateManyWithoutUserNestedInput
  sessions?: Prisma.SessionUpdateManyWithoutUserNestedInput
  postReads?: Prisma.PostReadUpdateManyWithoutUserNestedInput
  favorites?: Prisma.FavoriteUpdateManyWithoutUserNestedInput
}

export type UserUncheckedUpdateWithoutPasskeysInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  firstName?: Prisma.StringFieldUpdateOperationsInput | string
  discordId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  kitId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  role?: Prisma.StringFieldUpdateOperationsInput | string
  team?: Prisma.StringFieldUpdateOperationsInput | string
  password?: Prisma.PasswordUncheckedUpdateOneWithoutUserNestedInput
  calls?: Prisma.CallUncheckedUpdateManyWithoutUserNestedInput
  callKentCallerEpisodes?: Prisma.CallKentCallerEpisodeUncheckedUpdateManyWithoutUserNestedInput
  sessions?: Prisma.SessionUncheckedUpdateManyWithoutUserNestedInput
  postReads?: Prisma.PostReadUncheckedUpdateManyWithoutUserNestedInput
  favorites?: Prisma.FavoriteUncheckedUpdateManyWithoutUserNestedInput
}

export type UserCreateWithoutFavoritesInput = {
  id?: string
  createdAt?: Date | string
  updatedAt?: Date | string
  email: string
  firstName: string
  discordId?: string | null
  kitId?: string | null
  role?: string
  team: string
  password?: Prisma.PasswordCreateNestedOneWithoutUserInput
  passkeys?: Prisma.PasskeyCreateNestedManyWithoutUserInput
  calls?: Prisma.CallCreateNestedManyWithoutUserInput
  callKentCallerEpisodes?: Prisma.CallKentCallerEpisodeCreateNestedManyWithoutUserInput
  sessions?: Prisma.SessionCreateNestedManyWithoutUserInput
  postReads?: Prisma.PostReadCreateNestedManyWithoutUserInput
}

export type UserUncheckedCreateWithoutFavoritesInput = {
  id?: string
  createdAt?: Date | string
  updatedAt?: Date | string
  email: string
  firstName: string
  discordId?: string | null
  kitId?: string | null
  role?: string
  team: string
  password?: Prisma.PasswordUncheckedCreateNestedOneWithoutUserInput
  passkeys?: Prisma.PasskeyUncheckedCreateNestedManyWithoutUserInput
  calls?: Prisma.CallUncheckedCreateNestedManyWithoutUserInput
  callKentCallerEpisodes?: Prisma.CallKentCallerEpisodeUncheckedCreateNestedManyWithoutUserInput
  sessions?: Prisma.SessionUncheckedCreateNestedManyWithoutUserInput
  postReads?: Prisma.PostReadUncheckedCreateNestedManyWithoutUserInput
}

export type UserCreateOrConnectWithoutFavoritesInput = {
  where: Prisma.UserWhereUniqueInput
  create: Prisma.XOR<Prisma.UserCreateWithoutFavoritesInput, Prisma.UserUncheckedCreateWithoutFavoritesInput>
}

export type UserUpsertWithoutFavoritesInput = {
  update: Prisma.XOR<Prisma.UserUpdateWithoutFavoritesInput, Prisma.UserUncheckedUpdateWithoutFavoritesInput>
  create: Prisma.XOR<Prisma.UserCreateWithoutFavoritesInput, Prisma.UserUncheckedCreateWithoutFavoritesInput>
  where?: Prisma.UserWhereInput
}

export type UserUpdateToOneWithWhereWithoutFavoritesInput = {
  where?: Prisma.UserWhereInput
  data: Prisma.XOR<Prisma.UserUpdateWithoutFavoritesInput, Prisma.UserUncheckedUpdateWithoutFavoritesInput>
}

export type UserUpdateWithoutFavoritesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  firstName?: Prisma.StringFieldUpdateOperationsInput | string
  discordId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  kitId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  role?: Prisma.StringFieldUpdateOperationsInput | string
  team?: Prisma.StringFieldUpdateOperationsInput | string
  password?: Prisma.PasswordUpdateOneWithoutUserNestedInput
  passkeys?: Prisma.PasskeyUpdateManyWithoutUserNestedInput
  calls?: Prisma.CallUpdateManyWithoutUserNestedInput
  callKentCallerEpisodes?: Prisma.CallKentCallerEpisodeUpdateManyWithoutUserNestedInput
  sessions?: Prisma.SessionUpdateManyWithoutUserNestedInput
  postReads?: Prisma.PostReadUpdateManyWithoutUserNestedInput
}

export type UserUncheckedUpdateWithoutFavoritesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  firstName?: Prisma.StringFieldUpdateOperationsInput | string
  discordId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  kitId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  role?: Prisma.StringFieldUpdateOperationsInput | string
  team?: Prisma.StringFieldUpdateOperationsInput | string
  password?: Prisma.PasswordUncheckedUpdateOneWithoutUserNestedInput
  passkeys?: Prisma.PasskeyUncheckedUpdateManyWithoutUserNestedInput
  calls?: Prisma.CallUncheckedUpdateManyWithoutUserNestedInput
  callKentCallerEpisodes?: Prisma.CallKentCallerEpisodeUncheckedUpdateManyWithoutUserNestedInput
  sessions?: Prisma.SessionUncheckedUpdateManyWithoutUserNestedInput
  postReads?: Prisma.PostReadUncheckedUpdateManyWithoutUserNestedInput
}


/**
 * Count Type UserCountOutputType
 */

export type UserCountOutputType = {
  passkeys: number
  calls: number
  callKentCallerEpisodes: number
  sessions: number
  postReads: number
  favorites: number
}

export type UserCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  passkeys?: boolean | UserCountOutputTypeCountPasskeysArgs
  calls?: boolean | UserCountOutputTypeCountCallsArgs
  callKentCallerEpisodes?: boolean | UserCountOutputTypeCountCallKentCallerEpisodesArgs
  sessions?: boolean | UserCountOutputTypeCountSessionsArgs
  postReads?: boolean | UserCountOutputTypeCountPostReadsArgs
  favorites?: boolean | UserCountOutputTypeCountFavoritesArgs
}

/**
 * UserCountOutputType without action
 */
export type UserCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserCountOutputType
   */
  select?: Prisma.UserCountOutputTypeSelect<ExtArgs> | null
}

/**
 * UserCountOutputType without action
 */
export type UserCountOutputTypeCountPasskeysArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.PasskeyWhereInput
}

/**
 * UserCountOutputType without action
 */
export type UserCountOutputTypeCountCallsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.CallWhereInput
}

/**
 * UserCountOutputType without action
 */
export type UserCountOutputTypeCountCallKentCallerEpisodesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.CallKentCallerEpisodeWhereInput
}

/**
 * UserCountOutputType without action
 */
export type UserCountOutputTypeCountSessionsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.SessionWhereInput
}

/**
 * UserCountOutputType without action
 */
export type UserCountOutputTypeCountPostReadsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.PostReadWhereInput
}

/**
 * UserCountOutputType without action
 */
export type UserCountOutputTypeCountFavoritesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.FavoriteWhereInput
}


export type UserSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  email?: boolean
  firstName?: boolean
  discordId?: boolean
  kitId?: boolean
  role?: boolean
  team?: boolean
  password?: boolean | Prisma.User$passwordArgs<ExtArgs>
  passkeys?: boolean | Prisma.User$passkeysArgs<ExtArgs>
  calls?: boolean | Prisma.User$callsArgs<ExtArgs>
  callKentCallerEpisodes?: boolean | Prisma.User$callKentCallerEpisodesArgs<ExtArgs>
  sessions?: boolean | Prisma.User$sessionsArgs<ExtArgs>
  postReads?: boolean | Prisma.User$postReadsArgs<ExtArgs>
  favorites?: boolean | Prisma.User$favoritesArgs<ExtArgs>
  _count?: boolean | Prisma.UserCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["user"]>

export type UserSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  email?: boolean
  firstName?: boolean
  discordId?: boolean
  kitId?: boolean
  role?: boolean
  team?: boolean
}, ExtArgs["result"]["user"]>

export type UserSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  email?: boolean
  firstName?: boolean
  discordId?: boolean
  kitId?: boolean
  role?: boolean
  team?: boolean
}, ExtArgs["result"]["user"]>

export type UserSelectScalar = {
  id?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  email?: boolean
  firstName?: boolean
  discordId?: boolean
  kitId?: boolean
  role?: boolean
  team?: boolean
}

export type UserOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "createdAt" | "updatedAt" | "email" | "firstName" | "discordId" | "kitId" | "role" | "team", ExtArgs["result"]["user"]>
export type UserInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  password?: boolean | Prisma.User$passwordArgs<ExtArgs>
  passkeys?: boolean | Prisma.User$passkeysArgs<ExtArgs>
  calls?: boolean | Prisma.User$callsArgs<ExtArgs>
  callKentCallerEpisodes?: boolean | Prisma.User$callKentCallerEpisodesArgs<ExtArgs>
  sessions?: boolean | Prisma.User$sessionsArgs<ExtArgs>
  postReads?: boolean | Prisma.User$postReadsArgs<ExtArgs>
  favorites?: boolean | Prisma.User$favoritesArgs<ExtArgs>
  _count?: boolean | Prisma.UserCountOutputTypeDefaultArgs<ExtArgs>
}
export type UserIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}
export type UserIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}

export type $UserPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "User"
  objects: {
    password: Prisma.$PasswordPayload<ExtArgs> | null
    passkeys: Prisma.$PasskeyPayload<ExtArgs>[]
    calls: Prisma.$CallPayload<ExtArgs>[]
    callKentCallerEpisodes: Prisma.$CallKentCallerEpisodePayload<ExtArgs>[]
    sessions: Prisma.$SessionPayload<ExtArgs>[]
    postReads: Prisma.$PostReadPayload<ExtArgs>[]
    favorites: Prisma.$FavoritePayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    createdAt: Date
    updatedAt: Date
    email: string
    firstName: string
    discordId: string | null
    kitId: string | null
    role: string
    team: string
  }, ExtArgs["result"]["user"]>
  composites: {}
}

export type UserGetPayload<S extends boolean | null | undefined | UserDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$UserPayload, S>

export type UserCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<UserFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: UserCountAggregateInputType | true
  }

export interface UserDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['User'], meta: { name: 'User' } }
  /**
   * Find zero or one User that matches the filter.
   * @param {UserFindUniqueArgs} args - Arguments to find a User
   * @example
   * // Get one User
   * const user = await prisma.user.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends UserFindUniqueArgs>(args: Prisma.SelectSubset<T, UserFindUniqueArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one User that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {UserFindUniqueOrThrowArgs} args - Arguments to find a User
   * @example
   * // Get one User
   * const user = await prisma.user.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends UserFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, UserFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first User that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserFindFirstArgs} args - Arguments to find a User
   * @example
   * // Get one User
   * const user = await prisma.user.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends UserFindFirstArgs>(args?: Prisma.SelectSubset<T, UserFindFirstArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first User that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserFindFirstOrThrowArgs} args - Arguments to find a User
   * @example
   * // Get one User
   * const user = await prisma.user.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends UserFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, UserFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Users that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Users
   * const users = await prisma.user.findMany()
   * 
   * // Get first 10 Users
   * const users = await prisma.user.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const userWithIdOnly = await prisma.user.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends UserFindManyArgs>(args?: Prisma.SelectSubset<T, UserFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a User.
   * @param {UserCreateArgs} args - Arguments to create a User.
   * @example
   * // Create one User
   * const User = await prisma.user.create({
   *   data: {
   *     // ... data to create a User
   *   }
   * })
   * 
   */
  create<T extends UserCreateArgs>(args: Prisma.SelectSubset<T, UserCreateArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Users.
   * @param {UserCreateManyArgs} args - Arguments to create many Users.
   * @example
   * // Create many Users
   * const user = await prisma.user.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends UserCreateManyArgs>(args?: Prisma.SelectSubset<T, UserCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Users and returns the data saved in the database.
   * @param {UserCreateManyAndReturnArgs} args - Arguments to create many Users.
   * @example
   * // Create many Users
   * const user = await prisma.user.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Users and only return the `id`
   * const userWithIdOnly = await prisma.user.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends UserCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, UserCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a User.
   * @param {UserDeleteArgs} args - Arguments to delete one User.
   * @example
   * // Delete one User
   * const User = await prisma.user.delete({
   *   where: {
   *     // ... filter to delete one User
   *   }
   * })
   * 
   */
  delete<T extends UserDeleteArgs>(args: Prisma.SelectSubset<T, UserDeleteArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one User.
   * @param {UserUpdateArgs} args - Arguments to update one User.
   * @example
   * // Update one User
   * const user = await prisma.user.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends UserUpdateArgs>(args: Prisma.SelectSubset<T, UserUpdateArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Users.
   * @param {UserDeleteManyArgs} args - Arguments to filter Users to delete.
   * @example
   * // Delete a few Users
   * const { count } = await prisma.user.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends UserDeleteManyArgs>(args?: Prisma.SelectSubset<T, UserDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Users.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Users
   * const user = await prisma.user.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends UserUpdateManyArgs>(args: Prisma.SelectSubset<T, UserUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Users and returns the data updated in the database.
   * @param {UserUpdateManyAndReturnArgs} args - Arguments to update many Users.
   * @example
   * // Update many Users
   * const user = await prisma.user.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Users and only return the `id`
   * const userWithIdOnly = await prisma.user.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends UserUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, UserUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one User.
   * @param {UserUpsertArgs} args - Arguments to update or create a User.
   * @example
   * // Update or create a User
   * const user = await prisma.user.upsert({
   *   create: {
   *     // ... data to create a User
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the User we want to update
   *   }
   * })
   */
  upsert<T extends UserUpsertArgs>(args: Prisma.SelectSubset<T, UserUpsertArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Users.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserCountArgs} args - Arguments to filter Users to count.
   * @example
   * // Count the number of Users
   * const count = await prisma.user.count({
   *   where: {
   *     // ... the filter for the Users we want to count
   *   }
   * })
  **/
  count<T extends UserCountArgs>(
    args?: Prisma.Subset<T, UserCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], UserCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a User.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends UserAggregateArgs>(args: Prisma.Subset<T, UserAggregateArgs>): Prisma.PrismaPromise<GetUserAggregateType<T>>

  /**
   * Group by User.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends UserGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: UserGroupByArgs['orderBy'] }
      : { orderBy?: UserGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, UserGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetUserGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the User model
 */
readonly fields: UserFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for User.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__UserClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  password<T extends Prisma.User$passwordArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.User$passwordArgs<ExtArgs>>): Prisma.Prisma__PasswordClient<runtime.Types.Result.GetResult<Prisma.$PasswordPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  passkeys<T extends Prisma.User$passkeysArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.User$passkeysArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PasskeyPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  calls<T extends Prisma.User$callsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.User$callsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$CallPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  callKentCallerEpisodes<T extends Prisma.User$callKentCallerEpisodesArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.User$callKentCallerEpisodesArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$CallKentCallerEpisodePayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  sessions<T extends Prisma.User$sessionsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.User$sessionsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$SessionPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  postReads<T extends Prisma.User$postReadsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.User$postReadsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PostReadPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  favorites<T extends Prisma.User$favoritesArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.User$favoritesArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$FavoritePayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the User model
 */
export interface UserFieldRefs {
  readonly id: Prisma.FieldRef<"User", 'String'>
  readonly createdAt: Prisma.FieldRef<"User", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"User", 'DateTime'>
  readonly email: Prisma.FieldRef<"User", 'String'>
  readonly firstName: Prisma.FieldRef<"User", 'String'>
  readonly discordId: Prisma.FieldRef<"User", 'String'>
  readonly kitId: Prisma.FieldRef<"User", 'String'>
  readonly role: Prisma.FieldRef<"User", 'String'>
  readonly team: Prisma.FieldRef<"User", 'String'>
}
    

// Custom InputTypes
/**
 * User findUnique
 */
export type UserFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the User
   */
  select?: Prisma.UserSelect<ExtArgs> | null
  /**
   * Omit specific fields from the User
   */
  omit?: Prisma.UserOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserInclude<ExtArgs> | null
  /**
   * Filter, which User to fetch.
   */
  where: Prisma.UserWhereUniqueInput
}

/**
 * User findUniqueOrThrow
 */
export type UserFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the User
   */
  select?: Prisma.UserSelect<ExtArgs> | null
  /**
   * Omit specific fields from the User
   */
  omit?: Prisma.UserOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserInclude<ExtArgs> | null
  /**
   * Filter, which User to fetch.
   */
  where: Prisma.UserWhereUniqueInput
}

/**
 * User findFirst
 */
export type UserFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the User
   */
  select?: Prisma.UserSelect<ExtArgs> | null
  /**
   * Omit specific fields from the User
   */
  omit?: Prisma.UserOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserInclude<ExtArgs> | null
  /**
   * Filter, which User to fetch.
   */
  where?: Prisma.UserWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Users to fetch.
   */
  orderBy?: Prisma.UserOrderByWithRelationInput | Prisma.UserOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Users.
   */
  cursor?: Prisma.UserWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Users from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Users.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Users.
   */
  distinct?: Prisma.UserScalarFieldEnum | Prisma.UserScalarFieldEnum[]
}

/**
 * User findFirstOrThrow
 */
export type UserFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the User
   */
  select?: Prisma.UserSelect<ExtArgs> | null
  /**
   * Omit specific fields from the User
   */
  omit?: Prisma.UserOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserInclude<ExtArgs> | null
  /**
   * Filter, which User to fetch.
   */
  where?: Prisma.UserWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Users to fetch.
   */
  orderBy?: Prisma.UserOrderByWithRelationInput | Prisma.UserOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Users.
   */
  cursor?: Prisma.UserWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Users from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Users.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Users.
   */
  distinct?: Prisma.UserScalarFieldEnum | Prisma.UserScalarFieldEnum[]
}

/**
 * User findMany
 */
export type UserFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the User
   */
  select?: Prisma.UserSelect<ExtArgs> | null
  /**
   * Omit specific fields from the User
   */
  omit?: Prisma.UserOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserInclude<ExtArgs> | null
  /**
   * Filter, which Users to fetch.
   */
  where?: Prisma.UserWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Users to fetch.
   */
  orderBy?: Prisma.UserOrderByWithRelationInput | Prisma.UserOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Users.
   */
  cursor?: Prisma.UserWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Users from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Users.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Users.
   */
  distinct?: Prisma.UserScalarFieldEnum | Prisma.UserScalarFieldEnum[]
}

/**
 * User create
 */
export type UserCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the User
   */
  select?: Prisma.UserSelect<ExtArgs> | null
  /**
   * Omit specific fields from the User
   */
  omit?: Prisma.UserOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserInclude<ExtArgs> | null
  /**
   * The data needed to create a User.
   */
  data: Prisma.XOR<Prisma.UserCreateInput, Prisma.UserUncheckedCreateInput>
}

/**
 * User createMany
 */
export type UserCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Users.
   */
  data: Prisma.UserCreateManyInput | Prisma.UserCreateManyInput[]
}

/**
 * User createManyAndReturn
 */
export type UserCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the User
   */
  select?: Prisma.UserSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the User
   */
  omit?: Prisma.UserOmit<ExtArgs> | null
  /**
   * The data used to create many Users.
   */
  data: Prisma.UserCreateManyInput | Prisma.UserCreateManyInput[]
}

/**
 * User update
 */
export type UserUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the User
   */
  select?: Prisma.UserSelect<ExtArgs> | null
  /**
   * Omit specific fields from the User
   */
  omit?: Prisma.UserOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserInclude<ExtArgs> | null
  /**
   * The data needed to update a User.
   */
  data: Prisma.XOR<Prisma.UserUpdateInput, Prisma.UserUncheckedUpdateInput>
  /**
   * Choose, which User to update.
   */
  where: Prisma.UserWhereUniqueInput
}

/**
 * User updateMany
 */
export type UserUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Users.
   */
  data: Prisma.XOR<Prisma.UserUpdateManyMutationInput, Prisma.UserUncheckedUpdateManyInput>
  /**
   * Filter which Users to update
   */
  where?: Prisma.UserWhereInput
  /**
   * Limit how many Users to update.
   */
  limit?: number
}

/**
 * User updateManyAndReturn
 */
export type UserUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the User
   */
  select?: Prisma.UserSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the User
   */
  omit?: Prisma.UserOmit<ExtArgs> | null
  /**
   * The data used to update Users.
   */
  data: Prisma.XOR<Prisma.UserUpdateManyMutationInput, Prisma.UserUncheckedUpdateManyInput>
  /**
   * Filter which Users to update
   */
  where?: Prisma.UserWhereInput
  /**
   * Limit how many Users to update.
   */
  limit?: number
}

/**
 * User upsert
 */
export type UserUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the User
   */
  select?: Prisma.UserSelect<ExtArgs> | null
  /**
   * Omit specific fields from the User
   */
  omit?: Prisma.UserOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserInclude<ExtArgs> | null
  /**
   * The filter to search for the User to update in case it exists.
   */
  where: Prisma.UserWhereUniqueInput
  /**
   * In case the User found by the `where` argument doesn't exist, create a new User with this data.
   */
  create: Prisma.XOR<Prisma.UserCreateInput, Prisma.UserUncheckedCreateInput>
  /**
   * In case the User was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.UserUpdateInput, Prisma.UserUncheckedUpdateInput>
}

/**
 * User delete
 */
export type UserDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the User
   */
  select?: Prisma.UserSelect<ExtArgs> | null
  /**
   * Omit specific fields from the User
   */
  omit?: Prisma.UserOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserInclude<ExtArgs> | null
  /**
   * Filter which User to delete.
   */
  where: Prisma.UserWhereUniqueInput
}

/**
 * User deleteMany
 */
export type UserDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Users to delete
   */
  where?: Prisma.UserWhereInput
  /**
   * Limit how many Users to delete.
   */
  limit?: number
}

/**
 * User.password
 */
export type User$passwordArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Password
   */
  select?: Prisma.PasswordSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Password
   */
  omit?: Prisma.PasswordOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PasswordInclude<ExtArgs> | null
  where?: Prisma.PasswordWhereInput
}

/**
 * User.passkeys
 */
export type User$passkeysArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Passkey
   */
  select?: Prisma.PasskeySelect<ExtArgs> | null
  /**
   * Omit specific fields from the Passkey
   */
  omit?: Prisma.PasskeyOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PasskeyInclude<ExtArgs> | null
  where?: Prisma.PasskeyWhereInput
  orderBy?: Prisma.PasskeyOrderByWithRelationInput | Prisma.PasskeyOrderByWithRelationInput[]
  cursor?: Prisma.PasskeyWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.PasskeyScalarFieldEnum | Prisma.PasskeyScalarFieldEnum[]
}

/**
 * User.calls
 */
export type User$callsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Call
   */
  select?: Prisma.CallSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Call
   */
  omit?: Prisma.CallOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CallInclude<ExtArgs> | null
  where?: Prisma.CallWhereInput
  orderBy?: Prisma.CallOrderByWithRelationInput | Prisma.CallOrderByWithRelationInput[]
  cursor?: Prisma.CallWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.CallScalarFieldEnum | Prisma.CallScalarFieldEnum[]
}

/**
 * User.callKentCallerEpisodes
 */
export type User$callKentCallerEpisodesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CallKentCallerEpisode
   */
  select?: Prisma.CallKentCallerEpisodeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CallKentCallerEpisode
   */
  omit?: Prisma.CallKentCallerEpisodeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CallKentCallerEpisodeInclude<ExtArgs> | null
  where?: Prisma.CallKentCallerEpisodeWhereInput
  orderBy?: Prisma.CallKentCallerEpisodeOrderByWithRelationInput | Prisma.CallKentCallerEpisodeOrderByWithRelationInput[]
  cursor?: Prisma.CallKentCallerEpisodeWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.CallKentCallerEpisodeScalarFieldEnum | Prisma.CallKentCallerEpisodeScalarFieldEnum[]
}

/**
 * User.sessions
 */
export type User$sessionsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Session
   */
  select?: Prisma.SessionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Session
   */
  omit?: Prisma.SessionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SessionInclude<ExtArgs> | null
  where?: Prisma.SessionWhereInput
  orderBy?: Prisma.SessionOrderByWithRelationInput | Prisma.SessionOrderByWithRelationInput[]
  cursor?: Prisma.SessionWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.SessionScalarFieldEnum | Prisma.SessionScalarFieldEnum[]
}

/**
 * User.postReads
 */
export type User$postReadsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PostRead
   */
  select?: Prisma.PostReadSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PostRead
   */
  omit?: Prisma.PostReadOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PostReadInclude<ExtArgs> | null
  where?: Prisma.PostReadWhereInput
  orderBy?: Prisma.PostReadOrderByWithRelationInput | Prisma.PostReadOrderByWithRelationInput[]
  cursor?: Prisma.PostReadWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.PostReadScalarFieldEnum | Prisma.PostReadScalarFieldEnum[]
}

/**
 * User.favorites
 */
export type User$favoritesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Favorite
   */
  select?: Prisma.FavoriteSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Favorite
   */
  omit?: Prisma.FavoriteOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FavoriteInclude<ExtArgs> | null
  where?: Prisma.FavoriteWhereInput
  orderBy?: Prisma.FavoriteOrderByWithRelationInput | Prisma.FavoriteOrderByWithRelationInput[]
  cursor?: Prisma.FavoriteWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.FavoriteScalarFieldEnum | Prisma.FavoriteScalarFieldEnum[]
}

/**
 * User without action
 */
export type UserDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the User
   */
  select?: Prisma.UserSelect<ExtArgs> | null
  /**
   * Omit specific fields from the User
   */
  omit?: Prisma.UserOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserInclude<ExtArgs> | null
}
