
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file should be your main import to use Prisma-related types and utilities in a browser. 
 * Use it to get access to models, enums, and input types.
 * 
 * This file does not contain a `PrismaClient` class, nor several other helpers that are intended as server-side only.
 * See `client.ts` for the standard, server-side entry point.
 *
 * 🟢 You can import this file directly.
 */

import * as Prisma from './internal/prismaNamespaceBrowser.ts'
export { Prisma }
export * as $Enums from './enums.ts'
export * from './enums.ts';
/**
 * Model User
 * 
 */
export type User = Prisma.UserModel
/**
 * Model Password
 * 
 */
export type Password = Prisma.PasswordModel
/**
 * Model Verification
 * 
 */
export type Verification = Prisma.VerificationModel
/**
 * Model Session
 * 
 */
export type Session = Prisma.SessionModel
/**
 * Model Call
 * 
 */
export type Call = Prisma.CallModel
/**
 * Model CallKentEpisodeDraft
 * 
 */
export type CallKentEpisodeDraft = Prisma.CallKentEpisodeDraftModel
/**
 * Model CallKentCallerEpisode
 * 
 */
export type CallKentCallerEpisode = Prisma.CallKentCallerEpisodeModel
/**
 * Model PostRead
 * 
 */
export type PostRead = Prisma.PostReadModel
/**
 * Model Passkey
 * 
 */
export type Passkey = Prisma.PasskeyModel
/**
 * Model Favorite
 * 
 */
export type Favorite = Prisma.FavoriteModel
