
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports various common sort, input & filter types that are not directly linked to a particular model.
 *
 * 🟢 You can import this file directly.
 */

import type * as runtime from "@prisma/client/runtime/client"
import * as $Enums from "./enums.ts"
import type * as Prisma from "./internal/prismaNamespace.ts"


export type StringFilter<$PrismaModel = never> = {
  equals?: string | Prisma.StringFieldRefInput<$PrismaModel>
  in?: string[]
  notIn?: string[]
  lt?: string | Prisma.StringFieldRefInput<$PrismaModel>
  lte?: string | Prisma.StringFieldRefInput<$PrismaModel>
  gt?: string | Prisma.StringFieldRefInput<$PrismaModel>
  gte?: string | Prisma.StringFieldRefInput<$PrismaModel>
  contains?: string | Prisma.StringFieldRefInput<$PrismaModel>
  startsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>
  endsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>
  not?: Prisma.NestedStringFilter<$PrismaModel> | string
}

export type DateTimeFilter<$PrismaModel = never> = {
  equals?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  in?: Date[] | string[]
  notIn?: Date[] | string[]
  lt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  lte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  gt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  gte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  not?: Prisma.NestedDateTimeFilter<$PrismaModel> | Date | string
}

export type StringNullableFilter<$PrismaModel = never> = {
  equals?: string | Prisma.StringFieldRefInput<$PrismaModel> | null
  in?: string[] | null
  notIn?: string[] | null
  lt?: string | Prisma.StringFieldRefInput<$PrismaModel>
  lte?: string | Prisma.StringFieldRefInput<$PrismaModel>
  gt?: string | Prisma.StringFieldRefInput<$PrismaModel>
  gte?: string | Prisma.StringFieldRefInput<$PrismaModel>
  contains?: string | Prisma.StringFieldRefInput<$PrismaModel>
  startsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>
  endsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>
  not?: Prisma.NestedStringNullableFilter<$PrismaModel> | string | null
}

export type SortOrderInput = {
  sort: Prisma.SortOrder
  nulls?: Prisma.NullsOrder
}

export type StringWithAggregatesFilter<$PrismaModel = never> = {
  equals?: string | Prisma.StringFieldRefInput<$PrismaModel>
  in?: string[]
  notIn?: string[]
  lt?: string | Prisma.StringFieldRefInput<$PrismaModel>
  lte?: string | Prisma.StringFieldRefInput<$PrismaModel>
  gt?: string | Prisma.StringFieldRefInput<$PrismaModel>
  gte?: string | Prisma.StringFieldRefInput<$PrismaModel>
  contains?: string | Prisma.StringFieldRefInput<$PrismaModel>
  startsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>
  endsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>
  not?: Prisma.NestedStringWithAggregatesFilter<$PrismaModel> | string
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedStringFilter<$PrismaModel>
  _max?: Prisma.NestedStringFilter<$PrismaModel>
}

export type DateTimeWithAggregatesFilter<$PrismaModel = never> = {
  equals?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  in?: Date[] | string[]
  notIn?: Date[] | string[]
  lt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  lte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  gt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  gte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  not?: Prisma.NestedDateTimeWithAggregatesFilter<$PrismaModel> | Date | string
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedDateTimeFilter<$PrismaModel>
  _max?: Prisma.NestedDateTimeFilter<$PrismaModel>
}

export type StringNullableWithAggregatesFilter<$PrismaModel = never> = {
  equals?: string | Prisma.StringFieldRefInput<$PrismaModel> | null
  in?: string[] | null
  notIn?: string[] | null
  lt?: string | Prisma.StringFieldRefInput<$PrismaModel>
  lte?: string | Prisma.StringFieldRefInput<$PrismaModel>
  gt?: string | Prisma.StringFieldRefInput<$PrismaModel>
  gte?: string | Prisma.StringFieldRefInput<$PrismaModel>
  contains?: string | Prisma.StringFieldRefInput<$PrismaModel>
  startsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>
  endsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>
  not?: Prisma.NestedStringNullableWithAggregatesFilter<$PrismaModel> | string | null
  _count?: Prisma.NestedIntNullableFilter<$PrismaModel>
  _min?: Prisma.NestedStringNullableFilter<$PrismaModel>
  _max?: Prisma.NestedStringNullableFilter<$PrismaModel>
}

export type BoolFilter<$PrismaModel = never> = {
  equals?: boolean | Prisma.BooleanFieldRefInput<$PrismaModel>
  not?: Prisma.NestedBoolFilter<$PrismaModel> | boolean
}

export type EnumCallTranscriptStatusFilter<$PrismaModel = never> = {
  equals?: $Enums.CallTranscriptStatus | Prisma.EnumCallTranscriptStatusFieldRefInput<$PrismaModel>
  in?: $Enums.CallTranscriptStatus[]
  notIn?: $Enums.CallTranscriptStatus[]
  not?: Prisma.NestedEnumCallTranscriptStatusFilter<$PrismaModel> | $Enums.CallTranscriptStatus
}

export type IntNullableFilter<$PrismaModel = never> = {
  equals?: number | Prisma.IntFieldRefInput<$PrismaModel> | null
  in?: number[] | null
  notIn?: number[] | null
  lt?: number | Prisma.IntFieldRefInput<$PrismaModel>
  lte?: number | Prisma.IntFieldRefInput<$PrismaModel>
  gt?: number | Prisma.IntFieldRefInput<$PrismaModel>
  gte?: number | Prisma.IntFieldRefInput<$PrismaModel>
  not?: Prisma.NestedIntNullableFilter<$PrismaModel> | number | null
}

export type BoolWithAggregatesFilter<$PrismaModel = never> = {
  equals?: boolean | Prisma.BooleanFieldRefInput<$PrismaModel>
  not?: Prisma.NestedBoolWithAggregatesFilter<$PrismaModel> | boolean
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedBoolFilter<$PrismaModel>
  _max?: Prisma.NestedBoolFilter<$PrismaModel>
}

export type EnumCallTranscriptStatusWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.CallTranscriptStatus | Prisma.EnumCallTranscriptStatusFieldRefInput<$PrismaModel>
  in?: $Enums.CallTranscriptStatus[]
  notIn?: $Enums.CallTranscriptStatus[]
  not?: Prisma.NestedEnumCallTranscriptStatusWithAggregatesFilter<$PrismaModel> | $Enums.CallTranscriptStatus
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumCallTranscriptStatusFilter<$PrismaModel>
  _max?: Prisma.NestedEnumCallTranscriptStatusFilter<$PrismaModel>
}

export type IntNullableWithAggregatesFilter<$PrismaModel = never> = {
  equals?: number | Prisma.IntFieldRefInput<$PrismaModel> | null
  in?: number[] | null
  notIn?: number[] | null
  lt?: number | Prisma.IntFieldRefInput<$PrismaModel>
  lte?: number | Prisma.IntFieldRefInput<$PrismaModel>
  gt?: number | Prisma.IntFieldRefInput<$PrismaModel>
  gte?: number | Prisma.IntFieldRefInput<$PrismaModel>
  not?: Prisma.NestedIntNullableWithAggregatesFilter<$PrismaModel> | number | null
  _count?: Prisma.NestedIntNullableFilter<$PrismaModel>
  _avg?: Prisma.NestedFloatNullableFilter<$PrismaModel>
  _sum?: Prisma.NestedIntNullableFilter<$PrismaModel>
  _min?: Prisma.NestedIntNullableFilter<$PrismaModel>
  _max?: Prisma.NestedIntNullableFilter<$PrismaModel>
}

export type EnumCallKentEpisodeDraftStatusFilter<$PrismaModel = never> = {
  equals?: $Enums.CallKentEpisodeDraftStatus | Prisma.EnumCallKentEpisodeDraftStatusFieldRefInput<$PrismaModel>
  in?: $Enums.CallKentEpisodeDraftStatus[]
  notIn?: $Enums.CallKentEpisodeDraftStatus[]
  not?: Prisma.NestedEnumCallKentEpisodeDraftStatusFilter<$PrismaModel> | $Enums.CallKentEpisodeDraftStatus
}

export type EnumCallKentEpisodeDraftStepFilter<$PrismaModel = never> = {
  equals?: $Enums.CallKentEpisodeDraftStep | Prisma.EnumCallKentEpisodeDraftStepFieldRefInput<$PrismaModel>
  in?: $Enums.CallKentEpisodeDraftStep[]
  notIn?: $Enums.CallKentEpisodeDraftStep[]
  not?: Prisma.NestedEnumCallKentEpisodeDraftStepFilter<$PrismaModel> | $Enums.CallKentEpisodeDraftStep
}

export type EnumCallKentEpisodeDraftStatusWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.CallKentEpisodeDraftStatus | Prisma.EnumCallKentEpisodeDraftStatusFieldRefInput<$PrismaModel>
  in?: $Enums.CallKentEpisodeDraftStatus[]
  notIn?: $Enums.CallKentEpisodeDraftStatus[]
  not?: Prisma.NestedEnumCallKentEpisodeDraftStatusWithAggregatesFilter<$PrismaModel> | $Enums.CallKentEpisodeDraftStatus
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumCallKentEpisodeDraftStatusFilter<$PrismaModel>
  _max?: Prisma.NestedEnumCallKentEpisodeDraftStatusFilter<$PrismaModel>
}

export type EnumCallKentEpisodeDraftStepWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.CallKentEpisodeDraftStep | Prisma.EnumCallKentEpisodeDraftStepFieldRefInput<$PrismaModel>
  in?: $Enums.CallKentEpisodeDraftStep[]
  notIn?: $Enums.CallKentEpisodeDraftStep[]
  not?: Prisma.NestedEnumCallKentEpisodeDraftStepWithAggregatesFilter<$PrismaModel> | $Enums.CallKentEpisodeDraftStep
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumCallKentEpisodeDraftStepFilter<$PrismaModel>
  _max?: Prisma.NestedEnumCallKentEpisodeDraftStepFilter<$PrismaModel>
}

export type BytesFilter<$PrismaModel = never> = {
  equals?: runtime.Bytes | Prisma.BytesFieldRefInput<$PrismaModel>
  in?: runtime.Bytes[]
  notIn?: runtime.Bytes[]
  not?: Prisma.NestedBytesFilter<$PrismaModel> | runtime.Bytes
}

export type BigIntFilter<$PrismaModel = never> = {
  equals?: bigint | number | Prisma.BigIntFieldRefInput<$PrismaModel>
  in?: bigint[] | number[]
  notIn?: bigint[] | number[]
  lt?: bigint | number | Prisma.BigIntFieldRefInput<$PrismaModel>
  lte?: bigint | number | Prisma.BigIntFieldRefInput<$PrismaModel>
  gt?: bigint | number | Prisma.BigIntFieldRefInput<$PrismaModel>
  gte?: bigint | number | Prisma.BigIntFieldRefInput<$PrismaModel>
  not?: Prisma.NestedBigIntFilter<$PrismaModel> | bigint | number
}

export type BytesWithAggregatesFilter<$PrismaModel = never> = {
  equals?: runtime.Bytes | Prisma.BytesFieldRefInput<$PrismaModel>
  in?: runtime.Bytes[]
  notIn?: runtime.Bytes[]
  not?: Prisma.NestedBytesWithAggregatesFilter<$PrismaModel> | runtime.Bytes
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedBytesFilter<$PrismaModel>
  _max?: Prisma.NestedBytesFilter<$PrismaModel>
}

export type BigIntWithAggregatesFilter<$PrismaModel = never> = {
  equals?: bigint | number | Prisma.BigIntFieldRefInput<$PrismaModel>
  in?: bigint[] | number[]
  notIn?: bigint[] | number[]
  lt?: bigint | number | Prisma.BigIntFieldRefInput<$PrismaModel>
  lte?: bigint | number | Prisma.BigIntFieldRefInput<$PrismaModel>
  gt?: bigint | number | Prisma.BigIntFieldRefInput<$PrismaModel>
  gte?: bigint | number | Prisma.BigIntFieldRefInput<$PrismaModel>
  not?: Prisma.NestedBigIntWithAggregatesFilter<$PrismaModel> | bigint | number
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _avg?: Prisma.NestedFloatFilter<$PrismaModel>
  _sum?: Prisma.NestedBigIntFilter<$PrismaModel>
  _min?: Prisma.NestedBigIntFilter<$PrismaModel>
  _max?: Prisma.NestedBigIntFilter<$PrismaModel>
}

export type NestedStringFilter<$PrismaModel = never> = {
  equals?: string | Prisma.StringFieldRefInput<$PrismaModel>
  in?: string[]
  notIn?: string[]
  lt?: string | Prisma.StringFieldRefInput<$PrismaModel>
  lte?: string | Prisma.StringFieldRefInput<$PrismaModel>
  gt?: string | Prisma.StringFieldRefInput<$PrismaModel>
  gte?: string | Prisma.StringFieldRefInput<$PrismaModel>
  contains?: string | Prisma.StringFieldRefInput<$PrismaModel>
  startsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>
  endsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>
  not?: Prisma.NestedStringFilter<$PrismaModel> | string
}

export type NestedDateTimeFilter<$PrismaModel = never> = {
  equals?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  in?: Date[] | string[]
  notIn?: Date[] | string[]
  lt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  lte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  gt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  gte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  not?: Prisma.NestedDateTimeFilter<$PrismaModel> | Date | string
}

export type NestedStringNullableFilter<$PrismaModel = never> = {
  equals?: string | Prisma.StringFieldRefInput<$PrismaModel> | null
  in?: string[] | null
  notIn?: string[] | null
  lt?: string | Prisma.StringFieldRefInput<$PrismaModel>
  lte?: string | Prisma.StringFieldRefInput<$PrismaModel>
  gt?: string | Prisma.StringFieldRefInput<$PrismaModel>
  gte?: string | Prisma.StringFieldRefInput<$PrismaModel>
  contains?: string | Prisma.StringFieldRefInput<$PrismaModel>
  startsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>
  endsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>
  not?: Prisma.NestedStringNullableFilter<$PrismaModel> | string | null
}

export type NestedStringWithAggregatesFilter<$PrismaModel = never> = {
  equals?: string | Prisma.StringFieldRefInput<$PrismaModel>
  in?: string[]
  notIn?: string[]
  lt?: string | Prisma.StringFieldRefInput<$PrismaModel>
  lte?: string | Prisma.StringFieldRefInput<$PrismaModel>
  gt?: string | Prisma.StringFieldRefInput<$PrismaModel>
  gte?: string | Prisma.StringFieldRefInput<$PrismaModel>
  contains?: string | Prisma.StringFieldRefInput<$PrismaModel>
  startsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>
  endsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>
  not?: Prisma.NestedStringWithAggregatesFilter<$PrismaModel> | string
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedStringFilter<$PrismaModel>
  _max?: Prisma.NestedStringFilter<$PrismaModel>
}

export type NestedIntFilter<$PrismaModel = never> = {
  equals?: number | Prisma.IntFieldRefInput<$PrismaModel>
  in?: number[]
  notIn?: number[]
  lt?: number | Prisma.IntFieldRefInput<$PrismaModel>
  lte?: number | Prisma.IntFieldRefInput<$PrismaModel>
  gt?: number | Prisma.IntFieldRefInput<$PrismaModel>
  gte?: number | Prisma.IntFieldRefInput<$PrismaModel>
  not?: Prisma.NestedIntFilter<$PrismaModel> | number
}

export type NestedDateTimeWithAggregatesFilter<$PrismaModel = never> = {
  equals?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  in?: Date[] | string[]
  notIn?: Date[] | string[]
  lt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  lte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  gt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  gte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  not?: Prisma.NestedDateTimeWithAggregatesFilter<$PrismaModel> | Date | string
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedDateTimeFilter<$PrismaModel>
  _max?: Prisma.NestedDateTimeFilter<$PrismaModel>
}

export type NestedStringNullableWithAggregatesFilter<$PrismaModel = never> = {
  equals?: string | Prisma.StringFieldRefInput<$PrismaModel> | null
  in?: string[] | null
  notIn?: string[] | null
  lt?: string | Prisma.StringFieldRefInput<$PrismaModel>
  lte?: string | Prisma.StringFieldRefInput<$PrismaModel>
  gt?: string | Prisma.StringFieldRefInput<$PrismaModel>
  gte?: string | Prisma.StringFieldRefInput<$PrismaModel>
  contains?: string | Prisma.StringFieldRefInput<$PrismaModel>
  startsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>
  endsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>
  not?: Prisma.NestedStringNullableWithAggregatesFilter<$PrismaModel> | string | null
  _count?: Prisma.NestedIntNullableFilter<$PrismaModel>
  _min?: Prisma.NestedStringNullableFilter<$PrismaModel>
  _max?: Prisma.NestedStringNullableFilter<$PrismaModel>
}

export type NestedIntNullableFilter<$PrismaModel = never> = {
  equals?: number | Prisma.IntFieldRefInput<$PrismaModel> | null
  in?: number[] | null
  notIn?: number[] | null
  lt?: number | Prisma.IntFieldRefInput<$PrismaModel>
  lte?: number | Prisma.IntFieldRefInput<$PrismaModel>
  gt?: number | Prisma.IntFieldRefInput<$PrismaModel>
  gte?: number | Prisma.IntFieldRefInput<$PrismaModel>
  not?: Prisma.NestedIntNullableFilter<$PrismaModel> | number | null
}

export type NestedBoolFilter<$PrismaModel = never> = {
  equals?: boolean | Prisma.BooleanFieldRefInput<$PrismaModel>
  not?: Prisma.NestedBoolFilter<$PrismaModel> | boolean
}

export type NestedEnumCallTranscriptStatusFilter<$PrismaModel = never> = {
  equals?: $Enums.CallTranscriptStatus | Prisma.EnumCallTranscriptStatusFieldRefInput<$PrismaModel>
  in?: $Enums.CallTranscriptStatus[]
  notIn?: $Enums.CallTranscriptStatus[]
  not?: Prisma.NestedEnumCallTranscriptStatusFilter<$PrismaModel> | $Enums.CallTranscriptStatus
}

export type NestedBoolWithAggregatesFilter<$PrismaModel = never> = {
  equals?: boolean | Prisma.BooleanFieldRefInput<$PrismaModel>
  not?: Prisma.NestedBoolWithAggregatesFilter<$PrismaModel> | boolean
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedBoolFilter<$PrismaModel>
  _max?: Prisma.NestedBoolFilter<$PrismaModel>
}

export type NestedEnumCallTranscriptStatusWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.CallTranscriptStatus | Prisma.EnumCallTranscriptStatusFieldRefInput<$PrismaModel>
  in?: $Enums.CallTranscriptStatus[]
  notIn?: $Enums.CallTranscriptStatus[]
  not?: Prisma.NestedEnumCallTranscriptStatusWithAggregatesFilter<$PrismaModel> | $Enums.CallTranscriptStatus
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumCallTranscriptStatusFilter<$PrismaModel>
  _max?: Prisma.NestedEnumCallTranscriptStatusFilter<$PrismaModel>
}

export type NestedIntNullableWithAggregatesFilter<$PrismaModel = never> = {
  equals?: number | Prisma.IntFieldRefInput<$PrismaModel> | null
  in?: number[] | null
  notIn?: number[] | null
  lt?: number | Prisma.IntFieldRefInput<$PrismaModel>
  lte?: number | Prisma.IntFieldRefInput<$PrismaModel>
  gt?: number | Prisma.IntFieldRefInput<$PrismaModel>
  gte?: number | Prisma.IntFieldRefInput<$PrismaModel>
  not?: Prisma.NestedIntNullableWithAggregatesFilter<$PrismaModel> | number | null
  _count?: Prisma.NestedIntNullableFilter<$PrismaModel>
  _avg?: Prisma.NestedFloatNullableFilter<$PrismaModel>
  _sum?: Prisma.NestedIntNullableFilter<$PrismaModel>
  _min?: Prisma.NestedIntNullableFilter<$PrismaModel>
  _max?: Prisma.NestedIntNullableFilter<$PrismaModel>
}

export type NestedFloatNullableFilter<$PrismaModel = never> = {
  equals?: number | Prisma.FloatFieldRefInput<$PrismaModel> | null
  in?: number[] | null
  notIn?: number[] | null
  lt?: number | Prisma.FloatFieldRefInput<$PrismaModel>
  lte?: number | Prisma.FloatFieldRefInput<$PrismaModel>
  gt?: number | Prisma.FloatFieldRefInput<$PrismaModel>
  gte?: number | Prisma.FloatFieldRefInput<$PrismaModel>
  not?: Prisma.NestedFloatNullableFilter<$PrismaModel> | number | null
}

export type NestedEnumCallKentEpisodeDraftStatusFilter<$PrismaModel = never> = {
  equals?: $Enums.CallKentEpisodeDraftStatus | Prisma.EnumCallKentEpisodeDraftStatusFieldRefInput<$PrismaModel>
  in?: $Enums.CallKentEpisodeDraftStatus[]
  notIn?: $Enums.CallKentEpisodeDraftStatus[]
  not?: Prisma.NestedEnumCallKentEpisodeDraftStatusFilter<$PrismaModel> | $Enums.CallKentEpisodeDraftStatus
}

export type NestedEnumCallKentEpisodeDraftStepFilter<$PrismaModel = never> = {
  equals?: $Enums.CallKentEpisodeDraftStep | Prisma.EnumCallKentEpisodeDraftStepFieldRefInput<$PrismaModel>
  in?: $Enums.CallKentEpisodeDraftStep[]
  notIn?: $Enums.CallKentEpisodeDraftStep[]
  not?: Prisma.NestedEnumCallKentEpisodeDraftStepFilter<$PrismaModel> | $Enums.CallKentEpisodeDraftStep
}

export type NestedEnumCallKentEpisodeDraftStatusWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.CallKentEpisodeDraftStatus | Prisma.EnumCallKentEpisodeDraftStatusFieldRefInput<$PrismaModel>
  in?: $Enums.CallKentEpisodeDraftStatus[]
  notIn?: $Enums.CallKentEpisodeDraftStatus[]
  not?: Prisma.NestedEnumCallKentEpisodeDraftStatusWithAggregatesFilter<$PrismaModel> | $Enums.CallKentEpisodeDraftStatus
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumCallKentEpisodeDraftStatusFilter<$PrismaModel>
  _max?: Prisma.NestedEnumCallKentEpisodeDraftStatusFilter<$PrismaModel>
}

export type NestedEnumCallKentEpisodeDraftStepWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.CallKentEpisodeDraftStep | Prisma.EnumCallKentEpisodeDraftStepFieldRefInput<$PrismaModel>
  in?: $Enums.CallKentEpisodeDraftStep[]
  notIn?: $Enums.CallKentEpisodeDraftStep[]
  not?: Prisma.NestedEnumCallKentEpisodeDraftStepWithAggregatesFilter<$PrismaModel> | $Enums.CallKentEpisodeDraftStep
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumCallKentEpisodeDraftStepFilter<$PrismaModel>
  _max?: Prisma.NestedEnumCallKentEpisodeDraftStepFilter<$PrismaModel>
}

export type NestedBytesFilter<$PrismaModel = never> = {
  equals?: runtime.Bytes | Prisma.BytesFieldRefInput<$PrismaModel>
  in?: runtime.Bytes[]
  notIn?: runtime.Bytes[]
  not?: Prisma.NestedBytesFilter<$PrismaModel> | runtime.Bytes
}

export type NestedBigIntFilter<$PrismaModel = never> = {
  equals?: bigint | number | Prisma.BigIntFieldRefInput<$PrismaModel>
  in?: bigint[] | number[]
  notIn?: bigint[] | number[]
  lt?: bigint | number | Prisma.BigIntFieldRefInput<$PrismaModel>
  lte?: bigint | number | Prisma.BigIntFieldRefInput<$PrismaModel>
  gt?: bigint | number | Prisma.BigIntFieldRefInput<$PrismaModel>
  gte?: bigint | number | Prisma.BigIntFieldRefInput<$PrismaModel>
  not?: Prisma.NestedBigIntFilter<$PrismaModel> | bigint | number
}

export type NestedBytesWithAggregatesFilter<$PrismaModel = never> = {
  equals?: runtime.Bytes | Prisma.BytesFieldRefInput<$PrismaModel>
  in?: runtime.Bytes[]
  notIn?: runtime.Bytes[]
  not?: Prisma.NestedBytesWithAggregatesFilter<$PrismaModel> | runtime.Bytes
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedBytesFilter<$PrismaModel>
  _max?: Prisma.NestedBytesFilter<$PrismaModel>
}

export type NestedBigIntWithAggregatesFilter<$PrismaModel = never> = {
  equals?: bigint | number | Prisma.BigIntFieldRefInput<$PrismaModel>
  in?: bigint[] | number[]
  notIn?: bigint[] | number[]
  lt?: bigint | number | Prisma.BigIntFieldRefInput<$PrismaModel>
  lte?: bigint | number | Prisma.BigIntFieldRefInput<$PrismaModel>
  gt?: bigint | number | Prisma.BigIntFieldRefInput<$PrismaModel>
  gte?: bigint | number | Prisma.BigIntFieldRefInput<$PrismaModel>
  not?: Prisma.NestedBigIntWithAggregatesFilter<$PrismaModel> | bigint | number
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _avg?: Prisma.NestedFloatFilter<$PrismaModel>
  _sum?: Prisma.NestedBigIntFilter<$PrismaModel>
  _min?: Prisma.NestedBigIntFilter<$PrismaModel>
  _max?: Prisma.NestedBigIntFilter<$PrismaModel>
}

export type NestedFloatFilter<$PrismaModel = never> = {
  equals?: number | Prisma.FloatFieldRefInput<$PrismaModel>
  in?: number[]
  notIn?: number[]
  lt?: number | Prisma.FloatFieldRefInput<$PrismaModel>
  lte?: number | Prisma.FloatFieldRefInput<$PrismaModel>
  gt?: number | Prisma.FloatFieldRefInput<$PrismaModel>
  gte?: number | Prisma.FloatFieldRefInput<$PrismaModel>
  not?: Prisma.NestedFloatFilter<$PrismaModel> | number
}


