
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * WARNING: This is an internal file that is subject to change!
 *
 * 🛑 Under no circumstances should you import this file directly! 🛑
 *
 * All exports from this file are wrapped under a `Prisma` namespace object in the browser.ts file.
 * While this enables partial backward compatibility, it is not part of the stable public API.
 *
 * If you are looking for your Models, Enums, and Input Types, please import them from the respective
 * model files in the `model` directory!
 */

import * as runtime from "@prisma/client/runtime/index-browser"

export type * from '../models.ts'
export type * from './prismaNamespace.ts'

export const Decimal = runtime.Decimal


export const NullTypes = {
  DbNull: runtime.NullTypes.DbNull as (new (secret: never) => typeof runtime.DbNull),
  JsonNull: runtime.NullTypes.JsonNull as (new (secret: never) => typeof runtime.JsonNull),
  AnyNull: runtime.NullTypes.AnyNull as (new (secret: never) => typeof runtime.AnyNull),
}
/**
 * Helper for filtering JSON entries that have `null` on the database (empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const DbNull = runtime.DbNull

/**
 * Helper for filtering JSON entries that have JSON `null` values (not empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const JsonNull = runtime.JsonNull

/**
 * Helper for filtering JSON entries that are `Prisma.DbNull` or `Prisma.JsonNull`
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const AnyNull = runtime.AnyNull


export const ModelName = {
  User: 'User',
  Password: 'Password',
  Verification: 'Verification',
  Session: 'Session',
  Call: 'Call',
  CallKentEpisodeDraft: 'CallKentEpisodeDraft',
  CallKentCallerEpisode: 'CallKentCallerEpisode',
  PostRead: 'PostRead',
  Passkey: 'Passkey',
  Favorite: 'Favorite'
} as const

export type ModelName = (typeof ModelName)[keyof typeof ModelName]

/*
 * Enums
 */

export const TransactionIsolationLevel = runtime.makeStrictEnum({
  Serializable: 'Serializable'
} as const)

export type TransactionIsolationLevel = (typeof TransactionIsolationLevel)[keyof typeof TransactionIsolationLevel]


export const UserScalarFieldEnum = {
  id: 'id',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  email: 'email',
  firstName: 'firstName',
  discordId: 'discordId',
  kitId: 'kitId',
  role: 'role',
  team: 'team'
} as const

export type UserScalarFieldEnum = (typeof UserScalarFieldEnum)[keyof typeof UserScalarFieldEnum]


export const PasswordScalarFieldEnum = {
  hash: 'hash',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  userId: 'userId'
} as const

export type PasswordScalarFieldEnum = (typeof PasswordScalarFieldEnum)[keyof typeof PasswordScalarFieldEnum]


export const VerificationScalarFieldEnum = {
  id: 'id',
  createdAt: 'createdAt',
  type: 'type',
  target: 'target',
  codeHash: 'codeHash',
  expiresAt: 'expiresAt'
} as const

export type VerificationScalarFieldEnum = (typeof VerificationScalarFieldEnum)[keyof typeof VerificationScalarFieldEnum]


export const SessionScalarFieldEnum = {
  id: 'id',
  createdAt: 'createdAt',
  userId: 'userId',
  expirationDate: 'expirationDate'
} as const

export type SessionScalarFieldEnum = (typeof SessionScalarFieldEnum)[keyof typeof SessionScalarFieldEnum]


export const CallScalarFieldEnum = {
  id: 'id',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  title: 'title',
  notes: 'notes',
  isAnonymous: 'isAnonymous',
  callerTranscript: 'callerTranscript',
  callerTranscriptStatus: 'callerTranscriptStatus',
  callerTranscriptErrorMessage: 'callerTranscriptErrorMessage',
  userId: 'userId',
  audioKey: 'audioKey',
  audioContentType: 'audioContentType',
  audioSize: 'audioSize'
} as const

export type CallScalarFieldEnum = (typeof CallScalarFieldEnum)[keyof typeof CallScalarFieldEnum]


export const CallKentEpisodeDraftScalarFieldEnum = {
  id: 'id',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  status: 'status',
  step: 'step',
  errorMessage: 'errorMessage',
  episodeAudioKey: 'episodeAudioKey',
  episodeAudioContentType: 'episodeAudioContentType',
  episodeAudioSize: 'episodeAudioSize',
  responseAudioKey: 'responseAudioKey',
  responseAudioContentType: 'responseAudioContentType',
  responseAudioSize: 'responseAudioSize',
  callerSegmentAudioKey: 'callerSegmentAudioKey',
  responseSegmentAudioKey: 'responseSegmentAudioKey',
  transcript: 'transcript',
  title: 'title',
  description: 'description',
  keywords: 'keywords',
  callId: 'callId'
} as const

export type CallKentEpisodeDraftScalarFieldEnum = (typeof CallKentEpisodeDraftScalarFieldEnum)[keyof typeof CallKentEpisodeDraftScalarFieldEnum]


export const CallKentCallerEpisodeScalarFieldEnum = {
  id: 'id',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  userId: 'userId',
  callTitle: 'callTitle',
  callNotes: 'callNotes',
  isAnonymous: 'isAnonymous',
  transistorEpisodeId: 'transistorEpisodeId'
} as const

export type CallKentCallerEpisodeScalarFieldEnum = (typeof CallKentCallerEpisodeScalarFieldEnum)[keyof typeof CallKentCallerEpisodeScalarFieldEnum]


export const PostReadScalarFieldEnum = {
  id: 'id',
  createdAt: 'createdAt',
  userId: 'userId',
  clientId: 'clientId',
  postSlug: 'postSlug'
} as const

export type PostReadScalarFieldEnum = (typeof PostReadScalarFieldEnum)[keyof typeof PostReadScalarFieldEnum]


export const PasskeyScalarFieldEnum = {
  id: 'id',
  aaguid: 'aaguid',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  publicKey: 'publicKey',
  userId: 'userId',
  webauthnUserId: 'webauthnUserId',
  counter: 'counter',
  deviceType: 'deviceType',
  backedUp: 'backedUp',
  transports: 'transports'
} as const

export type PasskeyScalarFieldEnum = (typeof PasskeyScalarFieldEnum)[keyof typeof PasskeyScalarFieldEnum]


export const FavoriteScalarFieldEnum = {
  id: 'id',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  userId: 'userId',
  contentType: 'contentType',
  contentId: 'contentId'
} as const

export type FavoriteScalarFieldEnum = (typeof FavoriteScalarFieldEnum)[keyof typeof FavoriteScalarFieldEnum]


export const SortOrder = {
  asc: 'asc',
  desc: 'desc'
} as const

export type SortOrder = (typeof SortOrder)[keyof typeof SortOrder]


export const NullsOrder = {
  first: 'first',
  last: 'last'
} as const

export type NullsOrder = (typeof NullsOrder)[keyof typeof NullsOrder]

